// #Sireum

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

package tc.TempControlMixedSeL4CAmKES

import org.sireum._
import art._

@ext object TempSensor_tsp_tst_seL4Nix {
  // send payload 'd' to components connected to seL4's currentTemp port
  def currentTemp_Send(d: DataContent): Unit = $

  // send payload 'd' to components connected to seL4's tempChanged port
  def tempChanged_Send(d: DataContent): Unit = $
}
