#include <all.h>

B Type__eq(void *t1, void *t2) {
  TYPE type = ((Type) t1)->type;
  if (type != ((Type) t2)->type) return F;
  switch (type) {
    case TIS_948B60: return IS_948B60__eq((IS_948B60) t1, (IS_948B60) t2);
    case TNone_BE2C3F: return None_BE2C3F__eq((None_BE2C3F) t1, (None_BE2C3F) t2);
    case TNone_BE24EA: return None_BE24EA__eq((None_BE24EA) t1, (None_BE24EA) t2);
    case TNone_3C78E7: return None_3C78E7__eq((None_3C78E7) t1, (None_3C78E7) t2);
    case TNone_A45A41: return None_A45A41__eq((None_A45A41) t1, (None_A45A41) t2);
    case TNone_A23E58: return None_A23E58__eq((None_A23E58) t1, (None_A23E58) t2);
    case TNone_B4A4FA: return None_B4A4FA__eq((None_B4A4FA) t1, (None_B4A4FA) t2);
    case TNone_1AEC2C: return None_1AEC2C__eq((None_1AEC2C) t1, (None_1AEC2C) t2);
    case TNone_121724: return None_121724__eq((None_121724) t1, (None_121724) t2);
    case TNone_A70CEE: return None_A70CEE__eq((None_A70CEE) t1, (None_A70CEE) t2);
    case TNone_ACDB63: return None_ACDB63__eq((None_ACDB63) t1, (None_ACDB63) t2);
    case TNone_86BF24: return None_86BF24__eq((None_86BF24) t1, (None_86BF24) t2);
    case TNone_D4B208: return None_D4B208__eq((None_D4B208) t1, (None_D4B208) t2);
    case TNone_037804: return None_037804__eq((None_037804) t1, (None_037804) t2);
    case TNone_4E7E94: return None_4E7E94__eq((None_4E7E94) t1, (None_4E7E94) t2);
    case TSome_455777: return Some_455777__eq((Some_455777) t1, (Some_455777) t2);
    case TSome_F1808D: return Some_F1808D__eq((Some_F1808D) t1, (Some_F1808D) t2);
    case TSome_C790DA: return Some_C790DA__eq((Some_C790DA) t1, (Some_C790DA) t2);
    case TSome_140719: return Some_140719__eq((Some_140719) t1, (Some_140719) t2);
    case TSome_21C1E5: return Some_21C1E5__eq((Some_21C1E5) t1, (Some_21C1E5) t2);
    case TSome_270A8B: return Some_270A8B__eq((Some_270A8B) t1, (Some_270A8B) t2);
    case TSome_776961: return Some_776961__eq((Some_776961) t1, (Some_776961) t2);
    case TSome_0E3FBA: return Some_0E3FBA__eq((Some_0E3FBA) t1, (Some_0E3FBA) t2);
    case TSome_D85467: return Some_D85467__eq((Some_D85467) t1, (Some_D85467) t2);
    case TSome_2EFA7D: return Some_2EFA7D__eq((Some_2EFA7D) t1, (Some_2EFA7D) t2);
    case TSome_0C4CF8: return Some_0C4CF8__eq((Some_0C4CF8) t1, (Some_0C4CF8) t2);
    case TSome_C3173C: return Some_C3173C__eq((Some_C3173C) t1, (Some_C3173C) t2);
    case TSome_C0DBA9: return Some_C0DBA9__eq((Some_C0DBA9) t1, (Some_C0DBA9) t2);
    case TSome_56FCC9: return Some_56FCC9__eq((Some_56FCC9) t1, (Some_56FCC9) t2);
    case TString: return String__eq((String) t1, (String) t2);
    case Tart_Empty: return art_Empty__eq((art_Empty) t1, (art_Empty) t2);
    case Ttc_Base_Types_Boolean_Payload: return tc_Base_Types_Boolean_Payload__eq((tc_Base_Types_Boolean_Payload) t1, (tc_Base_Types_Boolean_Payload) t2);
    case Ttc_Base_Types_Character_Payload: return tc_Base_Types_Character_Payload__eq((tc_Base_Types_Character_Payload) t1, (tc_Base_Types_Character_Payload) t2);
    case Ttc_Base_Types_Float_32_Payload: return tc_Base_Types_Float_32_Payload__eq((tc_Base_Types_Float_32_Payload) t1, (tc_Base_Types_Float_32_Payload) t2);
    case Ttc_Base_Types_Float_64_Payload: return tc_Base_Types_Float_64_Payload__eq((tc_Base_Types_Float_64_Payload) t1, (tc_Base_Types_Float_64_Payload) t2);
    case Ttc_Base_Types_Float_Payload: return tc_Base_Types_Float_Payload__eq((tc_Base_Types_Float_Payload) t1, (tc_Base_Types_Float_Payload) t2);
    case Ttc_Base_Types_Integer_16_Payload: return tc_Base_Types_Integer_16_Payload__eq((tc_Base_Types_Integer_16_Payload) t1, (tc_Base_Types_Integer_16_Payload) t2);
    case Ttc_Base_Types_Integer_32_Payload: return tc_Base_Types_Integer_32_Payload__eq((tc_Base_Types_Integer_32_Payload) t1, (tc_Base_Types_Integer_32_Payload) t2);
    case Ttc_Base_Types_Integer_64_Payload: return tc_Base_Types_Integer_64_Payload__eq((tc_Base_Types_Integer_64_Payload) t1, (tc_Base_Types_Integer_64_Payload) t2);
    case Ttc_Base_Types_Integer_8_Payload: return tc_Base_Types_Integer_8_Payload__eq((tc_Base_Types_Integer_8_Payload) t1, (tc_Base_Types_Integer_8_Payload) t2);
    case Ttc_Base_Types_Integer_Payload: return tc_Base_Types_Integer_Payload__eq((tc_Base_Types_Integer_Payload) t1, (tc_Base_Types_Integer_Payload) t2);
    case Ttc_Base_Types_String_Payload: return tc_Base_Types_String_Payload__eq((tc_Base_Types_String_Payload) t1, (tc_Base_Types_String_Payload) t2);
    case Ttc_Base_Types_Unsigned_16_Payload: return tc_Base_Types_Unsigned_16_Payload__eq((tc_Base_Types_Unsigned_16_Payload) t1, (tc_Base_Types_Unsigned_16_Payload) t2);
    case Ttc_Base_Types_Unsigned_32_Payload: return tc_Base_Types_Unsigned_32_Payload__eq((tc_Base_Types_Unsigned_32_Payload) t1, (tc_Base_Types_Unsigned_32_Payload) t2);
    case Ttc_Base_Types_Unsigned_64_Payload: return tc_Base_Types_Unsigned_64_Payload__eq((tc_Base_Types_Unsigned_64_Payload) t1, (tc_Base_Types_Unsigned_64_Payload) t2);
    case Ttc_Base_Types_Unsigned_8_Payload: return tc_Base_Types_Unsigned_8_Payload__eq((tc_Base_Types_Unsigned_8_Payload) t1, (tc_Base_Types_Unsigned_8_Payload) t2);
    case Ttc_Isolette_Data_Model_Failure_Flag: return tc_Isolette_Data_Model_Failure_Flag__eq((tc_Isolette_Data_Model_Failure_Flag) t1, (tc_Isolette_Data_Model_Failure_Flag) t2);
    case Ttc_Isolette_Data_Model_Failure_Flag_Payload: return tc_Isolette_Data_Model_Failure_Flag_Payload__eq((tc_Isolette_Data_Model_Failure_Flag_Payload) t1, (tc_Isolette_Data_Model_Failure_Flag_Payload) t2);
    case Ttc_Isolette_Data_Model_Monitor_Mode_Payload: return tc_Isolette_Data_Model_Monitor_Mode_Payload__eq((tc_Isolette_Data_Model_Monitor_Mode_Payload) t1, (tc_Isolette_Data_Model_Monitor_Mode_Payload) t2);
    case Ttc_Isolette_Data_Model_On_Off_Payload: return tc_Isolette_Data_Model_On_Off_Payload__eq((tc_Isolette_Data_Model_On_Off_Payload) t1, (tc_Isolette_Data_Model_On_Off_Payload) t2);
    case Ttc_Isolette_Data_Model_PhysicalTemp: return tc_Isolette_Data_Model_PhysicalTemp__eq((tc_Isolette_Data_Model_PhysicalTemp) t1, (tc_Isolette_Data_Model_PhysicalTemp) t2);
    case Ttc_Isolette_Data_Model_PhysicalTemp_Payload: return tc_Isolette_Data_Model_PhysicalTemp_Payload__eq((tc_Isolette_Data_Model_PhysicalTemp_Payload) t1, (tc_Isolette_Data_Model_PhysicalTemp_Payload) t2);
    case Ttc_Isolette_Data_Model_Regulator_Mode_Payload: return tc_Isolette_Data_Model_Regulator_Mode_Payload__eq((tc_Isolette_Data_Model_Regulator_Mode_Payload) t1, (tc_Isolette_Data_Model_Regulator_Mode_Payload) t2);
    case Ttc_Isolette_Data_Model_Status_Payload: return tc_Isolette_Data_Model_Status_Payload__eq((tc_Isolette_Data_Model_Status_Payload) t1, (tc_Isolette_Data_Model_Status_Payload) t2);
    case Ttc_Isolette_Data_Model_Temp: return tc_Isolette_Data_Model_Temp__eq((tc_Isolette_Data_Model_Temp) t1, (tc_Isolette_Data_Model_Temp) t2);
    case Ttc_Isolette_Data_Model_TempWstatus: return tc_Isolette_Data_Model_TempWstatus__eq((tc_Isolette_Data_Model_TempWstatus) t1, (tc_Isolette_Data_Model_TempWstatus) t2);
    case Ttc_Isolette_Data_Model_TempWstatus_Payload: return tc_Isolette_Data_Model_TempWstatus_Payload__eq((tc_Isolette_Data_Model_TempWstatus_Payload) t1, (tc_Isolette_Data_Model_TempWstatus_Payload) t2);
    case Ttc_Isolette_Data_Model_Temp_Payload: return tc_Isolette_Data_Model_Temp_Payload__eq((tc_Isolette_Data_Model_Temp_Payload) t1, (tc_Isolette_Data_Model_Temp_Payload) t2);
    case Ttc_Isolette_Data_Model_ValueStatus_Payload: return tc_Isolette_Data_Model_ValueStatus_Payload__eq((tc_Isolette_Data_Model_ValueStatus_Payload) t1, (tc_Isolette_Data_Model_ValueStatus_Payload) t2);
    case Ttc_Isolette_Environment_Air_Interaction: return tc_Isolette_Environment_Air_Interaction__eq((tc_Isolette_Environment_Air_Interaction) t1, (tc_Isolette_Environment_Air_Interaction) t2);
    case Ttc_Isolette_Environment_Air_Interaction_Payload: return tc_Isolette_Environment_Air_Interaction_Payload__eq((tc_Isolette_Environment_Air_Interaction_Payload) t1, (tc_Isolette_Environment_Air_Interaction_Payload) t2);
    case Ttc_Isolette_Environment_Heat: return tc_Isolette_Environment_Heat__eq((tc_Isolette_Environment_Heat) t1, (tc_Isolette_Environment_Heat) t2);
    case Ttc_Isolette_Environment_Heat_Payload: return tc_Isolette_Environment_Heat_Payload__eq((tc_Isolette_Environment_Heat_Payload) t1, (tc_Isolette_Environment_Heat_Payload) t2);
    case Ttc_Isolette_Environment_Interface_Interaction: return tc_Isolette_Environment_Interface_Interaction__eq((tc_Isolette_Environment_Interface_Interaction) t1, (tc_Isolette_Environment_Interface_Interaction) t2);
    case Ttc_Isolette_Environment_Interface_Interaction_Payload: return tc_Isolette_Environment_Interface_Interaction_Payload__eq((tc_Isolette_Environment_Interface_Interaction_Payload) t1, (tc_Isolette_Environment_Interface_Interaction_Payload) t2);
    case Ttc_TempControlMixed_FanAck_Payload: return tc_TempControlMixed_FanAck_Payload__eq((tc_TempControlMixed_FanAck_Payload) t1, (tc_TempControlMixed_FanAck_Payload) t2);
    case Ttc_TempControlMixed_FanCmd_Payload: return tc_TempControlMixed_FanCmd_Payload__eq((tc_TempControlMixed_FanCmd_Payload) t1, (tc_TempControlMixed_FanCmd_Payload) t2);
    case Ttc_TempControlMixed_SetPoint: return tc_TempControlMixed_SetPoint__eq((tc_TempControlMixed_SetPoint) t1, (tc_TempControlMixed_SetPoint) t2);
    case Ttc_TempControlMixed_SetPoint_Payload: return tc_TempControlMixed_SetPoint_Payload__eq((tc_TempControlMixed_SetPoint_Payload) t1, (tc_TempControlMixed_SetPoint_Payload) t2);
    case Ttc_TempControlMixed_TempUnit_Payload: return tc_TempControlMixed_TempUnit_Payload__eq((tc_TempControlMixed_TempUnit_Payload) t1, (tc_TempControlMixed_TempUnit_Payload) t2);
    case Ttc_TempControlMixed_Temperature: return tc_TempControlMixed_Temperature__eq((tc_TempControlMixed_Temperature) t1, (tc_TempControlMixed_Temperature) t2);
    case Ttc_TempControlMixed_Temperature_Payload: return tc_TempControlMixed_Temperature_Payload__eq((tc_TempControlMixed_Temperature_Payload) t1, (tc_TempControlMixed_Temperature_Payload) t2);
    case Ttc_TempControlMixedSeL4CAmKES_FanAck_Payload: return tc_TempControlMixedSeL4CAmKES_FanAck_Payload__eq((tc_TempControlMixedSeL4CAmKES_FanAck_Payload) t1, (tc_TempControlMixedSeL4CAmKES_FanAck_Payload) t2);
    case Ttc_TempControlMixedSeL4CAmKES_FanCmd_Payload: return tc_TempControlMixedSeL4CAmKES_FanCmd_Payload__eq((tc_TempControlMixedSeL4CAmKES_FanCmd_Payload) t1, (tc_TempControlMixedSeL4CAmKES_FanCmd_Payload) t2);
    case Ttc_TempControlMixedSeL4CAmKES_SetPoint: return tc_TempControlMixedSeL4CAmKES_SetPoint__eq((tc_TempControlMixedSeL4CAmKES_SetPoint) t1, (tc_TempControlMixedSeL4CAmKES_SetPoint) t2);
    case Ttc_TempControlMixedSeL4CAmKES_SetPoint_Payload: return tc_TempControlMixedSeL4CAmKES_SetPoint_Payload__eq((tc_TempControlMixedSeL4CAmKES_SetPoint_Payload) t1, (tc_TempControlMixedSeL4CAmKES_SetPoint_Payload) t2);
    case Ttc_TempControlMixedSeL4CAmKES_TempUnit_Payload: return tc_TempControlMixedSeL4CAmKES_TempUnit_Payload__eq((tc_TempControlMixedSeL4CAmKES_TempUnit_Payload) t1, (tc_TempControlMixedSeL4CAmKES_TempUnit_Payload) t2);
    case Ttc_TempControlMixedSeL4CAmKES_Temperature: return tc_TempControlMixedSeL4CAmKES_Temperature__eq((tc_TempControlMixedSeL4CAmKES_Temperature) t1, (tc_TempControlMixedSeL4CAmKES_Temperature) t2);
    case Ttc_TempControlMixedSeL4CAmKES_Temperature_Payload: return tc_TempControlMixedSeL4CAmKES_Temperature_Payload__eq((tc_TempControlMixedSeL4CAmKES_Temperature_Payload) t1, (tc_TempControlMixedSeL4CAmKES_Temperature_Payload) t2);
    case Ttc_TempControlPeriodic_FanAck_Payload: return tc_TempControlPeriodic_FanAck_Payload__eq((tc_TempControlPeriodic_FanAck_Payload) t1, (tc_TempControlPeriodic_FanAck_Payload) t2);
    case Ttc_TempControlPeriodic_FanCmd_Payload: return tc_TempControlPeriodic_FanCmd_Payload__eq((tc_TempControlPeriodic_FanCmd_Payload) t1, (tc_TempControlPeriodic_FanCmd_Payload) t2);
    case Ttc_TempControlPeriodic_SetPoint: return tc_TempControlPeriodic_SetPoint__eq((tc_TempControlPeriodic_SetPoint) t1, (tc_TempControlPeriodic_SetPoint) t2);
    case Ttc_TempControlPeriodic_SetPoint_Payload: return tc_TempControlPeriodic_SetPoint_Payload__eq((tc_TempControlPeriodic_SetPoint_Payload) t1, (tc_TempControlPeriodic_SetPoint_Payload) t2);
    case Ttc_TempControlPeriodic_TempUnit_Payload: return tc_TempControlPeriodic_TempUnit_Payload__eq((tc_TempControlPeriodic_TempUnit_Payload) t1, (tc_TempControlPeriodic_TempUnit_Payload) t2);
    case Ttc_TempControlPeriodic_Temperature: return tc_TempControlPeriodic_Temperature__eq((tc_TempControlPeriodic_Temperature) t1, (tc_TempControlPeriodic_Temperature) t2);
    case Ttc_TempControlPeriodic_Temperature_Payload: return tc_TempControlPeriodic_Temperature_Payload__eq((tc_TempControlPeriodic_Temperature_Payload) t1, (tc_TempControlPeriodic_Temperature_Payload) t2);
    default: fprintf(stderr, "%s: %d\n", "Unexpected TYPE: ", type); exit(1);
  }
}

B Type__equiv(void *t1, void *t2) {
  TYPE type = ((Type) t1)->type;
  if (type != ((Type) t2)->type) return F;
  switch (type) {
    case TIS_948B60: return IS_948B60__equiv((IS_948B60) t1, (IS_948B60) t2);
    case TNone_BE2C3F: return None_BE2C3F__equiv((None_BE2C3F) t1, (None_BE2C3F) t2);
    case TNone_BE24EA: return None_BE24EA__equiv((None_BE24EA) t1, (None_BE24EA) t2);
    case TNone_3C78E7: return None_3C78E7__equiv((None_3C78E7) t1, (None_3C78E7) t2);
    case TNone_A45A41: return None_A45A41__equiv((None_A45A41) t1, (None_A45A41) t2);
    case TNone_A23E58: return None_A23E58__equiv((None_A23E58) t1, (None_A23E58) t2);
    case TNone_B4A4FA: return None_B4A4FA__equiv((None_B4A4FA) t1, (None_B4A4FA) t2);
    case TNone_1AEC2C: return None_1AEC2C__equiv((None_1AEC2C) t1, (None_1AEC2C) t2);
    case TNone_121724: return None_121724__equiv((None_121724) t1, (None_121724) t2);
    case TNone_A70CEE: return None_A70CEE__equiv((None_A70CEE) t1, (None_A70CEE) t2);
    case TNone_ACDB63: return None_ACDB63__equiv((None_ACDB63) t1, (None_ACDB63) t2);
    case TNone_86BF24: return None_86BF24__equiv((None_86BF24) t1, (None_86BF24) t2);
    case TNone_D4B208: return None_D4B208__equiv((None_D4B208) t1, (None_D4B208) t2);
    case TNone_037804: return None_037804__equiv((None_037804) t1, (None_037804) t2);
    case TNone_4E7E94: return None_4E7E94__equiv((None_4E7E94) t1, (None_4E7E94) t2);
    case TSome_455777: return Some_455777__equiv((Some_455777) t1, (Some_455777) t2);
    case TSome_F1808D: return Some_F1808D__equiv((Some_F1808D) t1, (Some_F1808D) t2);
    case TSome_C790DA: return Some_C790DA__equiv((Some_C790DA) t1, (Some_C790DA) t2);
    case TSome_140719: return Some_140719__equiv((Some_140719) t1, (Some_140719) t2);
    case TSome_21C1E5: return Some_21C1E5__equiv((Some_21C1E5) t1, (Some_21C1E5) t2);
    case TSome_270A8B: return Some_270A8B__equiv((Some_270A8B) t1, (Some_270A8B) t2);
    case TSome_776961: return Some_776961__equiv((Some_776961) t1, (Some_776961) t2);
    case TSome_0E3FBA: return Some_0E3FBA__equiv((Some_0E3FBA) t1, (Some_0E3FBA) t2);
    case TSome_D85467: return Some_D85467__equiv((Some_D85467) t1, (Some_D85467) t2);
    case TSome_2EFA7D: return Some_2EFA7D__equiv((Some_2EFA7D) t1, (Some_2EFA7D) t2);
    case TSome_0C4CF8: return Some_0C4CF8__equiv((Some_0C4CF8) t1, (Some_0C4CF8) t2);
    case TSome_C3173C: return Some_C3173C__equiv((Some_C3173C) t1, (Some_C3173C) t2);
    case TSome_C0DBA9: return Some_C0DBA9__equiv((Some_C0DBA9) t1, (Some_C0DBA9) t2);
    case TSome_56FCC9: return Some_56FCC9__equiv((Some_56FCC9) t1, (Some_56FCC9) t2);
    case TString: return String__equiv((String) t1, (String) t2);
    case Tart_Empty: return art_Empty__equiv((art_Empty) t1, (art_Empty) t2);
    case Ttc_Base_Types_Boolean_Payload: return tc_Base_Types_Boolean_Payload__equiv((tc_Base_Types_Boolean_Payload) t1, (tc_Base_Types_Boolean_Payload) t2);
    case Ttc_Base_Types_Character_Payload: return tc_Base_Types_Character_Payload__equiv((tc_Base_Types_Character_Payload) t1, (tc_Base_Types_Character_Payload) t2);
    case Ttc_Base_Types_Float_32_Payload: return tc_Base_Types_Float_32_Payload__equiv((tc_Base_Types_Float_32_Payload) t1, (tc_Base_Types_Float_32_Payload) t2);
    case Ttc_Base_Types_Float_64_Payload: return tc_Base_Types_Float_64_Payload__equiv((tc_Base_Types_Float_64_Payload) t1, (tc_Base_Types_Float_64_Payload) t2);
    case Ttc_Base_Types_Float_Payload: return tc_Base_Types_Float_Payload__equiv((tc_Base_Types_Float_Payload) t1, (tc_Base_Types_Float_Payload) t2);
    case Ttc_Base_Types_Integer_16_Payload: return tc_Base_Types_Integer_16_Payload__equiv((tc_Base_Types_Integer_16_Payload) t1, (tc_Base_Types_Integer_16_Payload) t2);
    case Ttc_Base_Types_Integer_32_Payload: return tc_Base_Types_Integer_32_Payload__equiv((tc_Base_Types_Integer_32_Payload) t1, (tc_Base_Types_Integer_32_Payload) t2);
    case Ttc_Base_Types_Integer_64_Payload: return tc_Base_Types_Integer_64_Payload__equiv((tc_Base_Types_Integer_64_Payload) t1, (tc_Base_Types_Integer_64_Payload) t2);
    case Ttc_Base_Types_Integer_8_Payload: return tc_Base_Types_Integer_8_Payload__equiv((tc_Base_Types_Integer_8_Payload) t1, (tc_Base_Types_Integer_8_Payload) t2);
    case Ttc_Base_Types_Integer_Payload: return tc_Base_Types_Integer_Payload__equiv((tc_Base_Types_Integer_Payload) t1, (tc_Base_Types_Integer_Payload) t2);
    case Ttc_Base_Types_String_Payload: return tc_Base_Types_String_Payload__equiv((tc_Base_Types_String_Payload) t1, (tc_Base_Types_String_Payload) t2);
    case Ttc_Base_Types_Unsigned_16_Payload: return tc_Base_Types_Unsigned_16_Payload__equiv((tc_Base_Types_Unsigned_16_Payload) t1, (tc_Base_Types_Unsigned_16_Payload) t2);
    case Ttc_Base_Types_Unsigned_32_Payload: return tc_Base_Types_Unsigned_32_Payload__equiv((tc_Base_Types_Unsigned_32_Payload) t1, (tc_Base_Types_Unsigned_32_Payload) t2);
    case Ttc_Base_Types_Unsigned_64_Payload: return tc_Base_Types_Unsigned_64_Payload__equiv((tc_Base_Types_Unsigned_64_Payload) t1, (tc_Base_Types_Unsigned_64_Payload) t2);
    case Ttc_Base_Types_Unsigned_8_Payload: return tc_Base_Types_Unsigned_8_Payload__equiv((tc_Base_Types_Unsigned_8_Payload) t1, (tc_Base_Types_Unsigned_8_Payload) t2);
    case Ttc_Isolette_Data_Model_Failure_Flag: return tc_Isolette_Data_Model_Failure_Flag__equiv((tc_Isolette_Data_Model_Failure_Flag) t1, (tc_Isolette_Data_Model_Failure_Flag) t2);
    case Ttc_Isolette_Data_Model_Failure_Flag_Payload: return tc_Isolette_Data_Model_Failure_Flag_Payload__equiv((tc_Isolette_Data_Model_Failure_Flag_Payload) t1, (tc_Isolette_Data_Model_Failure_Flag_Payload) t2);
    case Ttc_Isolette_Data_Model_Monitor_Mode_Payload: return tc_Isolette_Data_Model_Monitor_Mode_Payload__equiv((tc_Isolette_Data_Model_Monitor_Mode_Payload) t1, (tc_Isolette_Data_Model_Monitor_Mode_Payload) t2);
    case Ttc_Isolette_Data_Model_On_Off_Payload: return tc_Isolette_Data_Model_On_Off_Payload__equiv((tc_Isolette_Data_Model_On_Off_Payload) t1, (tc_Isolette_Data_Model_On_Off_Payload) t2);
    case Ttc_Isolette_Data_Model_PhysicalTemp: return tc_Isolette_Data_Model_PhysicalTemp__equiv((tc_Isolette_Data_Model_PhysicalTemp) t1, (tc_Isolette_Data_Model_PhysicalTemp) t2);
    case Ttc_Isolette_Data_Model_PhysicalTemp_Payload: return tc_Isolette_Data_Model_PhysicalTemp_Payload__equiv((tc_Isolette_Data_Model_PhysicalTemp_Payload) t1, (tc_Isolette_Data_Model_PhysicalTemp_Payload) t2);
    case Ttc_Isolette_Data_Model_Regulator_Mode_Payload: return tc_Isolette_Data_Model_Regulator_Mode_Payload__equiv((tc_Isolette_Data_Model_Regulator_Mode_Payload) t1, (tc_Isolette_Data_Model_Regulator_Mode_Payload) t2);
    case Ttc_Isolette_Data_Model_Status_Payload: return tc_Isolette_Data_Model_Status_Payload__equiv((tc_Isolette_Data_Model_Status_Payload) t1, (tc_Isolette_Data_Model_Status_Payload) t2);
    case Ttc_Isolette_Data_Model_Temp: return tc_Isolette_Data_Model_Temp__equiv((tc_Isolette_Data_Model_Temp) t1, (tc_Isolette_Data_Model_Temp) t2);
    case Ttc_Isolette_Data_Model_TempWstatus: return tc_Isolette_Data_Model_TempWstatus__equiv((tc_Isolette_Data_Model_TempWstatus) t1, (tc_Isolette_Data_Model_TempWstatus) t2);
    case Ttc_Isolette_Data_Model_TempWstatus_Payload: return tc_Isolette_Data_Model_TempWstatus_Payload__equiv((tc_Isolette_Data_Model_TempWstatus_Payload) t1, (tc_Isolette_Data_Model_TempWstatus_Payload) t2);
    case Ttc_Isolette_Data_Model_Temp_Payload: return tc_Isolette_Data_Model_Temp_Payload__equiv((tc_Isolette_Data_Model_Temp_Payload) t1, (tc_Isolette_Data_Model_Temp_Payload) t2);
    case Ttc_Isolette_Data_Model_ValueStatus_Payload: return tc_Isolette_Data_Model_ValueStatus_Payload__equiv((tc_Isolette_Data_Model_ValueStatus_Payload) t1, (tc_Isolette_Data_Model_ValueStatus_Payload) t2);
    case Ttc_Isolette_Environment_Air_Interaction: return tc_Isolette_Environment_Air_Interaction__equiv((tc_Isolette_Environment_Air_Interaction) t1, (tc_Isolette_Environment_Air_Interaction) t2);
    case Ttc_Isolette_Environment_Air_Interaction_Payload: return tc_Isolette_Environment_Air_Interaction_Payload__equiv((tc_Isolette_Environment_Air_Interaction_Payload) t1, (tc_Isolette_Environment_Air_Interaction_Payload) t2);
    case Ttc_Isolette_Environment_Heat: return tc_Isolette_Environment_Heat__equiv((tc_Isolette_Environment_Heat) t1, (tc_Isolette_Environment_Heat) t2);
    case Ttc_Isolette_Environment_Heat_Payload: return tc_Isolette_Environment_Heat_Payload__equiv((tc_Isolette_Environment_Heat_Payload) t1, (tc_Isolette_Environment_Heat_Payload) t2);
    case Ttc_Isolette_Environment_Interface_Interaction: return tc_Isolette_Environment_Interface_Interaction__equiv((tc_Isolette_Environment_Interface_Interaction) t1, (tc_Isolette_Environment_Interface_Interaction) t2);
    case Ttc_Isolette_Environment_Interface_Interaction_Payload: return tc_Isolette_Environment_Interface_Interaction_Payload__equiv((tc_Isolette_Environment_Interface_Interaction_Payload) t1, (tc_Isolette_Environment_Interface_Interaction_Payload) t2);
    case Ttc_TempControlMixed_FanAck_Payload: return tc_TempControlMixed_FanAck_Payload__equiv((tc_TempControlMixed_FanAck_Payload) t1, (tc_TempControlMixed_FanAck_Payload) t2);
    case Ttc_TempControlMixed_FanCmd_Payload: return tc_TempControlMixed_FanCmd_Payload__equiv((tc_TempControlMixed_FanCmd_Payload) t1, (tc_TempControlMixed_FanCmd_Payload) t2);
    case Ttc_TempControlMixed_SetPoint: return tc_TempControlMixed_SetPoint__equiv((tc_TempControlMixed_SetPoint) t1, (tc_TempControlMixed_SetPoint) t2);
    case Ttc_TempControlMixed_SetPoint_Payload: return tc_TempControlMixed_SetPoint_Payload__equiv((tc_TempControlMixed_SetPoint_Payload) t1, (tc_TempControlMixed_SetPoint_Payload) t2);
    case Ttc_TempControlMixed_TempUnit_Payload: return tc_TempControlMixed_TempUnit_Payload__equiv((tc_TempControlMixed_TempUnit_Payload) t1, (tc_TempControlMixed_TempUnit_Payload) t2);
    case Ttc_TempControlMixed_Temperature: return tc_TempControlMixed_Temperature__equiv((tc_TempControlMixed_Temperature) t1, (tc_TempControlMixed_Temperature) t2);
    case Ttc_TempControlMixed_Temperature_Payload: return tc_TempControlMixed_Temperature_Payload__equiv((tc_TempControlMixed_Temperature_Payload) t1, (tc_TempControlMixed_Temperature_Payload) t2);
    case Ttc_TempControlMixedSeL4CAmKES_FanAck_Payload: return tc_TempControlMixedSeL4CAmKES_FanAck_Payload__equiv((tc_TempControlMixedSeL4CAmKES_FanAck_Payload) t1, (tc_TempControlMixedSeL4CAmKES_FanAck_Payload) t2);
    case Ttc_TempControlMixedSeL4CAmKES_FanCmd_Payload: return tc_TempControlMixedSeL4CAmKES_FanCmd_Payload__equiv((tc_TempControlMixedSeL4CAmKES_FanCmd_Payload) t1, (tc_TempControlMixedSeL4CAmKES_FanCmd_Payload) t2);
    case Ttc_TempControlMixedSeL4CAmKES_SetPoint: return tc_TempControlMixedSeL4CAmKES_SetPoint__equiv((tc_TempControlMixedSeL4CAmKES_SetPoint) t1, (tc_TempControlMixedSeL4CAmKES_SetPoint) t2);
    case Ttc_TempControlMixedSeL4CAmKES_SetPoint_Payload: return tc_TempControlMixedSeL4CAmKES_SetPoint_Payload__equiv((tc_TempControlMixedSeL4CAmKES_SetPoint_Payload) t1, (tc_TempControlMixedSeL4CAmKES_SetPoint_Payload) t2);
    case Ttc_TempControlMixedSeL4CAmKES_TempUnit_Payload: return tc_TempControlMixedSeL4CAmKES_TempUnit_Payload__equiv((tc_TempControlMixedSeL4CAmKES_TempUnit_Payload) t1, (tc_TempControlMixedSeL4CAmKES_TempUnit_Payload) t2);
    case Ttc_TempControlMixedSeL4CAmKES_Temperature: return tc_TempControlMixedSeL4CAmKES_Temperature__equiv((tc_TempControlMixedSeL4CAmKES_Temperature) t1, (tc_TempControlMixedSeL4CAmKES_Temperature) t2);
    case Ttc_TempControlMixedSeL4CAmKES_Temperature_Payload: return tc_TempControlMixedSeL4CAmKES_Temperature_Payload__equiv((tc_TempControlMixedSeL4CAmKES_Temperature_Payload) t1, (tc_TempControlMixedSeL4CAmKES_Temperature_Payload) t2);
    case Ttc_TempControlPeriodic_FanAck_Payload: return tc_TempControlPeriodic_FanAck_Payload__equiv((tc_TempControlPeriodic_FanAck_Payload) t1, (tc_TempControlPeriodic_FanAck_Payload) t2);
    case Ttc_TempControlPeriodic_FanCmd_Payload: return tc_TempControlPeriodic_FanCmd_Payload__equiv((tc_TempControlPeriodic_FanCmd_Payload) t1, (tc_TempControlPeriodic_FanCmd_Payload) t2);
    case Ttc_TempControlPeriodic_SetPoint: return tc_TempControlPeriodic_SetPoint__equiv((tc_TempControlPeriodic_SetPoint) t1, (tc_TempControlPeriodic_SetPoint) t2);
    case Ttc_TempControlPeriodic_SetPoint_Payload: return tc_TempControlPeriodic_SetPoint_Payload__equiv((tc_TempControlPeriodic_SetPoint_Payload) t1, (tc_TempControlPeriodic_SetPoint_Payload) t2);
    case Ttc_TempControlPeriodic_TempUnit_Payload: return tc_TempControlPeriodic_TempUnit_Payload__equiv((tc_TempControlPeriodic_TempUnit_Payload) t1, (tc_TempControlPeriodic_TempUnit_Payload) t2);
    case Ttc_TempControlPeriodic_Temperature: return tc_TempControlPeriodic_Temperature__equiv((tc_TempControlPeriodic_Temperature) t1, (tc_TempControlPeriodic_Temperature) t2);
    case Ttc_TempControlPeriodic_Temperature_Payload: return tc_TempControlPeriodic_Temperature_Payload__equiv((tc_TempControlPeriodic_Temperature_Payload) t1, (tc_TempControlPeriodic_Temperature_Payload) t2);
    default: fprintf(stderr, "%s: %d\n", "Unexpected TYPE: ", type); exit(1);
  }
}

void Type_cprint(void *this, B isOut) {
  #ifndef SIREUM_NO_PRINT
  TYPE type = ((Type) this)->type;
  switch (type) {
    case TIS_948B60: IS_948B60_cprint((IS_948B60) this, isOut); return;
    case TNone_BE2C3F: None_BE2C3F_cprint((None_BE2C3F) this, isOut); return;
    case TNone_BE24EA: None_BE24EA_cprint((None_BE24EA) this, isOut); return;
    case TNone_3C78E7: None_3C78E7_cprint((None_3C78E7) this, isOut); return;
    case TNone_A45A41: None_A45A41_cprint((None_A45A41) this, isOut); return;
    case TNone_A23E58: None_A23E58_cprint((None_A23E58) this, isOut); return;
    case TNone_B4A4FA: None_B4A4FA_cprint((None_B4A4FA) this, isOut); return;
    case TNone_1AEC2C: None_1AEC2C_cprint((None_1AEC2C) this, isOut); return;
    case TNone_121724: None_121724_cprint((None_121724) this, isOut); return;
    case TNone_A70CEE: None_A70CEE_cprint((None_A70CEE) this, isOut); return;
    case TNone_ACDB63: None_ACDB63_cprint((None_ACDB63) this, isOut); return;
    case TNone_86BF24: None_86BF24_cprint((None_86BF24) this, isOut); return;
    case TNone_D4B208: None_D4B208_cprint((None_D4B208) this, isOut); return;
    case TNone_037804: None_037804_cprint((None_037804) this, isOut); return;
    case TNone_4E7E94: None_4E7E94_cprint((None_4E7E94) this, isOut); return;
    case TSome_455777: Some_455777_cprint((Some_455777) this, isOut); return;
    case TSome_F1808D: Some_F1808D_cprint((Some_F1808D) this, isOut); return;
    case TSome_C790DA: Some_C790DA_cprint((Some_C790DA) this, isOut); return;
    case TSome_140719: Some_140719_cprint((Some_140719) this, isOut); return;
    case TSome_21C1E5: Some_21C1E5_cprint((Some_21C1E5) this, isOut); return;
    case TSome_270A8B: Some_270A8B_cprint((Some_270A8B) this, isOut); return;
    case TSome_776961: Some_776961_cprint((Some_776961) this, isOut); return;
    case TSome_0E3FBA: Some_0E3FBA_cprint((Some_0E3FBA) this, isOut); return;
    case TSome_D85467: Some_D85467_cprint((Some_D85467) this, isOut); return;
    case TSome_2EFA7D: Some_2EFA7D_cprint((Some_2EFA7D) this, isOut); return;
    case TSome_0C4CF8: Some_0C4CF8_cprint((Some_0C4CF8) this, isOut); return;
    case TSome_C3173C: Some_C3173C_cprint((Some_C3173C) this, isOut); return;
    case TSome_C0DBA9: Some_C0DBA9_cprint((Some_C0DBA9) this, isOut); return;
    case TSome_56FCC9: Some_56FCC9_cprint((Some_56FCC9) this, isOut); return;
    case TString: String_cprint((String) this, isOut); return;
    case Tart_Empty: art_Empty_cprint((art_Empty) this, isOut); return;
    case Ttc_Base_Types_Boolean_Payload: tc_Base_Types_Boolean_Payload_cprint((tc_Base_Types_Boolean_Payload) this, isOut); return;
    case Ttc_Base_Types_Character_Payload: tc_Base_Types_Character_Payload_cprint((tc_Base_Types_Character_Payload) this, isOut); return;
    case Ttc_Base_Types_Float_32_Payload: tc_Base_Types_Float_32_Payload_cprint((tc_Base_Types_Float_32_Payload) this, isOut); return;
    case Ttc_Base_Types_Float_64_Payload: tc_Base_Types_Float_64_Payload_cprint((tc_Base_Types_Float_64_Payload) this, isOut); return;
    case Ttc_Base_Types_Float_Payload: tc_Base_Types_Float_Payload_cprint((tc_Base_Types_Float_Payload) this, isOut); return;
    case Ttc_Base_Types_Integer_16_Payload: tc_Base_Types_Integer_16_Payload_cprint((tc_Base_Types_Integer_16_Payload) this, isOut); return;
    case Ttc_Base_Types_Integer_32_Payload: tc_Base_Types_Integer_32_Payload_cprint((tc_Base_Types_Integer_32_Payload) this, isOut); return;
    case Ttc_Base_Types_Integer_64_Payload: tc_Base_Types_Integer_64_Payload_cprint((tc_Base_Types_Integer_64_Payload) this, isOut); return;
    case Ttc_Base_Types_Integer_8_Payload: tc_Base_Types_Integer_8_Payload_cprint((tc_Base_Types_Integer_8_Payload) this, isOut); return;
    case Ttc_Base_Types_Integer_Payload: tc_Base_Types_Integer_Payload_cprint((tc_Base_Types_Integer_Payload) this, isOut); return;
    case Ttc_Base_Types_String_Payload: tc_Base_Types_String_Payload_cprint((tc_Base_Types_String_Payload) this, isOut); return;
    case Ttc_Base_Types_Unsigned_16_Payload: tc_Base_Types_Unsigned_16_Payload_cprint((tc_Base_Types_Unsigned_16_Payload) this, isOut); return;
    case Ttc_Base_Types_Unsigned_32_Payload: tc_Base_Types_Unsigned_32_Payload_cprint((tc_Base_Types_Unsigned_32_Payload) this, isOut); return;
    case Ttc_Base_Types_Unsigned_64_Payload: tc_Base_Types_Unsigned_64_Payload_cprint((tc_Base_Types_Unsigned_64_Payload) this, isOut); return;
    case Ttc_Base_Types_Unsigned_8_Payload: tc_Base_Types_Unsigned_8_Payload_cprint((tc_Base_Types_Unsigned_8_Payload) this, isOut); return;
    case Ttc_Isolette_Data_Model_Failure_Flag: tc_Isolette_Data_Model_Failure_Flag_cprint((tc_Isolette_Data_Model_Failure_Flag) this, isOut); return;
    case Ttc_Isolette_Data_Model_Failure_Flag_Payload: tc_Isolette_Data_Model_Failure_Flag_Payload_cprint((tc_Isolette_Data_Model_Failure_Flag_Payload) this, isOut); return;
    case Ttc_Isolette_Data_Model_Monitor_Mode_Payload: tc_Isolette_Data_Model_Monitor_Mode_Payload_cprint((tc_Isolette_Data_Model_Monitor_Mode_Payload) this, isOut); return;
    case Ttc_Isolette_Data_Model_On_Off_Payload: tc_Isolette_Data_Model_On_Off_Payload_cprint((tc_Isolette_Data_Model_On_Off_Payload) this, isOut); return;
    case Ttc_Isolette_Data_Model_PhysicalTemp: tc_Isolette_Data_Model_PhysicalTemp_cprint((tc_Isolette_Data_Model_PhysicalTemp) this, isOut); return;
    case Ttc_Isolette_Data_Model_PhysicalTemp_Payload: tc_Isolette_Data_Model_PhysicalTemp_Payload_cprint((tc_Isolette_Data_Model_PhysicalTemp_Payload) this, isOut); return;
    case Ttc_Isolette_Data_Model_Regulator_Mode_Payload: tc_Isolette_Data_Model_Regulator_Mode_Payload_cprint((tc_Isolette_Data_Model_Regulator_Mode_Payload) this, isOut); return;
    case Ttc_Isolette_Data_Model_Status_Payload: tc_Isolette_Data_Model_Status_Payload_cprint((tc_Isolette_Data_Model_Status_Payload) this, isOut); return;
    case Ttc_Isolette_Data_Model_Temp: tc_Isolette_Data_Model_Temp_cprint((tc_Isolette_Data_Model_Temp) this, isOut); return;
    case Ttc_Isolette_Data_Model_TempWstatus: tc_Isolette_Data_Model_TempWstatus_cprint((tc_Isolette_Data_Model_TempWstatus) this, isOut); return;
    case Ttc_Isolette_Data_Model_TempWstatus_Payload: tc_Isolette_Data_Model_TempWstatus_Payload_cprint((tc_Isolette_Data_Model_TempWstatus_Payload) this, isOut); return;
    case Ttc_Isolette_Data_Model_Temp_Payload: tc_Isolette_Data_Model_Temp_Payload_cprint((tc_Isolette_Data_Model_Temp_Payload) this, isOut); return;
    case Ttc_Isolette_Data_Model_ValueStatus_Payload: tc_Isolette_Data_Model_ValueStatus_Payload_cprint((tc_Isolette_Data_Model_ValueStatus_Payload) this, isOut); return;
    case Ttc_Isolette_Environment_Air_Interaction: tc_Isolette_Environment_Air_Interaction_cprint((tc_Isolette_Environment_Air_Interaction) this, isOut); return;
    case Ttc_Isolette_Environment_Air_Interaction_Payload: tc_Isolette_Environment_Air_Interaction_Payload_cprint((tc_Isolette_Environment_Air_Interaction_Payload) this, isOut); return;
    case Ttc_Isolette_Environment_Heat: tc_Isolette_Environment_Heat_cprint((tc_Isolette_Environment_Heat) this, isOut); return;
    case Ttc_Isolette_Environment_Heat_Payload: tc_Isolette_Environment_Heat_Payload_cprint((tc_Isolette_Environment_Heat_Payload) this, isOut); return;
    case Ttc_Isolette_Environment_Interface_Interaction: tc_Isolette_Environment_Interface_Interaction_cprint((tc_Isolette_Environment_Interface_Interaction) this, isOut); return;
    case Ttc_Isolette_Environment_Interface_Interaction_Payload: tc_Isolette_Environment_Interface_Interaction_Payload_cprint((tc_Isolette_Environment_Interface_Interaction_Payload) this, isOut); return;
    case Ttc_TempControlMixed_FanAck_Payload: tc_TempControlMixed_FanAck_Payload_cprint((tc_TempControlMixed_FanAck_Payload) this, isOut); return;
    case Ttc_TempControlMixed_FanCmd_Payload: tc_TempControlMixed_FanCmd_Payload_cprint((tc_TempControlMixed_FanCmd_Payload) this, isOut); return;
    case Ttc_TempControlMixed_SetPoint: tc_TempControlMixed_SetPoint_cprint((tc_TempControlMixed_SetPoint) this, isOut); return;
    case Ttc_TempControlMixed_SetPoint_Payload: tc_TempControlMixed_SetPoint_Payload_cprint((tc_TempControlMixed_SetPoint_Payload) this, isOut); return;
    case Ttc_TempControlMixed_TempUnit_Payload: tc_TempControlMixed_TempUnit_Payload_cprint((tc_TempControlMixed_TempUnit_Payload) this, isOut); return;
    case Ttc_TempControlMixed_Temperature: tc_TempControlMixed_Temperature_cprint((tc_TempControlMixed_Temperature) this, isOut); return;
    case Ttc_TempControlMixed_Temperature_Payload: tc_TempControlMixed_Temperature_Payload_cprint((tc_TempControlMixed_Temperature_Payload) this, isOut); return;
    case Ttc_TempControlMixedSeL4CAmKES_FanAck_Payload: tc_TempControlMixedSeL4CAmKES_FanAck_Payload_cprint((tc_TempControlMixedSeL4CAmKES_FanAck_Payload) this, isOut); return;
    case Ttc_TempControlMixedSeL4CAmKES_FanCmd_Payload: tc_TempControlMixedSeL4CAmKES_FanCmd_Payload_cprint((tc_TempControlMixedSeL4CAmKES_FanCmd_Payload) this, isOut); return;
    case Ttc_TempControlMixedSeL4CAmKES_SetPoint: tc_TempControlMixedSeL4CAmKES_SetPoint_cprint((tc_TempControlMixedSeL4CAmKES_SetPoint) this, isOut); return;
    case Ttc_TempControlMixedSeL4CAmKES_SetPoint_Payload: tc_TempControlMixedSeL4CAmKES_SetPoint_Payload_cprint((tc_TempControlMixedSeL4CAmKES_SetPoint_Payload) this, isOut); return;
    case Ttc_TempControlMixedSeL4CAmKES_TempUnit_Payload: tc_TempControlMixedSeL4CAmKES_TempUnit_Payload_cprint((tc_TempControlMixedSeL4CAmKES_TempUnit_Payload) this, isOut); return;
    case Ttc_TempControlMixedSeL4CAmKES_Temperature: tc_TempControlMixedSeL4CAmKES_Temperature_cprint((tc_TempControlMixedSeL4CAmKES_Temperature) this, isOut); return;
    case Ttc_TempControlMixedSeL4CAmKES_Temperature_Payload: tc_TempControlMixedSeL4CAmKES_Temperature_Payload_cprint((tc_TempControlMixedSeL4CAmKES_Temperature_Payload) this, isOut); return;
    case Ttc_TempControlPeriodic_FanAck_Payload: tc_TempControlPeriodic_FanAck_Payload_cprint((tc_TempControlPeriodic_FanAck_Payload) this, isOut); return;
    case Ttc_TempControlPeriodic_FanCmd_Payload: tc_TempControlPeriodic_FanCmd_Payload_cprint((tc_TempControlPeriodic_FanCmd_Payload) this, isOut); return;
    case Ttc_TempControlPeriodic_SetPoint: tc_TempControlPeriodic_SetPoint_cprint((tc_TempControlPeriodic_SetPoint) this, isOut); return;
    case Ttc_TempControlPeriodic_SetPoint_Payload: tc_TempControlPeriodic_SetPoint_Payload_cprint((tc_TempControlPeriodic_SetPoint_Payload) this, isOut); return;
    case Ttc_TempControlPeriodic_TempUnit_Payload: tc_TempControlPeriodic_TempUnit_Payload_cprint((tc_TempControlPeriodic_TempUnit_Payload) this, isOut); return;
    case Ttc_TempControlPeriodic_Temperature: tc_TempControlPeriodic_Temperature_cprint((tc_TempControlPeriodic_Temperature) this, isOut); return;
    case Ttc_TempControlPeriodic_Temperature_Payload: tc_TempControlPeriodic_Temperature_Payload_cprint((tc_TempControlPeriodic_Temperature_Payload) this, isOut); return;
    default: fprintf(stderr, "%s: %d\n", "Unexpected TYPE: ", type); exit(1);
  }
  #endif
}

void Type_string_(STACK_FRAME String result, void *this) {
  TYPE type = ((Type) this)->type;
  switch (type) {
    case TIS_948B60: IS_948B60_string_(CALLER result, (IS_948B60) this); return;
    case TNone_BE2C3F: None_BE2C3F_string_(CALLER result, (None_BE2C3F) this); return;
    case TNone_BE24EA: None_BE24EA_string_(CALLER result, (None_BE24EA) this); return;
    case TNone_3C78E7: None_3C78E7_string_(CALLER result, (None_3C78E7) this); return;
    case TNone_A45A41: None_A45A41_string_(CALLER result, (None_A45A41) this); return;
    case TNone_A23E58: None_A23E58_string_(CALLER result, (None_A23E58) this); return;
    case TNone_B4A4FA: None_B4A4FA_string_(CALLER result, (None_B4A4FA) this); return;
    case TNone_1AEC2C: None_1AEC2C_string_(CALLER result, (None_1AEC2C) this); return;
    case TNone_121724: None_121724_string_(CALLER result, (None_121724) this); return;
    case TNone_A70CEE: None_A70CEE_string_(CALLER result, (None_A70CEE) this); return;
    case TNone_ACDB63: None_ACDB63_string_(CALLER result, (None_ACDB63) this); return;
    case TNone_86BF24: None_86BF24_string_(CALLER result, (None_86BF24) this); return;
    case TNone_D4B208: None_D4B208_string_(CALLER result, (None_D4B208) this); return;
    case TNone_037804: None_037804_string_(CALLER result, (None_037804) this); return;
    case TNone_4E7E94: None_4E7E94_string_(CALLER result, (None_4E7E94) this); return;
    case TSome_455777: Some_455777_string_(CALLER result, (Some_455777) this); return;
    case TSome_F1808D: Some_F1808D_string_(CALLER result, (Some_F1808D) this); return;
    case TSome_C790DA: Some_C790DA_string_(CALLER result, (Some_C790DA) this); return;
    case TSome_140719: Some_140719_string_(CALLER result, (Some_140719) this); return;
    case TSome_21C1E5: Some_21C1E5_string_(CALLER result, (Some_21C1E5) this); return;
    case TSome_270A8B: Some_270A8B_string_(CALLER result, (Some_270A8B) this); return;
    case TSome_776961: Some_776961_string_(CALLER result, (Some_776961) this); return;
    case TSome_0E3FBA: Some_0E3FBA_string_(CALLER result, (Some_0E3FBA) this); return;
    case TSome_D85467: Some_D85467_string_(CALLER result, (Some_D85467) this); return;
    case TSome_2EFA7D: Some_2EFA7D_string_(CALLER result, (Some_2EFA7D) this); return;
    case TSome_0C4CF8: Some_0C4CF8_string_(CALLER result, (Some_0C4CF8) this); return;
    case TSome_C3173C: Some_C3173C_string_(CALLER result, (Some_C3173C) this); return;
    case TSome_C0DBA9: Some_C0DBA9_string_(CALLER result, (Some_C0DBA9) this); return;
    case TSome_56FCC9: Some_56FCC9_string_(CALLER result, (Some_56FCC9) this); return;
    case TString: String_string_(CALLER result, (String) this); return;
    case Tart_Empty: art_Empty_string_(CALLER result, (art_Empty) this); return;
    case Ttc_Base_Types_Boolean_Payload: tc_Base_Types_Boolean_Payload_string_(CALLER result, (tc_Base_Types_Boolean_Payload) this); return;
    case Ttc_Base_Types_Character_Payload: tc_Base_Types_Character_Payload_string_(CALLER result, (tc_Base_Types_Character_Payload) this); return;
    case Ttc_Base_Types_Float_32_Payload: tc_Base_Types_Float_32_Payload_string_(CALLER result, (tc_Base_Types_Float_32_Payload) this); return;
    case Ttc_Base_Types_Float_64_Payload: tc_Base_Types_Float_64_Payload_string_(CALLER result, (tc_Base_Types_Float_64_Payload) this); return;
    case Ttc_Base_Types_Float_Payload: tc_Base_Types_Float_Payload_string_(CALLER result, (tc_Base_Types_Float_Payload) this); return;
    case Ttc_Base_Types_Integer_16_Payload: tc_Base_Types_Integer_16_Payload_string_(CALLER result, (tc_Base_Types_Integer_16_Payload) this); return;
    case Ttc_Base_Types_Integer_32_Payload: tc_Base_Types_Integer_32_Payload_string_(CALLER result, (tc_Base_Types_Integer_32_Payload) this); return;
    case Ttc_Base_Types_Integer_64_Payload: tc_Base_Types_Integer_64_Payload_string_(CALLER result, (tc_Base_Types_Integer_64_Payload) this); return;
    case Ttc_Base_Types_Integer_8_Payload: tc_Base_Types_Integer_8_Payload_string_(CALLER result, (tc_Base_Types_Integer_8_Payload) this); return;
    case Ttc_Base_Types_Integer_Payload: tc_Base_Types_Integer_Payload_string_(CALLER result, (tc_Base_Types_Integer_Payload) this); return;
    case Ttc_Base_Types_String_Payload: tc_Base_Types_String_Payload_string_(CALLER result, (tc_Base_Types_String_Payload) this); return;
    case Ttc_Base_Types_Unsigned_16_Payload: tc_Base_Types_Unsigned_16_Payload_string_(CALLER result, (tc_Base_Types_Unsigned_16_Payload) this); return;
    case Ttc_Base_Types_Unsigned_32_Payload: tc_Base_Types_Unsigned_32_Payload_string_(CALLER result, (tc_Base_Types_Unsigned_32_Payload) this); return;
    case Ttc_Base_Types_Unsigned_64_Payload: tc_Base_Types_Unsigned_64_Payload_string_(CALLER result, (tc_Base_Types_Unsigned_64_Payload) this); return;
    case Ttc_Base_Types_Unsigned_8_Payload: tc_Base_Types_Unsigned_8_Payload_string_(CALLER result, (tc_Base_Types_Unsigned_8_Payload) this); return;
    case Ttc_Isolette_Data_Model_Failure_Flag: tc_Isolette_Data_Model_Failure_Flag_string_(CALLER result, (tc_Isolette_Data_Model_Failure_Flag) this); return;
    case Ttc_Isolette_Data_Model_Failure_Flag_Payload: tc_Isolette_Data_Model_Failure_Flag_Payload_string_(CALLER result, (tc_Isolette_Data_Model_Failure_Flag_Payload) this); return;
    case Ttc_Isolette_Data_Model_Monitor_Mode_Payload: tc_Isolette_Data_Model_Monitor_Mode_Payload_string_(CALLER result, (tc_Isolette_Data_Model_Monitor_Mode_Payload) this); return;
    case Ttc_Isolette_Data_Model_On_Off_Payload: tc_Isolette_Data_Model_On_Off_Payload_string_(CALLER result, (tc_Isolette_Data_Model_On_Off_Payload) this); return;
    case Ttc_Isolette_Data_Model_PhysicalTemp: tc_Isolette_Data_Model_PhysicalTemp_string_(CALLER result, (tc_Isolette_Data_Model_PhysicalTemp) this); return;
    case Ttc_Isolette_Data_Model_PhysicalTemp_Payload: tc_Isolette_Data_Model_PhysicalTemp_Payload_string_(CALLER result, (tc_Isolette_Data_Model_PhysicalTemp_Payload) this); return;
    case Ttc_Isolette_Data_Model_Regulator_Mode_Payload: tc_Isolette_Data_Model_Regulator_Mode_Payload_string_(CALLER result, (tc_Isolette_Data_Model_Regulator_Mode_Payload) this); return;
    case Ttc_Isolette_Data_Model_Status_Payload: tc_Isolette_Data_Model_Status_Payload_string_(CALLER result, (tc_Isolette_Data_Model_Status_Payload) this); return;
    case Ttc_Isolette_Data_Model_Temp: tc_Isolette_Data_Model_Temp_string_(CALLER result, (tc_Isolette_Data_Model_Temp) this); return;
    case Ttc_Isolette_Data_Model_TempWstatus: tc_Isolette_Data_Model_TempWstatus_string_(CALLER result, (tc_Isolette_Data_Model_TempWstatus) this); return;
    case Ttc_Isolette_Data_Model_TempWstatus_Payload: tc_Isolette_Data_Model_TempWstatus_Payload_string_(CALLER result, (tc_Isolette_Data_Model_TempWstatus_Payload) this); return;
    case Ttc_Isolette_Data_Model_Temp_Payload: tc_Isolette_Data_Model_Temp_Payload_string_(CALLER result, (tc_Isolette_Data_Model_Temp_Payload) this); return;
    case Ttc_Isolette_Data_Model_ValueStatus_Payload: tc_Isolette_Data_Model_ValueStatus_Payload_string_(CALLER result, (tc_Isolette_Data_Model_ValueStatus_Payload) this); return;
    case Ttc_Isolette_Environment_Air_Interaction: tc_Isolette_Environment_Air_Interaction_string_(CALLER result, (tc_Isolette_Environment_Air_Interaction) this); return;
    case Ttc_Isolette_Environment_Air_Interaction_Payload: tc_Isolette_Environment_Air_Interaction_Payload_string_(CALLER result, (tc_Isolette_Environment_Air_Interaction_Payload) this); return;
    case Ttc_Isolette_Environment_Heat: tc_Isolette_Environment_Heat_string_(CALLER result, (tc_Isolette_Environment_Heat) this); return;
    case Ttc_Isolette_Environment_Heat_Payload: tc_Isolette_Environment_Heat_Payload_string_(CALLER result, (tc_Isolette_Environment_Heat_Payload) this); return;
    case Ttc_Isolette_Environment_Interface_Interaction: tc_Isolette_Environment_Interface_Interaction_string_(CALLER result, (tc_Isolette_Environment_Interface_Interaction) this); return;
    case Ttc_Isolette_Environment_Interface_Interaction_Payload: tc_Isolette_Environment_Interface_Interaction_Payload_string_(CALLER result, (tc_Isolette_Environment_Interface_Interaction_Payload) this); return;
    case Ttc_TempControlMixed_FanAck_Payload: tc_TempControlMixed_FanAck_Payload_string_(CALLER result, (tc_TempControlMixed_FanAck_Payload) this); return;
    case Ttc_TempControlMixed_FanCmd_Payload: tc_TempControlMixed_FanCmd_Payload_string_(CALLER result, (tc_TempControlMixed_FanCmd_Payload) this); return;
    case Ttc_TempControlMixed_SetPoint: tc_TempControlMixed_SetPoint_string_(CALLER result, (tc_TempControlMixed_SetPoint) this); return;
    case Ttc_TempControlMixed_SetPoint_Payload: tc_TempControlMixed_SetPoint_Payload_string_(CALLER result, (tc_TempControlMixed_SetPoint_Payload) this); return;
    case Ttc_TempControlMixed_TempUnit_Payload: tc_TempControlMixed_TempUnit_Payload_string_(CALLER result, (tc_TempControlMixed_TempUnit_Payload) this); return;
    case Ttc_TempControlMixed_Temperature: tc_TempControlMixed_Temperature_string_(CALLER result, (tc_TempControlMixed_Temperature) this); return;
    case Ttc_TempControlMixed_Temperature_Payload: tc_TempControlMixed_Temperature_Payload_string_(CALLER result, (tc_TempControlMixed_Temperature_Payload) this); return;
    case Ttc_TempControlMixedSeL4CAmKES_FanAck_Payload: tc_TempControlMixedSeL4CAmKES_FanAck_Payload_string_(CALLER result, (tc_TempControlMixedSeL4CAmKES_FanAck_Payload) this); return;
    case Ttc_TempControlMixedSeL4CAmKES_FanCmd_Payload: tc_TempControlMixedSeL4CAmKES_FanCmd_Payload_string_(CALLER result, (tc_TempControlMixedSeL4CAmKES_FanCmd_Payload) this); return;
    case Ttc_TempControlMixedSeL4CAmKES_SetPoint: tc_TempControlMixedSeL4CAmKES_SetPoint_string_(CALLER result, (tc_TempControlMixedSeL4CAmKES_SetPoint) this); return;
    case Ttc_TempControlMixedSeL4CAmKES_SetPoint_Payload: tc_TempControlMixedSeL4CAmKES_SetPoint_Payload_string_(CALLER result, (tc_TempControlMixedSeL4CAmKES_SetPoint_Payload) this); return;
    case Ttc_TempControlMixedSeL4CAmKES_TempUnit_Payload: tc_TempControlMixedSeL4CAmKES_TempUnit_Payload_string_(CALLER result, (tc_TempControlMixedSeL4CAmKES_TempUnit_Payload) this); return;
    case Ttc_TempControlMixedSeL4CAmKES_Temperature: tc_TempControlMixedSeL4CAmKES_Temperature_string_(CALLER result, (tc_TempControlMixedSeL4CAmKES_Temperature) this); return;
    case Ttc_TempControlMixedSeL4CAmKES_Temperature_Payload: tc_TempControlMixedSeL4CAmKES_Temperature_Payload_string_(CALLER result, (tc_TempControlMixedSeL4CAmKES_Temperature_Payload) this); return;
    case Ttc_TempControlPeriodic_FanAck_Payload: tc_TempControlPeriodic_FanAck_Payload_string_(CALLER result, (tc_TempControlPeriodic_FanAck_Payload) this); return;
    case Ttc_TempControlPeriodic_FanCmd_Payload: tc_TempControlPeriodic_FanCmd_Payload_string_(CALLER result, (tc_TempControlPeriodic_FanCmd_Payload) this); return;
    case Ttc_TempControlPeriodic_SetPoint: tc_TempControlPeriodic_SetPoint_string_(CALLER result, (tc_TempControlPeriodic_SetPoint) this); return;
    case Ttc_TempControlPeriodic_SetPoint_Payload: tc_TempControlPeriodic_SetPoint_Payload_string_(CALLER result, (tc_TempControlPeriodic_SetPoint_Payload) this); return;
    case Ttc_TempControlPeriodic_TempUnit_Payload: tc_TempControlPeriodic_TempUnit_Payload_string_(CALLER result, (tc_TempControlPeriodic_TempUnit_Payload) this); return;
    case Ttc_TempControlPeriodic_Temperature: tc_TempControlPeriodic_Temperature_string_(CALLER result, (tc_TempControlPeriodic_Temperature) this); return;
    case Ttc_TempControlPeriodic_Temperature_Payload: tc_TempControlPeriodic_Temperature_Payload_string_(CALLER result, (tc_TempControlPeriodic_Temperature_Payload) this); return;
    default: fprintf(stderr, "%s: %d\n", "Unexpected TYPE: ", type); exit(1);
  }
}

