// #Sireum

package slang_rm.TempControlPeriodic

import org.sireum._
import slang_rm._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

object SetPoint {
  def example(): TempControlPeriodic.SetPoint = {
    return TempControlPeriodic.SetPoint(
      low = TempControlPeriodic.Temperature.example(),
      high = TempControlPeriodic.Temperature.example())
  }

  /** invariant SetPoint_Data_Invariant
    */
  @strictpure def SetPoint_Data_Invariant_Invariant(value: TempControlPeriodic.SetPoint): B =
    value.low.degrees >= 50.0f &
      (value.high.degrees <= 110.0f &
        value.low.degrees <= value.high.degrees)

  /** D-Inv Data Invariant for TempControlPeriodic.SetPoint
    */
  @strictpure def D_Inv_SetPoint(value: TempControlPeriodic.SetPoint): B =
    (SetPoint_Data_Invariant_Invariant(value))

  /** D-Inv-Guard Data Invariant for TempControlPeriodic.SetPoint
    */
  @strictpure def D_Inv_Guard_SetPoint(value: Option[TempControlPeriodic.SetPoint]): B =
    value.nonEmpty -->: D_Inv_SetPoint(value.get)
}

@datatype class SetPoint(
  val low: TempControlPeriodic.Temperature,
  val high: TempControlPeriodic.Temperature) {
  @spec def SetPoint_Data_Invariant = Invariant(
    low.degrees >= 50.0f &
      (high.degrees <= 110.0f &
        low.degrees <= high.degrees)
  )
}

object SetPoint_Payload {
  def example(): SetPoint_Payload = {
    return SetPoint_Payload(TempControlPeriodic.SetPoint.example())
  }
}

@datatype class SetPoint_Payload(value: TempControlPeriodic.SetPoint) extends art.DataContent
