// #Sireum

package tc.TempControlMixedSeL4CAmKES

import org.sireum._
import art._
import tc._
import tc.TempControlMixedSeL4CAmKES.{TempControl_tcp_tct => component}

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

@datatype class TempControl_tcp_tct_Bridge(
  val id: Art.BridgeId,
  val name: String,
  val dispatchProtocol: DispatchPropertyProtocol,
  val dispatchTriggers: Option[ISZ[Art.PortId]],

  currentTemp: Port[TempControlMixedSeL4CAmKES.Temperature],
  tempChanged: Port[art.Empty],
  fanAck: Port[TempControlMixedSeL4CAmKES.FanAck.Type],
  setPoint: Port[TempControlMixedSeL4CAmKES.SetPoint],
  fanCmd: Port[TempControlMixedSeL4CAmKES.FanCmd.Type]
  ) extends Bridge {

  val ports : Bridge.Ports = Bridge.Ports(
    dataIns = ISZ[art.UPort](currentTemp),

    dataOuts = ISZ[art.UPort](),

    eventIns = ISZ[art.UPort](tempChanged,
                              fanAck,
                              setPoint),

    eventOuts = ISZ[art.UPort](fanCmd)
  )

  val initialization_api : TempControl_Initialization_Api = {
    val api = TempControl_Initialization_Api(
      id,
      currentTemp.id,
      tempChanged.id,
      fanAck.id,
      setPoint.id,
      fanCmd.id
    )
    TempControl_tcp_tct_Bridge.c_initialization_api = Some(api)
    api
  }

  val operational_api : TempControl_Operational_Api = {
    val api = TempControl_Operational_Api(
      id,
      currentTemp.id,
      tempChanged.id,
      fanAck.id,
      setPoint.id,
      fanCmd.id
    )
    TempControl_tcp_tct_Bridge.c_operational_api = Some(api)
    api
  }

  val entryPoints : Bridge.EntryPoints =
    TempControl_tcp_tct_Bridge.EntryPoints(
      id,

      currentTemp.id,
      tempChanged.id,
      fanAck.id,
      setPoint.id,
      fanCmd.id,

      dispatchTriggers,

      initialization_api,
      operational_api)
}

object TempControl_tcp_tct_Bridge {

  var c_initialization_api: Option[TempControl_Initialization_Api] = None()
  var c_operational_api: Option[TempControl_Operational_Api] = None()

  @datatype class EntryPoints(
    TempControl_tcp_tct_BridgeId : Art.BridgeId,
    currentTemp_Id : Art.PortId,
    tempChanged_Id : Art.PortId,
    fanAck_Id : Art.PortId,
    setPoint_Id : Art.PortId,
    fanCmd_Id : Art.PortId,
    dispatchTriggers : Option[ISZ[Art.PortId]],
    initialization_api: TempControl_Initialization_Api,
    operational_api: TempControl_Operational_Api) extends Bridge.EntryPoints {

    val dataInPortIds: ISZ[Art.PortId] = IS(currentTemp_Id)

    val eventInPortIds: ISZ[Art.PortId] = IS(tempChanged_Id,
                                             fanAck_Id,
                                             setPoint_Id)

    val dataOutPortIds: ISZ[Art.PortId] = IS()

    val eventOutPortIds: ISZ[Art.PortId] = IS(fanCmd_Id)

    def initialise(): Unit = {
      TempControl_tcp_tct_EntryPoint_Companion.pre_initialise()

      // implement the following method in 'component':  def initialise(api: TempControl_Initialization_Api): Unit = {}
      component.initialise(initialization_api)

      TempControl_tcp_tct_EntryPoint_Companion.post_initialise()

      Art.sendOutput(eventOutPortIds, dataOutPortIds)
    }

    def compute(): Unit = {
      // transpiler friendly filter
      def filter(receivedEvents: ISZ[Art.PortId], triggers: ISZ[Art.PortId]): ISZ[Art.PortId] = {
        var r = ISZ[Art.PortId]()
        val opsTriggers = ops.ISZOps(triggers)
        for(e <- receivedEvents) {
          if(opsTriggers.contains(e)) {
            r = r :+ e
          }
        }
        return r
      }

      // fetch received events ordered by highest urgency then earliest arrival-time
      val EventTriggered(receivedEvents) = Art.dispatchStatus(TempControl_tcp_tct_BridgeId)

      // remove non-dispatching event ports
      val dispatchableEventPorts: ISZ[Art.PortId] =
        if(dispatchTriggers.isEmpty) receivedEvents
        else filter(receivedEvents, dispatchTriggers.get)

      TempControl_tcp_tct_Injection_Service.pre_receiveInput()

      Art.receiveInput(eventInPortIds, dataInPortIds)

      for(portId <- dispatchableEventPorts) {
        if(portId == tempChanged_Id) {
          TempControl_tcp_tct_EntryPoint_Companion.pre_compute(tempChanged_Id)

          // implement the following in 'component':  def handle_tempChanged(api: TempControl_Operational_Api): Unit = {}
          component.handle_tempChanged(operational_api)

          TempControl_tcp_tct_EntryPoint_Companion.post_compute()
        }
        else if(portId == fanAck_Id){
          val Some(TempControlMixedSeL4CAmKES.FanAck_Payload(value)) = Art.getValue(fanAck_Id)

          TempControl_tcp_tct_EntryPoint_Companion.pre_compute(fanAck_Id)

          // implement the following in 'component':  def handle_fanAck(api: TempControl_Operational_Api, value: TempControlMixedSeL4CAmKES.FanAck.Type): Unit = {}
          component.handle_fanAck(operational_api, value)

          TempControl_tcp_tct_EntryPoint_Companion.post_compute()
        }
        else if(portId == setPoint_Id){
          val Some(TempControlMixedSeL4CAmKES.SetPoint_Payload(value)) = Art.getValue(setPoint_Id)

          TempControl_tcp_tct_EntryPoint_Companion.pre_compute(setPoint_Id)

          // implement the following in 'component':  def handle_setPoint(api: TempControl_Operational_Api, value: TempControlMixedSeL4CAmKES.SetPoint): Unit = {}
          component.handle_setPoint(operational_api, value)

          TempControl_tcp_tct_EntryPoint_Companion.post_compute()
        }
      }

      Art.sendOutput(eventOutPortIds, dataOutPortIds)
    }

    def finalise(): Unit = {
      // implement the following method in 'component':  def finalise(api: TempControl_Operational_Api): Unit = {}
      component.finalise(operational_api)
    }

    override
    def testInitialise(): Unit = {
      // implement the following method in 'component':  def initialise(api: TempControl_Initialization_Api): Unit = {}
      component.initialise(initialization_api)
      Art.releaseOutput(eventOutPortIds, dataOutPortIds)
    }

    override
    def testCompute(): Unit = {
      // transpiler friendly filter
      def filter(receivedEvents: ISZ[Art.PortId], triggers: ISZ[Art.PortId]): ISZ[Art.PortId] = {
        var r = ISZ[Art.PortId]()
        val opsTriggers = ops.ISZOps(triggers)
        for(e <- receivedEvents) {
          if(opsTriggers.contains(e)) {
            r = r :+ e
          }
        }
        return r
      }

      // fetch received events ordered by highest urgency then earliest arrival-time
      val EventTriggered(receivedEvents) = Art.dispatchStatus(TempControl_tcp_tct_BridgeId)

      // remove non-dispatching event ports
      val dispatchableEventPorts: ISZ[Art.PortId] =
        if(dispatchTriggers.isEmpty) receivedEvents
        else filter(receivedEvents, dispatchTriggers.get)

      Art.receiveInput(eventInPortIds, dataInPortIds)

      for(portId <- dispatchableEventPorts) {
        if(portId == tempChanged_Id) {
          // implement the following in 'component':  def handle_tempChanged(api: TempControl_Operational_Api): Unit = {}
          component.handle_tempChanged(operational_api)
        }
        else if(portId == fanAck_Id){
          val Some(TempControlMixedSeL4CAmKES.FanAck_Payload(value)) = Art.getValue(fanAck_Id)

          // implement the following in 'component':  def handle_fanAck(api: TempControl_Operational_Api, value: TempControlMixedSeL4CAmKES.FanAck.Type): Unit = {}
          component.handle_fanAck(operational_api, value)
        }
        else if(portId == setPoint_Id){
          val Some(TempControlMixedSeL4CAmKES.SetPoint_Payload(value)) = Art.getValue(setPoint_Id)

          // implement the following in 'component':  def handle_setPoint(api: TempControl_Operational_Api, value: TempControlMixedSeL4CAmKES.SetPoint): Unit = {}
          component.handle_setPoint(operational_api, value)
        }
      }

      Art.releaseOutput(eventOutPortIds, dataOutPortIds)
    }
  }
}