// #Sireum

package slang.Isolette_Environment

import org.sireum._
import slang._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

object Air_Interaction {
  def example(): Isolette_Environment.Air_Interaction = {
    return Isolette_Environment.Air_Interaction(
      dummyField = Base_Types.Boolean_example())
  }
}

@datatype class Air_Interaction(
  val dummyField: B) {
}

object Air_Interaction_Payload {
  def example(): Air_Interaction_Payload = {
    return Air_Interaction_Payload(Isolette_Environment.Air_Interaction.example())
  }
}

@datatype class Air_Interaction_Payload(value: Isolette_Environment.Air_Interaction) extends art.DataContent
