// #Sireum

package slang.Isolette_Environment

import org.sireum._
import slang._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

object Interface_Interaction {
  def example(): Isolette_Environment.Interface_Interaction = {
    return Isolette_Environment.Interface_Interaction(
      dummyField = Base_Types.Boolean_example())
  }
}

@datatype class Interface_Interaction(
  val dummyField: B) {
}

object Interface_Interaction_Payload {
  def example(): Interface_Interaction_Payload = {
    return Interface_Interaction_Payload(Isolette_Environment.Interface_Interaction.example())
  }
}

@datatype class Interface_Interaction_Payload(value: Isolette_Environment.Interface_Interaction) extends art.DataContent
