// #Sireum

package slang_rm.TempControlMixed

import org.sireum._
import slang_rm._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

object Temperature {
  def example(): TempControlMixed.Temperature = {
    return TempControlMixed.Temperature(
      degrees = Base_Types.Float_32_example(),
      unit = TempControlMixed.TempUnit.byOrdinal(0).get)
  }

  /** invariant AbsZero
    */
  @strictpure def AbsZero_Invariant(value: TempControlMixed.Temperature): B =
    GUMBO_Mixed_Definitions.GUMBO__Library.aboveAbsoluteZero(value.degrees)

  /** D-Inv Data Invariant for TempControlMixed.Temperature
    */
  @strictpure def D_Inv_Temperature(value: TempControlMixed.Temperature): B =
    (AbsZero_Invariant(value))

  /** D-Inv-Guard Data Invariant for TempControlMixed.Temperature
    */
  @strictpure def D_Inv_Guard_Temperature(value: Option[TempControlMixed.Temperature]): B =
    value.nonEmpty -->: D_Inv_Temperature(value.get)
}

@datatype class Temperature(
  val degrees: F32,
  val unit: TempControlMixed.TempUnit.Type) {
  @spec def AbsZero = Invariant(
    GUMBO_Mixed_Definitions.GUMBO__Library.aboveAbsoluteZero(degrees)
  )
}

object Temperature_Payload {
  def example(): Temperature_Payload = {
    return Temperature_Payload(TempControlMixed.Temperature.example())
  }
}

@datatype class Temperature_Payload(value: TempControlMixed.Temperature) extends art.DataContent
