// #Sireum

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

package tc.TempSensor_tsp_tst

import org.sireum._
import art._
import art.Art.BridgeId._
import art.Art.PortId._
import art.DispatchPropertyProtocol._
import art.PortMode._
import tc._
import tc.TempControlMixedSeL4CAmKES.TempSensor_tsp_tst_seL4Nix

object tst extends App {

  val tstBridge : tc.TempControlMixedSeL4CAmKES.TempSensor_tsp_tst_Bridge = {
    val currentTemp = Port[TempControlMixedSeL4CAmKES.Temperature] (id = portId"0", name = "TempControlSystem_Instance_tsp_tst_currentTemp", mode = DataOut)
    val tempChanged = Port[art.Empty] (id = portId"1", name = "TempControlSystem_Instance_tsp_tst_tempChanged", mode = EventOut)

    tc.TempControlMixedSeL4CAmKES.TempSensor_tsp_tst_Bridge(
      id = bridgeId"0",
      name = "TempControlSystem_Instance_tsp_tst",
      dispatchProtocol = Periodic(period = 1000),
      dispatchTriggers = None(),

      currentTemp = currentTemp,
      tempChanged = tempChanged
    )
  }

  val entryPoints: Bridge.EntryPoints = tstBridge.entryPoints
  val noData: Option[DataContent] = None()

  // currentTemp: Out DataPort TempControlMixedSeL4CAmKES.Temperature
  val currentTemp_id: Art.PortId = tstBridge.currentTemp.id
  var currentTemp_port: Option[DataContent] = noData

  // tempChanged: Out EventPort art.Empty
  val tempChanged_id: Art.PortId = tstBridge.tempChanged.id
  var tempChanged_port: Option[DataContent] = noData

  def dispatchStatus(bridgeId: Art.BridgeId): DispatchStatus = {
    return TimeTriggered()
  }

  def getValue(portId: Art.PortId): Option[DataContent] = {
    halt(s"Unexpected: tst.getValue called with: ${portId}")
  }

  def receiveInput(eventPortIds: ISZ[Art.PortId], dataPortIds: ISZ[Art.PortId]): Unit = {
    // ignore params


  }

  def putValue(portId: Art.PortId, data: DataContent): Unit = {
    if(portId == currentTemp_id) {
      currentTemp_port = Some(data)
    } else if(portId == tempChanged_id) {
      tempChanged_port = Some(data)
    } else {
      halt(s"Unexpected: tst.putValue called with: ${portId}")
    }
  }

  def sendOutput(eventPortIds: ISZ[Art.PortId], dataPortIds: ISZ[Art.PortId]): Unit = {
    // ignore params

    if(currentTemp_port.nonEmpty) {
      TempSensor_tsp_tst_seL4Nix.currentTemp_Send(currentTemp_port.get)
      currentTemp_port = noData
    }

    if(tempChanged_port.nonEmpty) {
      TempSensor_tsp_tst_seL4Nix.tempChanged_Send(tempChanged_port.get)
      tempChanged_port = noData
    }
  }

  def initialiseArchitecture(): Unit = {
    // nothing to do - CAmkES is responsible for initialization
  }

  def initialiseEntryPoint(): Unit = { entryPoints.initialise() }

  def computeEntryPoint(): Unit = { entryPoints.compute() }

  def finaliseEntryPoint(): Unit = { entryPoints.finalise() }

  def main(args: ISZ[String]): Z = {

    // need to touch the following for transpiler
    initialiseArchitecture()
    initialiseEntryPoint()
    computeEntryPoint()
    finaliseEntryPoint()

    touch()

    return 0
  }

  def touch(): Unit = {
    if(F) {
      TranspilerToucher.touch()

      // add types used in Platform.receive and Platform.receiveAsync
      val mbox2Boolean_Payload: MBox2[Art.PortId, DataContent] = MBox2(portId"0", Base_Types.Boolean_Payload(T))
      val mbox2OptionDataContent: MBox2[Art.PortId, Option[DataContent]] = MBox2(portId"0", None())

      // touch each payload/type in case some are only used as a field in a record
      def printDataContent(a: art.DataContent): Unit = { println(s"${a}") }

      printDataContent(Base_Types.Boolean_Payload(Base_Types.Boolean_example()))
      printDataContent(Base_Types.Integer_Payload(Base_Types.Integer_example()))
      printDataContent(Base_Types.Integer_8_Payload(Base_Types.Integer_8_example()))
      printDataContent(Base_Types.Integer_16_Payload(Base_Types.Integer_16_example()))
      printDataContent(Base_Types.Integer_32_Payload(Base_Types.Integer_32_example()))
      printDataContent(Base_Types.Integer_64_Payload(Base_Types.Integer_64_example()))
      printDataContent(Base_Types.Unsigned_8_Payload(Base_Types.Unsigned_8_example()))
      printDataContent(Base_Types.Unsigned_16_Payload(Base_Types.Unsigned_16_example()))
      printDataContent(Base_Types.Unsigned_32_Payload(Base_Types.Unsigned_32_example()))
      printDataContent(Base_Types.Unsigned_64_Payload(Base_Types.Unsigned_64_example()))
      printDataContent(Base_Types.Float_Payload(Base_Types.Float_example()))
      printDataContent(Base_Types.Float_32_Payload(Base_Types.Float_32_example()))
      printDataContent(Base_Types.Float_64_Payload(Base_Types.Float_64_example()))
      printDataContent(Base_Types.Character_Payload(Base_Types.Character_example()))
      printDataContent(Base_Types.String_Payload(Base_Types.String_example()))
      printDataContent(TempControlMixedSeL4CAmKES.Temperature_Payload(TempControlMixedSeL4CAmKES.Temperature.example()))
      printDataContent(TempControlMixedSeL4CAmKES.TempUnit_Payload(TempControlMixedSeL4CAmKES.TempUnit.byOrdinal(0).get))
      printDataContent(TempControlMixedSeL4CAmKES.SetPoint_Payload(TempControlMixedSeL4CAmKES.SetPoint.example()))
      printDataContent(TempControlMixedSeL4CAmKES.FanCmd_Payload(TempControlMixedSeL4CAmKES.FanCmd.byOrdinal(0).get))
      printDataContent(TempControlMixedSeL4CAmKES.FanAck_Payload(TempControlMixedSeL4CAmKES.FanAck.byOrdinal(0).get))
      printDataContent(Isolette_Environment.Heat_Payload(Isolette_Environment.Heat.example()))
      printDataContent(Isolette_Environment.Interface_Interaction_Payload(Isolette_Environment.Interface_Interaction.example()))
      printDataContent(Isolette_Environment.Air_Interaction_Payload(Isolette_Environment.Air_Interaction.example()))
      printDataContent(TempControlMixed.Temperature_Payload(TempControlMixed.Temperature.example()))
      printDataContent(TempControlMixed.SetPoint_Payload(TempControlMixed.SetPoint.example()))
      printDataContent(TempControlMixed.TempUnit_Payload(TempControlMixed.TempUnit.byOrdinal(0).get))
      printDataContent(TempControlMixed.FanCmd_Payload(TempControlMixed.FanCmd.byOrdinal(0).get))
      printDataContent(TempControlMixed.FanAck_Payload(TempControlMixed.FanAck.byOrdinal(0).get))
      printDataContent(TempControlPeriodic.Temperature_Payload(TempControlPeriodic.Temperature.example()))
      printDataContent(TempControlPeriodic.SetPoint_Payload(TempControlPeriodic.SetPoint.example()))
      printDataContent(TempControlPeriodic.TempUnit_Payload(TempControlPeriodic.TempUnit.byOrdinal(0).get))
      printDataContent(TempControlPeriodic.FanCmd_Payload(TempControlPeriodic.FanCmd.byOrdinal(0).get))
      printDataContent(TempControlPeriodic.FanAck_Payload(TempControlPeriodic.FanAck.byOrdinal(0).get))
      printDataContent(Isolette_Data_Model.PhysicalTemp_Payload(Isolette_Data_Model.PhysicalTemp.example()))
      printDataContent(Isolette_Data_Model.TempWstatus_Payload(Isolette_Data_Model.TempWstatus.example()))
      printDataContent(Isolette_Data_Model.Temp_Payload(Isolette_Data_Model.Temp.example()))
      printDataContent(Isolette_Data_Model.On_Off_Payload(Isolette_Data_Model.On_Off.byOrdinal(0).get))
      printDataContent(Isolette_Data_Model.Failure_Flag_Payload(Isolette_Data_Model.Failure_Flag.example()))
      printDataContent(Isolette_Data_Model.ValueStatus_Payload(Isolette_Data_Model.ValueStatus.byOrdinal(0).get))
      printDataContent(Isolette_Data_Model.Status_Payload(Isolette_Data_Model.Status.byOrdinal(0).get))
      printDataContent(Isolette_Data_Model.Regulator_Mode_Payload(Isolette_Data_Model.Regulator_Mode.byOrdinal(0).get))
      printDataContent(Isolette_Data_Model.Monitor_Mode_Payload(Isolette_Data_Model.Monitor_Mode.byOrdinal(0).get))
      printDataContent(art.Empty())

      tc.TempControlMixedSeL4CAmKES.TempSensor_tsp_tst_Bridge.c_initialization_api.get.logInfo("")
      tc.TempControlMixedSeL4CAmKES.TempSensor_tsp_tst_Bridge.c_initialization_api.get.logDebug("")
      tc.TempControlMixedSeL4CAmKES.TempSensor_tsp_tst_Bridge.c_initialization_api.get.logError("")
      tc.TempControlMixedSeL4CAmKES.TempSensor_tsp_tst_Bridge.c_operational_api.get.logInfo("")
      tc.TempControlMixedSeL4CAmKES.TempSensor_tsp_tst_Bridge.c_operational_api.get.logDebug("")
      tc.TempControlMixedSeL4CAmKES.TempSensor_tsp_tst_Bridge.c_operational_api.get.logError("")
      tc.TempControlMixedSeL4CAmKES.TempSensor_tsp_tst_Bridge.c_initialization_api.get.put_currentTemp(TempControlMixedSeL4CAmKES.Temperature.example())
      tc.TempControlMixedSeL4CAmKES.TempSensor_tsp_tst_Bridge.c_operational_api.get.put_currentTemp(TempControlMixedSeL4CAmKES.Temperature.example())
      tc.TempControlMixedSeL4CAmKES.TempSensor_tsp_tst_Bridge.c_initialization_api.get.put_tempChanged()
      tc.TempControlMixedSeL4CAmKES.TempSensor_tsp_tst_Bridge.c_operational_api.get.put_tempChanged()
    }
  }

  def logInfo(title: String, msg: String): Unit = {
    print(tstBridge.name)
    print(": ")
    println(msg)
  }

  def logError(title: String, msg: String): Unit = {
    eprint(tstBridge.name)
    eprint(": ")
    eprintln(msg)
  }

  def logDebug(title: String, msg: String): Unit = {
    print(tstBridge.name)
    print(": ")
    println(msg)
  }

  def run(): Unit = {}

}
