// Do not edit this file as it will be overwritten if HAMR codegen is rerun

#ifndef SB_TEMPSENSOR_H
#define SB_TEMPSENSOR_H

#include <sb_types.h>

bool sb_currentTemp_write(const union_art_DataContent * value);

bool sb_tempChanged_enqueue(void);

#endif // SB_TEMPSENSOR_H
