// #Sireum

package tc.GUMBO_Mixed_Definitions

import org.sireum._
import tc._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

object GUMBO__Library {
  @strictpure def aboveAbsoluteZero(degrees: Base_Types.Float_32): Base_Types.Boolean = degrees > -459.67f
}
