// #Sireum

package tc.TempControlMixedSeL4CAmKES

import org.sireum._
import art.Art
import tc._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun
@msig trait Fan_fp_ft_TestApi {

  def BeforeEntrypoint(): Unit = {
    Art.initTest(Arch.TempControlSystem_Instance_fp_ft)
  }

  def AfterEntrypoint(): Unit = {
    Art.finalizeTest(Arch.TempControlSystem_Instance_fp_ft)
  }

  def testCompute(): Unit = {
    Art.manuallyClearOutput()
    Art.testCompute(Arch.TempControlSystem_Instance_fp_ft)
  }

  def testInitialise(): Unit = {
    Art.manuallyClearOutput()
    Art.testInitialise(Arch.TempControlSystem_Instance_fp_ft)
  }

  /** helper function to set the values of all input ports.
   * @param fanCmd payloads for event data port fanCmd.
   *   ART currently supports single element event data queues so
   *   only the last element of fanCmd will be used
   */
  def put_concrete_inputs(fanCmd : ISZ[TempControlMixedSeL4CAmKES.FanCmd.Type]): Unit = {
    for(v <- fanCmd){
      put_fanCmd(v)
    }
  }


  /** helper function to check Fan_fp_ft's
   * output ports.  Use named arguments to check subsets of the output ports.
   * @param fanAck method that will be called with the payloads to be sent
   *        on the outgoing event data port 'fanAck'.
   */
  def check_concrete_output(fanAck: ISZ[TempControlMixedSeL4CAmKES.FanAck.Type] => B): Unit = {
    var testFailures: ISZ[ST] = ISZ()

    var fanAckValue: ISZ[TempControlMixedSeL4CAmKES.FanAck.Type] = ISZ()
    // TODO: event data port getter should return all of the events/payloads
    //       received on event data ports when queue sizes > 1 support is added
    //       to ART
    if(get_fanAck().nonEmpty) { fanAckValue = fanAckValue :+ get_fanAck().get }
    if(!fanAck(fanAckValue)) {
      testFailures = testFailures :+ st"'fanAck' did not match expected: received ${fanAckValue.size} events with the following payloads ${fanAckValue}"
    }

    assert(testFailures.isEmpty, st"${(testFailures, "\n")}".render)
  }


  // setter for in EventDataPort
  def put_fanCmd(value : TempControlMixedSeL4CAmKES.FanCmd.Type): Unit = {
    Art.insertInInfrastructurePort(Arch.TempControlSystem_Instance_fp_ft.operational_api.fanCmd_Id, TempControlMixedSeL4CAmKES.FanCmd_Payload(value))
  }

  // getter for out EventDataPort
  def get_fanAck(): Option[TempControlMixedSeL4CAmKES.FanAck.Type] = {
    val value: Option[TempControlMixedSeL4CAmKES.FanAck.Type] = get_fanAck_payload() match {
      case Some(TempControlMixedSeL4CAmKES.FanAck_Payload(v)) => Some(v)
      case Some(v) => halt(s"Unexpected payload on port fanAck.  Expecting 'TempControlMixedSeL4CAmKES.FanAck_Payload' but received ${v}")
      case _ => None[TempControlMixedSeL4CAmKES.FanAck.Type]()
    }
    return value
  }

  // payload getter for out EventDataPort
  def get_fanAck_payload(): Option[TempControlMixedSeL4CAmKES.FanAck_Payload] = {
    return Art.observeOutInfrastructurePort(Arch.TempControlSystem_Instance_fp_ft.initialization_api.fanAck_Id).asInstanceOf[Option[TempControlMixedSeL4CAmKES.FanAck_Payload]]
  }

}
