// Do not edit this file as it will be overwritten if HAMR codegen is rerun

#ifndef SB_FAN_H
#define SB_FAN_H

#include <sb_types.h>

bool sb_fanCmd_dequeue(union_art_DataContent *);

bool sb_fanAck_enqueue(const union_art_DataContent *);

#endif // SB_FAN_H
