#include <all.h>

B Type__eq(void *t1, void *t2) {
  TYPE type = ((Type) t1)->type;
  if (type != ((Type) t2)->type) return F;
  switch (type) {
    case TIS_948B60: return IS_948B60__eq((IS_948B60) t1, (IS_948B60) t2);
    case TIS_D10119: return IS_D10119__eq((IS_D10119) t1, (IS_D10119) t2);
    case TIS_820232: return IS_820232__eq((IS_820232) t1, (IS_820232) t2);
    case TMBox2_37E193: return MBox2_37E193__eq((MBox2_37E193) t1, (MBox2_37E193) t2);
    case TMBox2_43CC67: return MBox2_43CC67__eq((MBox2_43CC67) t1, (MBox2_43CC67) t2);
    case TMS_83D5EB: return MS_83D5EB__eq((MS_83D5EB) t1, (MS_83D5EB) t2);
    case TNone_CFD2B0: return None_CFD2B0__eq((None_CFD2B0) t1, (None_CFD2B0) t2);
    case TNone_734370: return None_734370__eq((None_734370) t1, (None_734370) t2);
    case TNone_964667: return None_964667__eq((None_964667) t1, (None_964667) t2);
    case TNone_BE2C3F: return None_BE2C3F__eq((None_BE2C3F) t1, (None_BE2C3F) t2);
    case TNone_BE24EA: return None_BE24EA__eq((None_BE24EA) t1, (None_BE24EA) t2);
    case TNone_3C78E7: return None_3C78E7__eq((None_3C78E7) t1, (None_3C78E7) t2);
    case TNone_A45A41: return None_A45A41__eq((None_A45A41) t1, (None_A45A41) t2);
    case TNone_A23E58: return None_A23E58__eq((None_A23E58) t1, (None_A23E58) t2);
    case TNone_B4A4FA: return None_B4A4FA__eq((None_B4A4FA) t1, (None_B4A4FA) t2);
    case TNone_1AEC2C: return None_1AEC2C__eq((None_1AEC2C) t1, (None_1AEC2C) t2);
    case TNone_121724: return None_121724__eq((None_121724) t1, (None_121724) t2);
    case TNone_A70CEE: return None_A70CEE__eq((None_A70CEE) t1, (None_A70CEE) t2);
    case TNone_ACDB63: return None_ACDB63__eq((None_ACDB63) t1, (None_ACDB63) t2);
    case TNone_B66650: return None_B66650__eq((None_B66650) t1, (None_B66650) t2);
    case TNone_79FC20: return None_79FC20__eq((None_79FC20) t1, (None_79FC20) t2);
    case TNone_86BF24: return None_86BF24__eq((None_86BF24) t1, (None_86BF24) t2);
    case TNone_D4B208: return None_D4B208__eq((None_D4B208) t1, (None_D4B208) t2);
    case TNone_037804: return None_037804__eq((None_037804) t1, (None_037804) t2);
    case TNone_4E7E94: return None_4E7E94__eq((None_4E7E94) t1, (None_4E7E94) t2);
    case TRandom_Gen64Impl: return Random_Gen64Impl__eq((Random_Gen64Impl) t1, (Random_Gen64Impl) t2);
    case TRandom_Impl_SplitMix64: return Random_Impl_SplitMix64__eq((Random_Impl_SplitMix64) t1, (Random_Impl_SplitMix64) t2);
    case TRandom_Impl_Xoshiro256: return Random_Impl_Xoshiro256__eq((Random_Impl_Xoshiro256) t1, (Random_Impl_Xoshiro256) t2);
    case TSome_D29615: return Some_D29615__eq((Some_D29615) t1, (Some_D29615) t2);
    case TSome_455777: return Some_455777__eq((Some_455777) t1, (Some_455777) t2);
    case TSome_F1808D: return Some_F1808D__eq((Some_F1808D) t1, (Some_F1808D) t2);
    case TSome_C790DA: return Some_C790DA__eq((Some_C790DA) t1, (Some_C790DA) t2);
    case TSome_140719: return Some_140719__eq((Some_140719) t1, (Some_140719) t2);
    case TSome_21C1E5: return Some_21C1E5__eq((Some_21C1E5) t1, (Some_21C1E5) t2);
    case TSome_270A8B: return Some_270A8B__eq((Some_270A8B) t1, (Some_270A8B) t2);
    case TSome_776961: return Some_776961__eq((Some_776961) t1, (Some_776961) t2);
    case TSome_0E3FBA: return Some_0E3FBA__eq((Some_0E3FBA) t1, (Some_0E3FBA) t2);
    case TSome_D85467: return Some_D85467__eq((Some_D85467) t1, (Some_D85467) t2);
    case TSome_2EFA7D: return Some_2EFA7D__eq((Some_2EFA7D) t1, (Some_2EFA7D) t2);
    case TSome_B14D88: return Some_B14D88__eq((Some_B14D88) t1, (Some_B14D88) t2);
    case TSome_FBE41D: return Some_FBE41D__eq((Some_FBE41D) t1, (Some_FBE41D) t2);
    case TSome_0C4CF8: return Some_0C4CF8__eq((Some_0C4CF8) t1, (Some_0C4CF8) t2);
    case TSome_C3173C: return Some_C3173C__eq((Some_C3173C) t1, (Some_C3173C) t2);
    case TSome_C0DBA9: return Some_C0DBA9__eq((Some_C0DBA9) t1, (Some_C0DBA9) t2);
    case TSome_56FCC9: return Some_56FCC9__eq((Some_56FCC9) t1, (Some_56FCC9) t2);
    case TString: return String__eq((String) t1, (String) t2);
    case Tart_Bridge_Ports: return art_Bridge_Ports__eq((art_Bridge_Ports) t1, (art_Bridge_Ports) t2);
    case Tart_DispatchPropertyProtocol_Periodic: return art_DispatchPropertyProtocol_Periodic__eq((art_DispatchPropertyProtocol_Periodic) t1, (art_DispatchPropertyProtocol_Periodic) t2);
    case Tart_Empty: return art_Empty__eq((art_Empty) t1, (art_Empty) t2);
    case Tart_Port_9CBF18: return art_Port_9CBF18__eq((art_Port_9CBF18) t1, (art_Port_9CBF18) t2);
    case Tart_Port_890848: return art_Port_890848__eq((art_Port_890848) t1, (art_Port_890848) t2);
    case Ttc_Base_Types_Boolean_Payload: return tc_Base_Types_Boolean_Payload__eq((tc_Base_Types_Boolean_Payload) t1, (tc_Base_Types_Boolean_Payload) t2);
    case Ttc_Base_Types_Character_Payload: return tc_Base_Types_Character_Payload__eq((tc_Base_Types_Character_Payload) t1, (tc_Base_Types_Character_Payload) t2);
    case Ttc_Base_Types_Float_32_Payload: return tc_Base_Types_Float_32_Payload__eq((tc_Base_Types_Float_32_Payload) t1, (tc_Base_Types_Float_32_Payload) t2);
    case Ttc_Base_Types_Float_64_Payload: return tc_Base_Types_Float_64_Payload__eq((tc_Base_Types_Float_64_Payload) t1, (tc_Base_Types_Float_64_Payload) t2);
    case Ttc_Base_Types_Float_Payload: return tc_Base_Types_Float_Payload__eq((tc_Base_Types_Float_Payload) t1, (tc_Base_Types_Float_Payload) t2);
    case Ttc_Base_Types_Integer_16_Payload: return tc_Base_Types_Integer_16_Payload__eq((tc_Base_Types_Integer_16_Payload) t1, (tc_Base_Types_Integer_16_Payload) t2);
    case Ttc_Base_Types_Integer_32_Payload: return tc_Base_Types_Integer_32_Payload__eq((tc_Base_Types_Integer_32_Payload) t1, (tc_Base_Types_Integer_32_Payload) t2);
    case Ttc_Base_Types_Integer_64_Payload: return tc_Base_Types_Integer_64_Payload__eq((tc_Base_Types_Integer_64_Payload) t1, (tc_Base_Types_Integer_64_Payload) t2);
    case Ttc_Base_Types_Integer_8_Payload: return tc_Base_Types_Integer_8_Payload__eq((tc_Base_Types_Integer_8_Payload) t1, (tc_Base_Types_Integer_8_Payload) t2);
    case Ttc_Base_Types_Integer_Payload: return tc_Base_Types_Integer_Payload__eq((tc_Base_Types_Integer_Payload) t1, (tc_Base_Types_Integer_Payload) t2);
    case Ttc_Base_Types_String_Payload: return tc_Base_Types_String_Payload__eq((tc_Base_Types_String_Payload) t1, (tc_Base_Types_String_Payload) t2);
    case Ttc_Base_Types_Unsigned_16_Payload: return tc_Base_Types_Unsigned_16_Payload__eq((tc_Base_Types_Unsigned_16_Payload) t1, (tc_Base_Types_Unsigned_16_Payload) t2);
    case Ttc_Base_Types_Unsigned_32_Payload: return tc_Base_Types_Unsigned_32_Payload__eq((tc_Base_Types_Unsigned_32_Payload) t1, (tc_Base_Types_Unsigned_32_Payload) t2);
    case Ttc_Base_Types_Unsigned_64_Payload: return tc_Base_Types_Unsigned_64_Payload__eq((tc_Base_Types_Unsigned_64_Payload) t1, (tc_Base_Types_Unsigned_64_Payload) t2);
    case Ttc_Base_Types_Unsigned_8_Payload: return tc_Base_Types_Unsigned_8_Payload__eq((tc_Base_Types_Unsigned_8_Payload) t1, (tc_Base_Types_Unsigned_8_Payload) t2);
    case Ttc_Isolette_Data_Model_Failure_Flag: return tc_Isolette_Data_Model_Failure_Flag__eq((tc_Isolette_Data_Model_Failure_Flag) t1, (tc_Isolette_Data_Model_Failure_Flag) t2);
    case Ttc_Isolette_Data_Model_Failure_Flag_Payload: return tc_Isolette_Data_Model_Failure_Flag_Payload__eq((tc_Isolette_Data_Model_Failure_Flag_Payload) t1, (tc_Isolette_Data_Model_Failure_Flag_Payload) t2);
    case Ttc_Isolette_Data_Model_Monitor_Mode_Payload: return tc_Isolette_Data_Model_Monitor_Mode_Payload__eq((tc_Isolette_Data_Model_Monitor_Mode_Payload) t1, (tc_Isolette_Data_Model_Monitor_Mode_Payload) t2);
    case Ttc_Isolette_Data_Model_On_Off_Payload: return tc_Isolette_Data_Model_On_Off_Payload__eq((tc_Isolette_Data_Model_On_Off_Payload) t1, (tc_Isolette_Data_Model_On_Off_Payload) t2);
    case Ttc_Isolette_Data_Model_PhysicalTemp: return tc_Isolette_Data_Model_PhysicalTemp__eq((tc_Isolette_Data_Model_PhysicalTemp) t1, (tc_Isolette_Data_Model_PhysicalTemp) t2);
    case Ttc_Isolette_Data_Model_PhysicalTemp_Payload: return tc_Isolette_Data_Model_PhysicalTemp_Payload__eq((tc_Isolette_Data_Model_PhysicalTemp_Payload) t1, (tc_Isolette_Data_Model_PhysicalTemp_Payload) t2);
    case Ttc_Isolette_Data_Model_Regulator_Mode_Payload: return tc_Isolette_Data_Model_Regulator_Mode_Payload__eq((tc_Isolette_Data_Model_Regulator_Mode_Payload) t1, (tc_Isolette_Data_Model_Regulator_Mode_Payload) t2);
    case Ttc_Isolette_Data_Model_Status_Payload: return tc_Isolette_Data_Model_Status_Payload__eq((tc_Isolette_Data_Model_Status_Payload) t1, (tc_Isolette_Data_Model_Status_Payload) t2);
    case Ttc_Isolette_Data_Model_Temp: return tc_Isolette_Data_Model_Temp__eq((tc_Isolette_Data_Model_Temp) t1, (tc_Isolette_Data_Model_Temp) t2);
    case Ttc_Isolette_Data_Model_TempWstatus: return tc_Isolette_Data_Model_TempWstatus__eq((tc_Isolette_Data_Model_TempWstatus) t1, (tc_Isolette_Data_Model_TempWstatus) t2);
    case Ttc_Isolette_Data_Model_TempWstatus_Payload: return tc_Isolette_Data_Model_TempWstatus_Payload__eq((tc_Isolette_Data_Model_TempWstatus_Payload) t1, (tc_Isolette_Data_Model_TempWstatus_Payload) t2);
    case Ttc_Isolette_Data_Model_Temp_Payload: return tc_Isolette_Data_Model_Temp_Payload__eq((tc_Isolette_Data_Model_Temp_Payload) t1, (tc_Isolette_Data_Model_Temp_Payload) t2);
    case Ttc_Isolette_Data_Model_ValueStatus_Payload: return tc_Isolette_Data_Model_ValueStatus_Payload__eq((tc_Isolette_Data_Model_ValueStatus_Payload) t1, (tc_Isolette_Data_Model_ValueStatus_Payload) t2);
    case Ttc_Isolette_Environment_Air_Interaction: return tc_Isolette_Environment_Air_Interaction__eq((tc_Isolette_Environment_Air_Interaction) t1, (tc_Isolette_Environment_Air_Interaction) t2);
    case Ttc_Isolette_Environment_Air_Interaction_Payload: return tc_Isolette_Environment_Air_Interaction_Payload__eq((tc_Isolette_Environment_Air_Interaction_Payload) t1, (tc_Isolette_Environment_Air_Interaction_Payload) t2);
    case Ttc_Isolette_Environment_Heat: return tc_Isolette_Environment_Heat__eq((tc_Isolette_Environment_Heat) t1, (tc_Isolette_Environment_Heat) t2);
    case Ttc_Isolette_Environment_Heat_Payload: return tc_Isolette_Environment_Heat_Payload__eq((tc_Isolette_Environment_Heat_Payload) t1, (tc_Isolette_Environment_Heat_Payload) t2);
    case Ttc_Isolette_Environment_Interface_Interaction: return tc_Isolette_Environment_Interface_Interaction__eq((tc_Isolette_Environment_Interface_Interaction) t1, (tc_Isolette_Environment_Interface_Interaction) t2);
    case Ttc_Isolette_Environment_Interface_Interaction_Payload: return tc_Isolette_Environment_Interface_Interaction_Payload__eq((tc_Isolette_Environment_Interface_Interaction_Payload) t1, (tc_Isolette_Environment_Interface_Interaction_Payload) t2);
    case Ttc_TempControlMixed_FanAck_Payload: return tc_TempControlMixed_FanAck_Payload__eq((tc_TempControlMixed_FanAck_Payload) t1, (tc_TempControlMixed_FanAck_Payload) t2);
    case Ttc_TempControlMixed_FanCmd_Payload: return tc_TempControlMixed_FanCmd_Payload__eq((tc_TempControlMixed_FanCmd_Payload) t1, (tc_TempControlMixed_FanCmd_Payload) t2);
    case Ttc_TempControlMixed_SetPoint: return tc_TempControlMixed_SetPoint__eq((tc_TempControlMixed_SetPoint) t1, (tc_TempControlMixed_SetPoint) t2);
    case Ttc_TempControlMixed_SetPoint_Payload: return tc_TempControlMixed_SetPoint_Payload__eq((tc_TempControlMixed_SetPoint_Payload) t1, (tc_TempControlMixed_SetPoint_Payload) t2);
    case Ttc_TempControlMixed_TempUnit_Payload: return tc_TempControlMixed_TempUnit_Payload__eq((tc_TempControlMixed_TempUnit_Payload) t1, (tc_TempControlMixed_TempUnit_Payload) t2);
    case Ttc_TempControlMixed_Temperature: return tc_TempControlMixed_Temperature__eq((tc_TempControlMixed_Temperature) t1, (tc_TempControlMixed_Temperature) t2);
    case Ttc_TempControlMixed_Temperature_Payload: return tc_TempControlMixed_Temperature_Payload__eq((tc_TempControlMixed_Temperature_Payload) t1, (tc_TempControlMixed_Temperature_Payload) t2);
    case Ttc_TempControlMixedSeL4CAmKES_FanAck_Payload: return tc_TempControlMixedSeL4CAmKES_FanAck_Payload__eq((tc_TempControlMixedSeL4CAmKES_FanAck_Payload) t1, (tc_TempControlMixedSeL4CAmKES_FanAck_Payload) t2);
    case Ttc_TempControlMixedSeL4CAmKES_FanCmd_Payload: return tc_TempControlMixedSeL4CAmKES_FanCmd_Payload__eq((tc_TempControlMixedSeL4CAmKES_FanCmd_Payload) t1, (tc_TempControlMixedSeL4CAmKES_FanCmd_Payload) t2);
    case Ttc_TempControlMixedSeL4CAmKES_SetPoint: return tc_TempControlMixedSeL4CAmKES_SetPoint__eq((tc_TempControlMixedSeL4CAmKES_SetPoint) t1, (tc_TempControlMixedSeL4CAmKES_SetPoint) t2);
    case Ttc_TempControlMixedSeL4CAmKES_SetPoint_Payload: return tc_TempControlMixedSeL4CAmKES_SetPoint_Payload__eq((tc_TempControlMixedSeL4CAmKES_SetPoint_Payload) t1, (tc_TempControlMixedSeL4CAmKES_SetPoint_Payload) t2);
    case Ttc_TempControlMixedSeL4CAmKES_TempSensor_Initialization_Api: return tc_TempControlMixedSeL4CAmKES_TempSensor_Initialization_Api__eq((tc_TempControlMixedSeL4CAmKES_TempSensor_Initialization_Api) t1, (tc_TempControlMixedSeL4CAmKES_TempSensor_Initialization_Api) t2);
    case Ttc_TempControlMixedSeL4CAmKES_TempSensor_Operational_Api: return tc_TempControlMixedSeL4CAmKES_TempSensor_Operational_Api__eq((tc_TempControlMixedSeL4CAmKES_TempSensor_Operational_Api) t1, (tc_TempControlMixedSeL4CAmKES_TempSensor_Operational_Api) t2);
    case Ttc_TempControlMixedSeL4CAmKES_TempSensor_tsp_tst_Bridge: return tc_TempControlMixedSeL4CAmKES_TempSensor_tsp_tst_Bridge__eq((tc_TempControlMixedSeL4CAmKES_TempSensor_tsp_tst_Bridge) t1, (tc_TempControlMixedSeL4CAmKES_TempSensor_tsp_tst_Bridge) t2);
    case Ttc_TempControlMixedSeL4CAmKES_TempSensor_tsp_tst_Bridge_EntryPoints: return tc_TempControlMixedSeL4CAmKES_TempSensor_tsp_tst_Bridge_EntryPoints__eq((tc_TempControlMixedSeL4CAmKES_TempSensor_tsp_tst_Bridge_EntryPoints) t1, (tc_TempControlMixedSeL4CAmKES_TempSensor_tsp_tst_Bridge_EntryPoints) t2);
    case Ttc_TempControlMixedSeL4CAmKES_TempUnit_Payload: return tc_TempControlMixedSeL4CAmKES_TempUnit_Payload__eq((tc_TempControlMixedSeL4CAmKES_TempUnit_Payload) t1, (tc_TempControlMixedSeL4CAmKES_TempUnit_Payload) t2);
    case Ttc_TempControlMixedSeL4CAmKES_Temperature: return tc_TempControlMixedSeL4CAmKES_Temperature__eq((tc_TempControlMixedSeL4CAmKES_Temperature) t1, (tc_TempControlMixedSeL4CAmKES_Temperature) t2);
    case Ttc_TempControlMixedSeL4CAmKES_Temperature_Payload: return tc_TempControlMixedSeL4CAmKES_Temperature_Payload__eq((tc_TempControlMixedSeL4CAmKES_Temperature_Payload) t1, (tc_TempControlMixedSeL4CAmKES_Temperature_Payload) t2);
    case Ttc_TempControlPeriodic_FanAck_Payload: return tc_TempControlPeriodic_FanAck_Payload__eq((tc_TempControlPeriodic_FanAck_Payload) t1, (tc_TempControlPeriodic_FanAck_Payload) t2);
    case Ttc_TempControlPeriodic_FanCmd_Payload: return tc_TempControlPeriodic_FanCmd_Payload__eq((tc_TempControlPeriodic_FanCmd_Payload) t1, (tc_TempControlPeriodic_FanCmd_Payload) t2);
    case Ttc_TempControlPeriodic_SetPoint: return tc_TempControlPeriodic_SetPoint__eq((tc_TempControlPeriodic_SetPoint) t1, (tc_TempControlPeriodic_SetPoint) t2);
    case Ttc_TempControlPeriodic_SetPoint_Payload: return tc_TempControlPeriodic_SetPoint_Payload__eq((tc_TempControlPeriodic_SetPoint_Payload) t1, (tc_TempControlPeriodic_SetPoint_Payload) t2);
    case Ttc_TempControlPeriodic_TempUnit_Payload: return tc_TempControlPeriodic_TempUnit_Payload__eq((tc_TempControlPeriodic_TempUnit_Payload) t1, (tc_TempControlPeriodic_TempUnit_Payload) t2);
    case Ttc_TempControlPeriodic_Temperature: return tc_TempControlPeriodic_Temperature__eq((tc_TempControlPeriodic_Temperature) t1, (tc_TempControlPeriodic_Temperature) t2);
    case Ttc_TempControlPeriodic_Temperature_Payload: return tc_TempControlPeriodic_Temperature_Payload__eq((tc_TempControlPeriodic_Temperature_Payload) t1, (tc_TempControlPeriodic_Temperature_Payload) t2);
    default: fprintf(stderr, "%s: %d\n", "Unexpected TYPE: ", type); exit(1);
  }
}

B Type__equiv(void *t1, void *t2) {
  TYPE type = ((Type) t1)->type;
  if (type != ((Type) t2)->type) return F;
  switch (type) {
    case TIS_948B60: return IS_948B60__equiv((IS_948B60) t1, (IS_948B60) t2);
    case TIS_D10119: return IS_D10119__equiv((IS_D10119) t1, (IS_D10119) t2);
    case TIS_820232: return IS_820232__equiv((IS_820232) t1, (IS_820232) t2);
    case TMBox2_37E193: return MBox2_37E193__equiv((MBox2_37E193) t1, (MBox2_37E193) t2);
    case TMBox2_43CC67: return MBox2_43CC67__equiv((MBox2_43CC67) t1, (MBox2_43CC67) t2);
    case TMS_83D5EB: return MS_83D5EB__equiv((MS_83D5EB) t1, (MS_83D5EB) t2);
    case TNone_CFD2B0: return None_CFD2B0__equiv((None_CFD2B0) t1, (None_CFD2B0) t2);
    case TNone_734370: return None_734370__equiv((None_734370) t1, (None_734370) t2);
    case TNone_964667: return None_964667__equiv((None_964667) t1, (None_964667) t2);
    case TNone_BE2C3F: return None_BE2C3F__equiv((None_BE2C3F) t1, (None_BE2C3F) t2);
    case TNone_BE24EA: return None_BE24EA__equiv((None_BE24EA) t1, (None_BE24EA) t2);
    case TNone_3C78E7: return None_3C78E7__equiv((None_3C78E7) t1, (None_3C78E7) t2);
    case TNone_A45A41: return None_A45A41__equiv((None_A45A41) t1, (None_A45A41) t2);
    case TNone_A23E58: return None_A23E58__equiv((None_A23E58) t1, (None_A23E58) t2);
    case TNone_B4A4FA: return None_B4A4FA__equiv((None_B4A4FA) t1, (None_B4A4FA) t2);
    case TNone_1AEC2C: return None_1AEC2C__equiv((None_1AEC2C) t1, (None_1AEC2C) t2);
    case TNone_121724: return None_121724__equiv((None_121724) t1, (None_121724) t2);
    case TNone_A70CEE: return None_A70CEE__equiv((None_A70CEE) t1, (None_A70CEE) t2);
    case TNone_ACDB63: return None_ACDB63__equiv((None_ACDB63) t1, (None_ACDB63) t2);
    case TNone_B66650: return None_B66650__equiv((None_B66650) t1, (None_B66650) t2);
    case TNone_79FC20: return None_79FC20__equiv((None_79FC20) t1, (None_79FC20) t2);
    case TNone_86BF24: return None_86BF24__equiv((None_86BF24) t1, (None_86BF24) t2);
    case TNone_D4B208: return None_D4B208__equiv((None_D4B208) t1, (None_D4B208) t2);
    case TNone_037804: return None_037804__equiv((None_037804) t1, (None_037804) t2);
    case TNone_4E7E94: return None_4E7E94__equiv((None_4E7E94) t1, (None_4E7E94) t2);
    case TRandom_Gen64Impl: return Random_Gen64Impl__equiv((Random_Gen64Impl) t1, (Random_Gen64Impl) t2);
    case TRandom_Impl_SplitMix64: return Random_Impl_SplitMix64__equiv((Random_Impl_SplitMix64) t1, (Random_Impl_SplitMix64) t2);
    case TRandom_Impl_Xoshiro256: return Random_Impl_Xoshiro256__equiv((Random_Impl_Xoshiro256) t1, (Random_Impl_Xoshiro256) t2);
    case TSome_D29615: return Some_D29615__equiv((Some_D29615) t1, (Some_D29615) t2);
    case TSome_455777: return Some_455777__equiv((Some_455777) t1, (Some_455777) t2);
    case TSome_F1808D: return Some_F1808D__equiv((Some_F1808D) t1, (Some_F1808D) t2);
    case TSome_C790DA: return Some_C790DA__equiv((Some_C790DA) t1, (Some_C790DA) t2);
    case TSome_140719: return Some_140719__equiv((Some_140719) t1, (Some_140719) t2);
    case TSome_21C1E5: return Some_21C1E5__equiv((Some_21C1E5) t1, (Some_21C1E5) t2);
    case TSome_270A8B: return Some_270A8B__equiv((Some_270A8B) t1, (Some_270A8B) t2);
    case TSome_776961: return Some_776961__equiv((Some_776961) t1, (Some_776961) t2);
    case TSome_0E3FBA: return Some_0E3FBA__equiv((Some_0E3FBA) t1, (Some_0E3FBA) t2);
    case TSome_D85467: return Some_D85467__equiv((Some_D85467) t1, (Some_D85467) t2);
    case TSome_2EFA7D: return Some_2EFA7D__equiv((Some_2EFA7D) t1, (Some_2EFA7D) t2);
    case TSome_B14D88: return Some_B14D88__equiv((Some_B14D88) t1, (Some_B14D88) t2);
    case TSome_FBE41D: return Some_FBE41D__equiv((Some_FBE41D) t1, (Some_FBE41D) t2);
    case TSome_0C4CF8: return Some_0C4CF8__equiv((Some_0C4CF8) t1, (Some_0C4CF8) t2);
    case TSome_C3173C: return Some_C3173C__equiv((Some_C3173C) t1, (Some_C3173C) t2);
    case TSome_C0DBA9: return Some_C0DBA9__equiv((Some_C0DBA9) t1, (Some_C0DBA9) t2);
    case TSome_56FCC9: return Some_56FCC9__equiv((Some_56FCC9) t1, (Some_56FCC9) t2);
    case TString: return String__equiv((String) t1, (String) t2);
    case Tart_Bridge_Ports: return art_Bridge_Ports__equiv((art_Bridge_Ports) t1, (art_Bridge_Ports) t2);
    case Tart_DispatchPropertyProtocol_Periodic: return art_DispatchPropertyProtocol_Periodic__equiv((art_DispatchPropertyProtocol_Periodic) t1, (art_DispatchPropertyProtocol_Periodic) t2);
    case Tart_Empty: return art_Empty__equiv((art_Empty) t1, (art_Empty) t2);
    case Tart_Port_9CBF18: return art_Port_9CBF18__equiv((art_Port_9CBF18) t1, (art_Port_9CBF18) t2);
    case Tart_Port_890848: return art_Port_890848__equiv((art_Port_890848) t1, (art_Port_890848) t2);
    case Ttc_Base_Types_Boolean_Payload: return tc_Base_Types_Boolean_Payload__equiv((tc_Base_Types_Boolean_Payload) t1, (tc_Base_Types_Boolean_Payload) t2);
    case Ttc_Base_Types_Character_Payload: return tc_Base_Types_Character_Payload__equiv((tc_Base_Types_Character_Payload) t1, (tc_Base_Types_Character_Payload) t2);
    case Ttc_Base_Types_Float_32_Payload: return tc_Base_Types_Float_32_Payload__equiv((tc_Base_Types_Float_32_Payload) t1, (tc_Base_Types_Float_32_Payload) t2);
    case Ttc_Base_Types_Float_64_Payload: return tc_Base_Types_Float_64_Payload__equiv((tc_Base_Types_Float_64_Payload) t1, (tc_Base_Types_Float_64_Payload) t2);
    case Ttc_Base_Types_Float_Payload: return tc_Base_Types_Float_Payload__equiv((tc_Base_Types_Float_Payload) t1, (tc_Base_Types_Float_Payload) t2);
    case Ttc_Base_Types_Integer_16_Payload: return tc_Base_Types_Integer_16_Payload__equiv((tc_Base_Types_Integer_16_Payload) t1, (tc_Base_Types_Integer_16_Payload) t2);
    case Ttc_Base_Types_Integer_32_Payload: return tc_Base_Types_Integer_32_Payload__equiv((tc_Base_Types_Integer_32_Payload) t1, (tc_Base_Types_Integer_32_Payload) t2);
    case Ttc_Base_Types_Integer_64_Payload: return tc_Base_Types_Integer_64_Payload__equiv((tc_Base_Types_Integer_64_Payload) t1, (tc_Base_Types_Integer_64_Payload) t2);
    case Ttc_Base_Types_Integer_8_Payload: return tc_Base_Types_Integer_8_Payload__equiv((tc_Base_Types_Integer_8_Payload) t1, (tc_Base_Types_Integer_8_Payload) t2);
    case Ttc_Base_Types_Integer_Payload: return tc_Base_Types_Integer_Payload__equiv((tc_Base_Types_Integer_Payload) t1, (tc_Base_Types_Integer_Payload) t2);
    case Ttc_Base_Types_String_Payload: return tc_Base_Types_String_Payload__equiv((tc_Base_Types_String_Payload) t1, (tc_Base_Types_String_Payload) t2);
    case Ttc_Base_Types_Unsigned_16_Payload: return tc_Base_Types_Unsigned_16_Payload__equiv((tc_Base_Types_Unsigned_16_Payload) t1, (tc_Base_Types_Unsigned_16_Payload) t2);
    case Ttc_Base_Types_Unsigned_32_Payload: return tc_Base_Types_Unsigned_32_Payload__equiv((tc_Base_Types_Unsigned_32_Payload) t1, (tc_Base_Types_Unsigned_32_Payload) t2);
    case Ttc_Base_Types_Unsigned_64_Payload: return tc_Base_Types_Unsigned_64_Payload__equiv((tc_Base_Types_Unsigned_64_Payload) t1, (tc_Base_Types_Unsigned_64_Payload) t2);
    case Ttc_Base_Types_Unsigned_8_Payload: return tc_Base_Types_Unsigned_8_Payload__equiv((tc_Base_Types_Unsigned_8_Payload) t1, (tc_Base_Types_Unsigned_8_Payload) t2);
    case Ttc_Isolette_Data_Model_Failure_Flag: return tc_Isolette_Data_Model_Failure_Flag__equiv((tc_Isolette_Data_Model_Failure_Flag) t1, (tc_Isolette_Data_Model_Failure_Flag) t2);
    case Ttc_Isolette_Data_Model_Failure_Flag_Payload: return tc_Isolette_Data_Model_Failure_Flag_Payload__equiv((tc_Isolette_Data_Model_Failure_Flag_Payload) t1, (tc_Isolette_Data_Model_Failure_Flag_Payload) t2);
    case Ttc_Isolette_Data_Model_Monitor_Mode_Payload: return tc_Isolette_Data_Model_Monitor_Mode_Payload__equiv((tc_Isolette_Data_Model_Monitor_Mode_Payload) t1, (tc_Isolette_Data_Model_Monitor_Mode_Payload) t2);
    case Ttc_Isolette_Data_Model_On_Off_Payload: return tc_Isolette_Data_Model_On_Off_Payload__equiv((tc_Isolette_Data_Model_On_Off_Payload) t1, (tc_Isolette_Data_Model_On_Off_Payload) t2);
    case Ttc_Isolette_Data_Model_PhysicalTemp: return tc_Isolette_Data_Model_PhysicalTemp__equiv((tc_Isolette_Data_Model_PhysicalTemp) t1, (tc_Isolette_Data_Model_PhysicalTemp) t2);
    case Ttc_Isolette_Data_Model_PhysicalTemp_Payload: return tc_Isolette_Data_Model_PhysicalTemp_Payload__equiv((tc_Isolette_Data_Model_PhysicalTemp_Payload) t1, (tc_Isolette_Data_Model_PhysicalTemp_Payload) t2);
    case Ttc_Isolette_Data_Model_Regulator_Mode_Payload: return tc_Isolette_Data_Model_Regulator_Mode_Payload__equiv((tc_Isolette_Data_Model_Regulator_Mode_Payload) t1, (tc_Isolette_Data_Model_Regulator_Mode_Payload) t2);
    case Ttc_Isolette_Data_Model_Status_Payload: return tc_Isolette_Data_Model_Status_Payload__equiv((tc_Isolette_Data_Model_Status_Payload) t1, (tc_Isolette_Data_Model_Status_Payload) t2);
    case Ttc_Isolette_Data_Model_Temp: return tc_Isolette_Data_Model_Temp__equiv((tc_Isolette_Data_Model_Temp) t1, (tc_Isolette_Data_Model_Temp) t2);
    case Ttc_Isolette_Data_Model_TempWstatus: return tc_Isolette_Data_Model_TempWstatus__equiv((tc_Isolette_Data_Model_TempWstatus) t1, (tc_Isolette_Data_Model_TempWstatus) t2);
    case Ttc_Isolette_Data_Model_TempWstatus_Payload: return tc_Isolette_Data_Model_TempWstatus_Payload__equiv((tc_Isolette_Data_Model_TempWstatus_Payload) t1, (tc_Isolette_Data_Model_TempWstatus_Payload) t2);
    case Ttc_Isolette_Data_Model_Temp_Payload: return tc_Isolette_Data_Model_Temp_Payload__equiv((tc_Isolette_Data_Model_Temp_Payload) t1, (tc_Isolette_Data_Model_Temp_Payload) t2);
    case Ttc_Isolette_Data_Model_ValueStatus_Payload: return tc_Isolette_Data_Model_ValueStatus_Payload__equiv((tc_Isolette_Data_Model_ValueStatus_Payload) t1, (tc_Isolette_Data_Model_ValueStatus_Payload) t2);
    case Ttc_Isolette_Environment_Air_Interaction: return tc_Isolette_Environment_Air_Interaction__equiv((tc_Isolette_Environment_Air_Interaction) t1, (tc_Isolette_Environment_Air_Interaction) t2);
    case Ttc_Isolette_Environment_Air_Interaction_Payload: return tc_Isolette_Environment_Air_Interaction_Payload__equiv((tc_Isolette_Environment_Air_Interaction_Payload) t1, (tc_Isolette_Environment_Air_Interaction_Payload) t2);
    case Ttc_Isolette_Environment_Heat: return tc_Isolette_Environment_Heat__equiv((tc_Isolette_Environment_Heat) t1, (tc_Isolette_Environment_Heat) t2);
    case Ttc_Isolette_Environment_Heat_Payload: return tc_Isolette_Environment_Heat_Payload__equiv((tc_Isolette_Environment_Heat_Payload) t1, (tc_Isolette_Environment_Heat_Payload) t2);
    case Ttc_Isolette_Environment_Interface_Interaction: return tc_Isolette_Environment_Interface_Interaction__equiv((tc_Isolette_Environment_Interface_Interaction) t1, (tc_Isolette_Environment_Interface_Interaction) t2);
    case Ttc_Isolette_Environment_Interface_Interaction_Payload: return tc_Isolette_Environment_Interface_Interaction_Payload__equiv((tc_Isolette_Environment_Interface_Interaction_Payload) t1, (tc_Isolette_Environment_Interface_Interaction_Payload) t2);
    case Ttc_TempControlMixed_FanAck_Payload: return tc_TempControlMixed_FanAck_Payload__equiv((tc_TempControlMixed_FanAck_Payload) t1, (tc_TempControlMixed_FanAck_Payload) t2);
    case Ttc_TempControlMixed_FanCmd_Payload: return tc_TempControlMixed_FanCmd_Payload__equiv((tc_TempControlMixed_FanCmd_Payload) t1, (tc_TempControlMixed_FanCmd_Payload) t2);
    case Ttc_TempControlMixed_SetPoint: return tc_TempControlMixed_SetPoint__equiv((tc_TempControlMixed_SetPoint) t1, (tc_TempControlMixed_SetPoint) t2);
    case Ttc_TempControlMixed_SetPoint_Payload: return tc_TempControlMixed_SetPoint_Payload__equiv((tc_TempControlMixed_SetPoint_Payload) t1, (tc_TempControlMixed_SetPoint_Payload) t2);
    case Ttc_TempControlMixed_TempUnit_Payload: return tc_TempControlMixed_TempUnit_Payload__equiv((tc_TempControlMixed_TempUnit_Payload) t1, (tc_TempControlMixed_TempUnit_Payload) t2);
    case Ttc_TempControlMixed_Temperature: return tc_TempControlMixed_Temperature__equiv((tc_TempControlMixed_Temperature) t1, (tc_TempControlMixed_Temperature) t2);
    case Ttc_TempControlMixed_Temperature_Payload: return tc_TempControlMixed_Temperature_Payload__equiv((tc_TempControlMixed_Temperature_Payload) t1, (tc_TempControlMixed_Temperature_Payload) t2);
    case Ttc_TempControlMixedSeL4CAmKES_FanAck_Payload: return tc_TempControlMixedSeL4CAmKES_FanAck_Payload__equiv((tc_TempControlMixedSeL4CAmKES_FanAck_Payload) t1, (tc_TempControlMixedSeL4CAmKES_FanAck_Payload) t2);
    case Ttc_TempControlMixedSeL4CAmKES_FanCmd_Payload: return tc_TempControlMixedSeL4CAmKES_FanCmd_Payload__equiv((tc_TempControlMixedSeL4CAmKES_FanCmd_Payload) t1, (tc_TempControlMixedSeL4CAmKES_FanCmd_Payload) t2);
    case Ttc_TempControlMixedSeL4CAmKES_SetPoint: return tc_TempControlMixedSeL4CAmKES_SetPoint__equiv((tc_TempControlMixedSeL4CAmKES_SetPoint) t1, (tc_TempControlMixedSeL4CAmKES_SetPoint) t2);
    case Ttc_TempControlMixedSeL4CAmKES_SetPoint_Payload: return tc_TempControlMixedSeL4CAmKES_SetPoint_Payload__equiv((tc_TempControlMixedSeL4CAmKES_SetPoint_Payload) t1, (tc_TempControlMixedSeL4CAmKES_SetPoint_Payload) t2);
    case Ttc_TempControlMixedSeL4CAmKES_TempSensor_Initialization_Api: return tc_TempControlMixedSeL4CAmKES_TempSensor_Initialization_Api__equiv((tc_TempControlMixedSeL4CAmKES_TempSensor_Initialization_Api) t1, (tc_TempControlMixedSeL4CAmKES_TempSensor_Initialization_Api) t2);
    case Ttc_TempControlMixedSeL4CAmKES_TempSensor_Operational_Api: return tc_TempControlMixedSeL4CAmKES_TempSensor_Operational_Api__equiv((tc_TempControlMixedSeL4CAmKES_TempSensor_Operational_Api) t1, (tc_TempControlMixedSeL4CAmKES_TempSensor_Operational_Api) t2);
    case Ttc_TempControlMixedSeL4CAmKES_TempSensor_tsp_tst_Bridge: return tc_TempControlMixedSeL4CAmKES_TempSensor_tsp_tst_Bridge__equiv((tc_TempControlMixedSeL4CAmKES_TempSensor_tsp_tst_Bridge) t1, (tc_TempControlMixedSeL4CAmKES_TempSensor_tsp_tst_Bridge) t2);
    case Ttc_TempControlMixedSeL4CAmKES_TempSensor_tsp_tst_Bridge_EntryPoints: return tc_TempControlMixedSeL4CAmKES_TempSensor_tsp_tst_Bridge_EntryPoints__equiv((tc_TempControlMixedSeL4CAmKES_TempSensor_tsp_tst_Bridge_EntryPoints) t1, (tc_TempControlMixedSeL4CAmKES_TempSensor_tsp_tst_Bridge_EntryPoints) t2);
    case Ttc_TempControlMixedSeL4CAmKES_TempUnit_Payload: return tc_TempControlMixedSeL4CAmKES_TempUnit_Payload__equiv((tc_TempControlMixedSeL4CAmKES_TempUnit_Payload) t1, (tc_TempControlMixedSeL4CAmKES_TempUnit_Payload) t2);
    case Ttc_TempControlMixedSeL4CAmKES_Temperature: return tc_TempControlMixedSeL4CAmKES_Temperature__equiv((tc_TempControlMixedSeL4CAmKES_Temperature) t1, (tc_TempControlMixedSeL4CAmKES_Temperature) t2);
    case Ttc_TempControlMixedSeL4CAmKES_Temperature_Payload: return tc_TempControlMixedSeL4CAmKES_Temperature_Payload__equiv((tc_TempControlMixedSeL4CAmKES_Temperature_Payload) t1, (tc_TempControlMixedSeL4CAmKES_Temperature_Payload) t2);
    case Ttc_TempControlPeriodic_FanAck_Payload: return tc_TempControlPeriodic_FanAck_Payload__equiv((tc_TempControlPeriodic_FanAck_Payload) t1, (tc_TempControlPeriodic_FanAck_Payload) t2);
    case Ttc_TempControlPeriodic_FanCmd_Payload: return tc_TempControlPeriodic_FanCmd_Payload__equiv((tc_TempControlPeriodic_FanCmd_Payload) t1, (tc_TempControlPeriodic_FanCmd_Payload) t2);
    case Ttc_TempControlPeriodic_SetPoint: return tc_TempControlPeriodic_SetPoint__equiv((tc_TempControlPeriodic_SetPoint) t1, (tc_TempControlPeriodic_SetPoint) t2);
    case Ttc_TempControlPeriodic_SetPoint_Payload: return tc_TempControlPeriodic_SetPoint_Payload__equiv((tc_TempControlPeriodic_SetPoint_Payload) t1, (tc_TempControlPeriodic_SetPoint_Payload) t2);
    case Ttc_TempControlPeriodic_TempUnit_Payload: return tc_TempControlPeriodic_TempUnit_Payload__equiv((tc_TempControlPeriodic_TempUnit_Payload) t1, (tc_TempControlPeriodic_TempUnit_Payload) t2);
    case Ttc_TempControlPeriodic_Temperature: return tc_TempControlPeriodic_Temperature__equiv((tc_TempControlPeriodic_Temperature) t1, (tc_TempControlPeriodic_Temperature) t2);
    case Ttc_TempControlPeriodic_Temperature_Payload: return tc_TempControlPeriodic_Temperature_Payload__equiv((tc_TempControlPeriodic_Temperature_Payload) t1, (tc_TempControlPeriodic_Temperature_Payload) t2);
    default: fprintf(stderr, "%s: %d\n", "Unexpected TYPE: ", type); exit(1);
  }
}

void Type_cprint(void *this, B isOut) {
  #ifndef SIREUM_NO_PRINT
  TYPE type = ((Type) this)->type;
  switch (type) {
    case TIS_948B60: IS_948B60_cprint((IS_948B60) this, isOut); return;
    case TIS_D10119: IS_D10119_cprint((IS_D10119) this, isOut); return;
    case TIS_820232: IS_820232_cprint((IS_820232) this, isOut); return;
    case TMBox2_37E193: MBox2_37E193_cprint((MBox2_37E193) this, isOut); return;
    case TMBox2_43CC67: MBox2_43CC67_cprint((MBox2_43CC67) this, isOut); return;
    case TMS_83D5EB: MS_83D5EB_cprint((MS_83D5EB) this, isOut); return;
    case TNone_CFD2B0: None_CFD2B0_cprint((None_CFD2B0) this, isOut); return;
    case TNone_734370: None_734370_cprint((None_734370) this, isOut); return;
    case TNone_964667: None_964667_cprint((None_964667) this, isOut); return;
    case TNone_BE2C3F: None_BE2C3F_cprint((None_BE2C3F) this, isOut); return;
    case TNone_BE24EA: None_BE24EA_cprint((None_BE24EA) this, isOut); return;
    case TNone_3C78E7: None_3C78E7_cprint((None_3C78E7) this, isOut); return;
    case TNone_A45A41: None_A45A41_cprint((None_A45A41) this, isOut); return;
    case TNone_A23E58: None_A23E58_cprint((None_A23E58) this, isOut); return;
    case TNone_B4A4FA: None_B4A4FA_cprint((None_B4A4FA) this, isOut); return;
    case TNone_1AEC2C: None_1AEC2C_cprint((None_1AEC2C) this, isOut); return;
    case TNone_121724: None_121724_cprint((None_121724) this, isOut); return;
    case TNone_A70CEE: None_A70CEE_cprint((None_A70CEE) this, isOut); return;
    case TNone_ACDB63: None_ACDB63_cprint((None_ACDB63) this, isOut); return;
    case TNone_B66650: None_B66650_cprint((None_B66650) this, isOut); return;
    case TNone_79FC20: None_79FC20_cprint((None_79FC20) this, isOut); return;
    case TNone_86BF24: None_86BF24_cprint((None_86BF24) this, isOut); return;
    case TNone_D4B208: None_D4B208_cprint((None_D4B208) this, isOut); return;
    case TNone_037804: None_037804_cprint((None_037804) this, isOut); return;
    case TNone_4E7E94: None_4E7E94_cprint((None_4E7E94) this, isOut); return;
    case TRandom_Gen64Impl: Random_Gen64Impl_cprint((Random_Gen64Impl) this, isOut); return;
    case TRandom_Impl_SplitMix64: Random_Impl_SplitMix64_cprint((Random_Impl_SplitMix64) this, isOut); return;
    case TRandom_Impl_Xoshiro256: Random_Impl_Xoshiro256_cprint((Random_Impl_Xoshiro256) this, isOut); return;
    case TSome_D29615: Some_D29615_cprint((Some_D29615) this, isOut); return;
    case TSome_455777: Some_455777_cprint((Some_455777) this, isOut); return;
    case TSome_F1808D: Some_F1808D_cprint((Some_F1808D) this, isOut); return;
    case TSome_C790DA: Some_C790DA_cprint((Some_C790DA) this, isOut); return;
    case TSome_140719: Some_140719_cprint((Some_140719) this, isOut); return;
    case TSome_21C1E5: Some_21C1E5_cprint((Some_21C1E5) this, isOut); return;
    case TSome_270A8B: Some_270A8B_cprint((Some_270A8B) this, isOut); return;
    case TSome_776961: Some_776961_cprint((Some_776961) this, isOut); return;
    case TSome_0E3FBA: Some_0E3FBA_cprint((Some_0E3FBA) this, isOut); return;
    case TSome_D85467: Some_D85467_cprint((Some_D85467) this, isOut); return;
    case TSome_2EFA7D: Some_2EFA7D_cprint((Some_2EFA7D) this, isOut); return;
    case TSome_B14D88: Some_B14D88_cprint((Some_B14D88) this, isOut); return;
    case TSome_FBE41D: Some_FBE41D_cprint((Some_FBE41D) this, isOut); return;
    case TSome_0C4CF8: Some_0C4CF8_cprint((Some_0C4CF8) this, isOut); return;
    case TSome_C3173C: Some_C3173C_cprint((Some_C3173C) this, isOut); return;
    case TSome_C0DBA9: Some_C0DBA9_cprint((Some_C0DBA9) this, isOut); return;
    case TSome_56FCC9: Some_56FCC9_cprint((Some_56FCC9) this, isOut); return;
    case TString: String_cprint((String) this, isOut); return;
    case Tart_Bridge_Ports: art_Bridge_Ports_cprint((art_Bridge_Ports) this, isOut); return;
    case Tart_DispatchPropertyProtocol_Periodic: art_DispatchPropertyProtocol_Periodic_cprint((art_DispatchPropertyProtocol_Periodic) this, isOut); return;
    case Tart_Empty: art_Empty_cprint((art_Empty) this, isOut); return;
    case Tart_Port_9CBF18: art_Port_9CBF18_cprint((art_Port_9CBF18) this, isOut); return;
    case Tart_Port_890848: art_Port_890848_cprint((art_Port_890848) this, isOut); return;
    case Ttc_Base_Types_Boolean_Payload: tc_Base_Types_Boolean_Payload_cprint((tc_Base_Types_Boolean_Payload) this, isOut); return;
    case Ttc_Base_Types_Character_Payload: tc_Base_Types_Character_Payload_cprint((tc_Base_Types_Character_Payload) this, isOut); return;
    case Ttc_Base_Types_Float_32_Payload: tc_Base_Types_Float_32_Payload_cprint((tc_Base_Types_Float_32_Payload) this, isOut); return;
    case Ttc_Base_Types_Float_64_Payload: tc_Base_Types_Float_64_Payload_cprint((tc_Base_Types_Float_64_Payload) this, isOut); return;
    case Ttc_Base_Types_Float_Payload: tc_Base_Types_Float_Payload_cprint((tc_Base_Types_Float_Payload) this, isOut); return;
    case Ttc_Base_Types_Integer_16_Payload: tc_Base_Types_Integer_16_Payload_cprint((tc_Base_Types_Integer_16_Payload) this, isOut); return;
    case Ttc_Base_Types_Integer_32_Payload: tc_Base_Types_Integer_32_Payload_cprint((tc_Base_Types_Integer_32_Payload) this, isOut); return;
    case Ttc_Base_Types_Integer_64_Payload: tc_Base_Types_Integer_64_Payload_cprint((tc_Base_Types_Integer_64_Payload) this, isOut); return;
    case Ttc_Base_Types_Integer_8_Payload: tc_Base_Types_Integer_8_Payload_cprint((tc_Base_Types_Integer_8_Payload) this, isOut); return;
    case Ttc_Base_Types_Integer_Payload: tc_Base_Types_Integer_Payload_cprint((tc_Base_Types_Integer_Payload) this, isOut); return;
    case Ttc_Base_Types_String_Payload: tc_Base_Types_String_Payload_cprint((tc_Base_Types_String_Payload) this, isOut); return;
    case Ttc_Base_Types_Unsigned_16_Payload: tc_Base_Types_Unsigned_16_Payload_cprint((tc_Base_Types_Unsigned_16_Payload) this, isOut); return;
    case Ttc_Base_Types_Unsigned_32_Payload: tc_Base_Types_Unsigned_32_Payload_cprint((tc_Base_Types_Unsigned_32_Payload) this, isOut); return;
    case Ttc_Base_Types_Unsigned_64_Payload: tc_Base_Types_Unsigned_64_Payload_cprint((tc_Base_Types_Unsigned_64_Payload) this, isOut); return;
    case Ttc_Base_Types_Unsigned_8_Payload: tc_Base_Types_Unsigned_8_Payload_cprint((tc_Base_Types_Unsigned_8_Payload) this, isOut); return;
    case Ttc_Isolette_Data_Model_Failure_Flag: tc_Isolette_Data_Model_Failure_Flag_cprint((tc_Isolette_Data_Model_Failure_Flag) this, isOut); return;
    case Ttc_Isolette_Data_Model_Failure_Flag_Payload: tc_Isolette_Data_Model_Failure_Flag_Payload_cprint((tc_Isolette_Data_Model_Failure_Flag_Payload) this, isOut); return;
    case Ttc_Isolette_Data_Model_Monitor_Mode_Payload: tc_Isolette_Data_Model_Monitor_Mode_Payload_cprint((tc_Isolette_Data_Model_Monitor_Mode_Payload) this, isOut); return;
    case Ttc_Isolette_Data_Model_On_Off_Payload: tc_Isolette_Data_Model_On_Off_Payload_cprint((tc_Isolette_Data_Model_On_Off_Payload) this, isOut); return;
    case Ttc_Isolette_Data_Model_PhysicalTemp: tc_Isolette_Data_Model_PhysicalTemp_cprint((tc_Isolette_Data_Model_PhysicalTemp) this, isOut); return;
    case Ttc_Isolette_Data_Model_PhysicalTemp_Payload: tc_Isolette_Data_Model_PhysicalTemp_Payload_cprint((tc_Isolette_Data_Model_PhysicalTemp_Payload) this, isOut); return;
    case Ttc_Isolette_Data_Model_Regulator_Mode_Payload: tc_Isolette_Data_Model_Regulator_Mode_Payload_cprint((tc_Isolette_Data_Model_Regulator_Mode_Payload) this, isOut); return;
    case Ttc_Isolette_Data_Model_Status_Payload: tc_Isolette_Data_Model_Status_Payload_cprint((tc_Isolette_Data_Model_Status_Payload) this, isOut); return;
    case Ttc_Isolette_Data_Model_Temp: tc_Isolette_Data_Model_Temp_cprint((tc_Isolette_Data_Model_Temp) this, isOut); return;
    case Ttc_Isolette_Data_Model_TempWstatus: tc_Isolette_Data_Model_TempWstatus_cprint((tc_Isolette_Data_Model_TempWstatus) this, isOut); return;
    case Ttc_Isolette_Data_Model_TempWstatus_Payload: tc_Isolette_Data_Model_TempWstatus_Payload_cprint((tc_Isolette_Data_Model_TempWstatus_Payload) this, isOut); return;
    case Ttc_Isolette_Data_Model_Temp_Payload: tc_Isolette_Data_Model_Temp_Payload_cprint((tc_Isolette_Data_Model_Temp_Payload) this, isOut); return;
    case Ttc_Isolette_Data_Model_ValueStatus_Payload: tc_Isolette_Data_Model_ValueStatus_Payload_cprint((tc_Isolette_Data_Model_ValueStatus_Payload) this, isOut); return;
    case Ttc_Isolette_Environment_Air_Interaction: tc_Isolette_Environment_Air_Interaction_cprint((tc_Isolette_Environment_Air_Interaction) this, isOut); return;
    case Ttc_Isolette_Environment_Air_Interaction_Payload: tc_Isolette_Environment_Air_Interaction_Payload_cprint((tc_Isolette_Environment_Air_Interaction_Payload) this, isOut); return;
    case Ttc_Isolette_Environment_Heat: tc_Isolette_Environment_Heat_cprint((tc_Isolette_Environment_Heat) this, isOut); return;
    case Ttc_Isolette_Environment_Heat_Payload: tc_Isolette_Environment_Heat_Payload_cprint((tc_Isolette_Environment_Heat_Payload) this, isOut); return;
    case Ttc_Isolette_Environment_Interface_Interaction: tc_Isolette_Environment_Interface_Interaction_cprint((tc_Isolette_Environment_Interface_Interaction) this, isOut); return;
    case Ttc_Isolette_Environment_Interface_Interaction_Payload: tc_Isolette_Environment_Interface_Interaction_Payload_cprint((tc_Isolette_Environment_Interface_Interaction_Payload) this, isOut); return;
    case Ttc_TempControlMixed_FanAck_Payload: tc_TempControlMixed_FanAck_Payload_cprint((tc_TempControlMixed_FanAck_Payload) this, isOut); return;
    case Ttc_TempControlMixed_FanCmd_Payload: tc_TempControlMixed_FanCmd_Payload_cprint((tc_TempControlMixed_FanCmd_Payload) this, isOut); return;
    case Ttc_TempControlMixed_SetPoint: tc_TempControlMixed_SetPoint_cprint((tc_TempControlMixed_SetPoint) this, isOut); return;
    case Ttc_TempControlMixed_SetPoint_Payload: tc_TempControlMixed_SetPoint_Payload_cprint((tc_TempControlMixed_SetPoint_Payload) this, isOut); return;
    case Ttc_TempControlMixed_TempUnit_Payload: tc_TempControlMixed_TempUnit_Payload_cprint((tc_TempControlMixed_TempUnit_Payload) this, isOut); return;
    case Ttc_TempControlMixed_Temperature: tc_TempControlMixed_Temperature_cprint((tc_TempControlMixed_Temperature) this, isOut); return;
    case Ttc_TempControlMixed_Temperature_Payload: tc_TempControlMixed_Temperature_Payload_cprint((tc_TempControlMixed_Temperature_Payload) this, isOut); return;
    case Ttc_TempControlMixedSeL4CAmKES_FanAck_Payload: tc_TempControlMixedSeL4CAmKES_FanAck_Payload_cprint((tc_TempControlMixedSeL4CAmKES_FanAck_Payload) this, isOut); return;
    case Ttc_TempControlMixedSeL4CAmKES_FanCmd_Payload: tc_TempControlMixedSeL4CAmKES_FanCmd_Payload_cprint((tc_TempControlMixedSeL4CAmKES_FanCmd_Payload) this, isOut); return;
    case Ttc_TempControlMixedSeL4CAmKES_SetPoint: tc_TempControlMixedSeL4CAmKES_SetPoint_cprint((tc_TempControlMixedSeL4CAmKES_SetPoint) this, isOut); return;
    case Ttc_TempControlMixedSeL4CAmKES_SetPoint_Payload: tc_TempControlMixedSeL4CAmKES_SetPoint_Payload_cprint((tc_TempControlMixedSeL4CAmKES_SetPoint_Payload) this, isOut); return;
    case Ttc_TempControlMixedSeL4CAmKES_TempSensor_Initialization_Api: tc_TempControlMixedSeL4CAmKES_TempSensor_Initialization_Api_cprint((tc_TempControlMixedSeL4CAmKES_TempSensor_Initialization_Api) this, isOut); return;
    case Ttc_TempControlMixedSeL4CAmKES_TempSensor_Operational_Api: tc_TempControlMixedSeL4CAmKES_TempSensor_Operational_Api_cprint((tc_TempControlMixedSeL4CAmKES_TempSensor_Operational_Api) this, isOut); return;
    case Ttc_TempControlMixedSeL4CAmKES_TempSensor_tsp_tst_Bridge: tc_TempControlMixedSeL4CAmKES_TempSensor_tsp_tst_Bridge_cprint((tc_TempControlMixedSeL4CAmKES_TempSensor_tsp_tst_Bridge) this, isOut); return;
    case Ttc_TempControlMixedSeL4CAmKES_TempSensor_tsp_tst_Bridge_EntryPoints: tc_TempControlMixedSeL4CAmKES_TempSensor_tsp_tst_Bridge_EntryPoints_cprint((tc_TempControlMixedSeL4CAmKES_TempSensor_tsp_tst_Bridge_EntryPoints) this, isOut); return;
    case Ttc_TempControlMixedSeL4CAmKES_TempUnit_Payload: tc_TempControlMixedSeL4CAmKES_TempUnit_Payload_cprint((tc_TempControlMixedSeL4CAmKES_TempUnit_Payload) this, isOut); return;
    case Ttc_TempControlMixedSeL4CAmKES_Temperature: tc_TempControlMixedSeL4CAmKES_Temperature_cprint((tc_TempControlMixedSeL4CAmKES_Temperature) this, isOut); return;
    case Ttc_TempControlMixedSeL4CAmKES_Temperature_Payload: tc_TempControlMixedSeL4CAmKES_Temperature_Payload_cprint((tc_TempControlMixedSeL4CAmKES_Temperature_Payload) this, isOut); return;
    case Ttc_TempControlPeriodic_FanAck_Payload: tc_TempControlPeriodic_FanAck_Payload_cprint((tc_TempControlPeriodic_FanAck_Payload) this, isOut); return;
    case Ttc_TempControlPeriodic_FanCmd_Payload: tc_TempControlPeriodic_FanCmd_Payload_cprint((tc_TempControlPeriodic_FanCmd_Payload) this, isOut); return;
    case Ttc_TempControlPeriodic_SetPoint: tc_TempControlPeriodic_SetPoint_cprint((tc_TempControlPeriodic_SetPoint) this, isOut); return;
    case Ttc_TempControlPeriodic_SetPoint_Payload: tc_TempControlPeriodic_SetPoint_Payload_cprint((tc_TempControlPeriodic_SetPoint_Payload) this, isOut); return;
    case Ttc_TempControlPeriodic_TempUnit_Payload: tc_TempControlPeriodic_TempUnit_Payload_cprint((tc_TempControlPeriodic_TempUnit_Payload) this, isOut); return;
    case Ttc_TempControlPeriodic_Temperature: tc_TempControlPeriodic_Temperature_cprint((tc_TempControlPeriodic_Temperature) this, isOut); return;
    case Ttc_TempControlPeriodic_Temperature_Payload: tc_TempControlPeriodic_Temperature_Payload_cprint((tc_TempControlPeriodic_Temperature_Payload) this, isOut); return;
    default: fprintf(stderr, "%s: %d\n", "Unexpected TYPE: ", type); exit(1);
  }
  #endif
}

void Type_string_(STACK_FRAME String result, void *this) {
  TYPE type = ((Type) this)->type;
  switch (type) {
    case TIS_948B60: IS_948B60_string_(CALLER result, (IS_948B60) this); return;
    case TIS_D10119: IS_D10119_string_(CALLER result, (IS_D10119) this); return;
    case TIS_820232: IS_820232_string_(CALLER result, (IS_820232) this); return;
    case TMBox2_37E193: MBox2_37E193_string_(CALLER result, (MBox2_37E193) this); return;
    case TMBox2_43CC67: MBox2_43CC67_string_(CALLER result, (MBox2_43CC67) this); return;
    case TMS_83D5EB: MS_83D5EB_string_(CALLER result, (MS_83D5EB) this); return;
    case TNone_CFD2B0: None_CFD2B0_string_(CALLER result, (None_CFD2B0) this); return;
    case TNone_734370: None_734370_string_(CALLER result, (None_734370) this); return;
    case TNone_964667: None_964667_string_(CALLER result, (None_964667) this); return;
    case TNone_BE2C3F: None_BE2C3F_string_(CALLER result, (None_BE2C3F) this); return;
    case TNone_BE24EA: None_BE24EA_string_(CALLER result, (None_BE24EA) this); return;
    case TNone_3C78E7: None_3C78E7_string_(CALLER result, (None_3C78E7) this); return;
    case TNone_A45A41: None_A45A41_string_(CALLER result, (None_A45A41) this); return;
    case TNone_A23E58: None_A23E58_string_(CALLER result, (None_A23E58) this); return;
    case TNone_B4A4FA: None_B4A4FA_string_(CALLER result, (None_B4A4FA) this); return;
    case TNone_1AEC2C: None_1AEC2C_string_(CALLER result, (None_1AEC2C) this); return;
    case TNone_121724: None_121724_string_(CALLER result, (None_121724) this); return;
    case TNone_A70CEE: None_A70CEE_string_(CALLER result, (None_A70CEE) this); return;
    case TNone_ACDB63: None_ACDB63_string_(CALLER result, (None_ACDB63) this); return;
    case TNone_B66650: None_B66650_string_(CALLER result, (None_B66650) this); return;
    case TNone_79FC20: None_79FC20_string_(CALLER result, (None_79FC20) this); return;
    case TNone_86BF24: None_86BF24_string_(CALLER result, (None_86BF24) this); return;
    case TNone_D4B208: None_D4B208_string_(CALLER result, (None_D4B208) this); return;
    case TNone_037804: None_037804_string_(CALLER result, (None_037804) this); return;
    case TNone_4E7E94: None_4E7E94_string_(CALLER result, (None_4E7E94) this); return;
    case TRandom_Gen64Impl: Random_Gen64Impl_string_(CALLER result, (Random_Gen64Impl) this); return;
    case TRandom_Impl_SplitMix64: Random_Impl_SplitMix64_string_(CALLER result, (Random_Impl_SplitMix64) this); return;
    case TRandom_Impl_Xoshiro256: Random_Impl_Xoshiro256_string_(CALLER result, (Random_Impl_Xoshiro256) this); return;
    case TSome_D29615: Some_D29615_string_(CALLER result, (Some_D29615) this); return;
    case TSome_455777: Some_455777_string_(CALLER result, (Some_455777) this); return;
    case TSome_F1808D: Some_F1808D_string_(CALLER result, (Some_F1808D) this); return;
    case TSome_C790DA: Some_C790DA_string_(CALLER result, (Some_C790DA) this); return;
    case TSome_140719: Some_140719_string_(CALLER result, (Some_140719) this); return;
    case TSome_21C1E5: Some_21C1E5_string_(CALLER result, (Some_21C1E5) this); return;
    case TSome_270A8B: Some_270A8B_string_(CALLER result, (Some_270A8B) this); return;
    case TSome_776961: Some_776961_string_(CALLER result, (Some_776961) this); return;
    case TSome_0E3FBA: Some_0E3FBA_string_(CALLER result, (Some_0E3FBA) this); return;
    case TSome_D85467: Some_D85467_string_(CALLER result, (Some_D85467) this); return;
    case TSome_2EFA7D: Some_2EFA7D_string_(CALLER result, (Some_2EFA7D) this); return;
    case TSome_B14D88: Some_B14D88_string_(CALLER result, (Some_B14D88) this); return;
    case TSome_FBE41D: Some_FBE41D_string_(CALLER result, (Some_FBE41D) this); return;
    case TSome_0C4CF8: Some_0C4CF8_string_(CALLER result, (Some_0C4CF8) this); return;
    case TSome_C3173C: Some_C3173C_string_(CALLER result, (Some_C3173C) this); return;
    case TSome_C0DBA9: Some_C0DBA9_string_(CALLER result, (Some_C0DBA9) this); return;
    case TSome_56FCC9: Some_56FCC9_string_(CALLER result, (Some_56FCC9) this); return;
    case TString: String_string_(CALLER result, (String) this); return;
    case Tart_Bridge_Ports: art_Bridge_Ports_string_(CALLER result, (art_Bridge_Ports) this); return;
    case Tart_DispatchPropertyProtocol_Periodic: art_DispatchPropertyProtocol_Periodic_string_(CALLER result, (art_DispatchPropertyProtocol_Periodic) this); return;
    case Tart_Empty: art_Empty_string_(CALLER result, (art_Empty) this); return;
    case Tart_Port_9CBF18: art_Port_9CBF18_string_(CALLER result, (art_Port_9CBF18) this); return;
    case Tart_Port_890848: art_Port_890848_string_(CALLER result, (art_Port_890848) this); return;
    case Ttc_Base_Types_Boolean_Payload: tc_Base_Types_Boolean_Payload_string_(CALLER result, (tc_Base_Types_Boolean_Payload) this); return;
    case Ttc_Base_Types_Character_Payload: tc_Base_Types_Character_Payload_string_(CALLER result, (tc_Base_Types_Character_Payload) this); return;
    case Ttc_Base_Types_Float_32_Payload: tc_Base_Types_Float_32_Payload_string_(CALLER result, (tc_Base_Types_Float_32_Payload) this); return;
    case Ttc_Base_Types_Float_64_Payload: tc_Base_Types_Float_64_Payload_string_(CALLER result, (tc_Base_Types_Float_64_Payload) this); return;
    case Ttc_Base_Types_Float_Payload: tc_Base_Types_Float_Payload_string_(CALLER result, (tc_Base_Types_Float_Payload) this); return;
    case Ttc_Base_Types_Integer_16_Payload: tc_Base_Types_Integer_16_Payload_string_(CALLER result, (tc_Base_Types_Integer_16_Payload) this); return;
    case Ttc_Base_Types_Integer_32_Payload: tc_Base_Types_Integer_32_Payload_string_(CALLER result, (tc_Base_Types_Integer_32_Payload) this); return;
    case Ttc_Base_Types_Integer_64_Payload: tc_Base_Types_Integer_64_Payload_string_(CALLER result, (tc_Base_Types_Integer_64_Payload) this); return;
    case Ttc_Base_Types_Integer_8_Payload: tc_Base_Types_Integer_8_Payload_string_(CALLER result, (tc_Base_Types_Integer_8_Payload) this); return;
    case Ttc_Base_Types_Integer_Payload: tc_Base_Types_Integer_Payload_string_(CALLER result, (tc_Base_Types_Integer_Payload) this); return;
    case Ttc_Base_Types_String_Payload: tc_Base_Types_String_Payload_string_(CALLER result, (tc_Base_Types_String_Payload) this); return;
    case Ttc_Base_Types_Unsigned_16_Payload: tc_Base_Types_Unsigned_16_Payload_string_(CALLER result, (tc_Base_Types_Unsigned_16_Payload) this); return;
    case Ttc_Base_Types_Unsigned_32_Payload: tc_Base_Types_Unsigned_32_Payload_string_(CALLER result, (tc_Base_Types_Unsigned_32_Payload) this); return;
    case Ttc_Base_Types_Unsigned_64_Payload: tc_Base_Types_Unsigned_64_Payload_string_(CALLER result, (tc_Base_Types_Unsigned_64_Payload) this); return;
    case Ttc_Base_Types_Unsigned_8_Payload: tc_Base_Types_Unsigned_8_Payload_string_(CALLER result, (tc_Base_Types_Unsigned_8_Payload) this); return;
    case Ttc_Isolette_Data_Model_Failure_Flag: tc_Isolette_Data_Model_Failure_Flag_string_(CALLER result, (tc_Isolette_Data_Model_Failure_Flag) this); return;
    case Ttc_Isolette_Data_Model_Failure_Flag_Payload: tc_Isolette_Data_Model_Failure_Flag_Payload_string_(CALLER result, (tc_Isolette_Data_Model_Failure_Flag_Payload) this); return;
    case Ttc_Isolette_Data_Model_Monitor_Mode_Payload: tc_Isolette_Data_Model_Monitor_Mode_Payload_string_(CALLER result, (tc_Isolette_Data_Model_Monitor_Mode_Payload) this); return;
    case Ttc_Isolette_Data_Model_On_Off_Payload: tc_Isolette_Data_Model_On_Off_Payload_string_(CALLER result, (tc_Isolette_Data_Model_On_Off_Payload) this); return;
    case Ttc_Isolette_Data_Model_PhysicalTemp: tc_Isolette_Data_Model_PhysicalTemp_string_(CALLER result, (tc_Isolette_Data_Model_PhysicalTemp) this); return;
    case Ttc_Isolette_Data_Model_PhysicalTemp_Payload: tc_Isolette_Data_Model_PhysicalTemp_Payload_string_(CALLER result, (tc_Isolette_Data_Model_PhysicalTemp_Payload) this); return;
    case Ttc_Isolette_Data_Model_Regulator_Mode_Payload: tc_Isolette_Data_Model_Regulator_Mode_Payload_string_(CALLER result, (tc_Isolette_Data_Model_Regulator_Mode_Payload) this); return;
    case Ttc_Isolette_Data_Model_Status_Payload: tc_Isolette_Data_Model_Status_Payload_string_(CALLER result, (tc_Isolette_Data_Model_Status_Payload) this); return;
    case Ttc_Isolette_Data_Model_Temp: tc_Isolette_Data_Model_Temp_string_(CALLER result, (tc_Isolette_Data_Model_Temp) this); return;
    case Ttc_Isolette_Data_Model_TempWstatus: tc_Isolette_Data_Model_TempWstatus_string_(CALLER result, (tc_Isolette_Data_Model_TempWstatus) this); return;
    case Ttc_Isolette_Data_Model_TempWstatus_Payload: tc_Isolette_Data_Model_TempWstatus_Payload_string_(CALLER result, (tc_Isolette_Data_Model_TempWstatus_Payload) this); return;
    case Ttc_Isolette_Data_Model_Temp_Payload: tc_Isolette_Data_Model_Temp_Payload_string_(CALLER result, (tc_Isolette_Data_Model_Temp_Payload) this); return;
    case Ttc_Isolette_Data_Model_ValueStatus_Payload: tc_Isolette_Data_Model_ValueStatus_Payload_string_(CALLER result, (tc_Isolette_Data_Model_ValueStatus_Payload) this); return;
    case Ttc_Isolette_Environment_Air_Interaction: tc_Isolette_Environment_Air_Interaction_string_(CALLER result, (tc_Isolette_Environment_Air_Interaction) this); return;
    case Ttc_Isolette_Environment_Air_Interaction_Payload: tc_Isolette_Environment_Air_Interaction_Payload_string_(CALLER result, (tc_Isolette_Environment_Air_Interaction_Payload) this); return;
    case Ttc_Isolette_Environment_Heat: tc_Isolette_Environment_Heat_string_(CALLER result, (tc_Isolette_Environment_Heat) this); return;
    case Ttc_Isolette_Environment_Heat_Payload: tc_Isolette_Environment_Heat_Payload_string_(CALLER result, (tc_Isolette_Environment_Heat_Payload) this); return;
    case Ttc_Isolette_Environment_Interface_Interaction: tc_Isolette_Environment_Interface_Interaction_string_(CALLER result, (tc_Isolette_Environment_Interface_Interaction) this); return;
    case Ttc_Isolette_Environment_Interface_Interaction_Payload: tc_Isolette_Environment_Interface_Interaction_Payload_string_(CALLER result, (tc_Isolette_Environment_Interface_Interaction_Payload) this); return;
    case Ttc_TempControlMixed_FanAck_Payload: tc_TempControlMixed_FanAck_Payload_string_(CALLER result, (tc_TempControlMixed_FanAck_Payload) this); return;
    case Ttc_TempControlMixed_FanCmd_Payload: tc_TempControlMixed_FanCmd_Payload_string_(CALLER result, (tc_TempControlMixed_FanCmd_Payload) this); return;
    case Ttc_TempControlMixed_SetPoint: tc_TempControlMixed_SetPoint_string_(CALLER result, (tc_TempControlMixed_SetPoint) this); return;
    case Ttc_TempControlMixed_SetPoint_Payload: tc_TempControlMixed_SetPoint_Payload_string_(CALLER result, (tc_TempControlMixed_SetPoint_Payload) this); return;
    case Ttc_TempControlMixed_TempUnit_Payload: tc_TempControlMixed_TempUnit_Payload_string_(CALLER result, (tc_TempControlMixed_TempUnit_Payload) this); return;
    case Ttc_TempControlMixed_Temperature: tc_TempControlMixed_Temperature_string_(CALLER result, (tc_TempControlMixed_Temperature) this); return;
    case Ttc_TempControlMixed_Temperature_Payload: tc_TempControlMixed_Temperature_Payload_string_(CALLER result, (tc_TempControlMixed_Temperature_Payload) this); return;
    case Ttc_TempControlMixedSeL4CAmKES_FanAck_Payload: tc_TempControlMixedSeL4CAmKES_FanAck_Payload_string_(CALLER result, (tc_TempControlMixedSeL4CAmKES_FanAck_Payload) this); return;
    case Ttc_TempControlMixedSeL4CAmKES_FanCmd_Payload: tc_TempControlMixedSeL4CAmKES_FanCmd_Payload_string_(CALLER result, (tc_TempControlMixedSeL4CAmKES_FanCmd_Payload) this); return;
    case Ttc_TempControlMixedSeL4CAmKES_SetPoint: tc_TempControlMixedSeL4CAmKES_SetPoint_string_(CALLER result, (tc_TempControlMixedSeL4CAmKES_SetPoint) this); return;
    case Ttc_TempControlMixedSeL4CAmKES_SetPoint_Payload: tc_TempControlMixedSeL4CAmKES_SetPoint_Payload_string_(CALLER result, (tc_TempControlMixedSeL4CAmKES_SetPoint_Payload) this); return;
    case Ttc_TempControlMixedSeL4CAmKES_TempSensor_Initialization_Api: tc_TempControlMixedSeL4CAmKES_TempSensor_Initialization_Api_string_(CALLER result, (tc_TempControlMixedSeL4CAmKES_TempSensor_Initialization_Api) this); return;
    case Ttc_TempControlMixedSeL4CAmKES_TempSensor_Operational_Api: tc_TempControlMixedSeL4CAmKES_TempSensor_Operational_Api_string_(CALLER result, (tc_TempControlMixedSeL4CAmKES_TempSensor_Operational_Api) this); return;
    case Ttc_TempControlMixedSeL4CAmKES_TempSensor_tsp_tst_Bridge: tc_TempControlMixedSeL4CAmKES_TempSensor_tsp_tst_Bridge_string_(CALLER result, (tc_TempControlMixedSeL4CAmKES_TempSensor_tsp_tst_Bridge) this); return;
    case Ttc_TempControlMixedSeL4CAmKES_TempSensor_tsp_tst_Bridge_EntryPoints: tc_TempControlMixedSeL4CAmKES_TempSensor_tsp_tst_Bridge_EntryPoints_string_(CALLER result, (tc_TempControlMixedSeL4CAmKES_TempSensor_tsp_tst_Bridge_EntryPoints) this); return;
    case Ttc_TempControlMixedSeL4CAmKES_TempUnit_Payload: tc_TempControlMixedSeL4CAmKES_TempUnit_Payload_string_(CALLER result, (tc_TempControlMixedSeL4CAmKES_TempUnit_Payload) this); return;
    case Ttc_TempControlMixedSeL4CAmKES_Temperature: tc_TempControlMixedSeL4CAmKES_Temperature_string_(CALLER result, (tc_TempControlMixedSeL4CAmKES_Temperature) this); return;
    case Ttc_TempControlMixedSeL4CAmKES_Temperature_Payload: tc_TempControlMixedSeL4CAmKES_Temperature_Payload_string_(CALLER result, (tc_TempControlMixedSeL4CAmKES_Temperature_Payload) this); return;
    case Ttc_TempControlPeriodic_FanAck_Payload: tc_TempControlPeriodic_FanAck_Payload_string_(CALLER result, (tc_TempControlPeriodic_FanAck_Payload) this); return;
    case Ttc_TempControlPeriodic_FanCmd_Payload: tc_TempControlPeriodic_FanCmd_Payload_string_(CALLER result, (tc_TempControlPeriodic_FanCmd_Payload) this); return;
    case Ttc_TempControlPeriodic_SetPoint: tc_TempControlPeriodic_SetPoint_string_(CALLER result, (tc_TempControlPeriodic_SetPoint) this); return;
    case Ttc_TempControlPeriodic_SetPoint_Payload: tc_TempControlPeriodic_SetPoint_Payload_string_(CALLER result, (tc_TempControlPeriodic_SetPoint_Payload) this); return;
    case Ttc_TempControlPeriodic_TempUnit_Payload: tc_TempControlPeriodic_TempUnit_Payload_string_(CALLER result, (tc_TempControlPeriodic_TempUnit_Payload) this); return;
    case Ttc_TempControlPeriodic_Temperature: tc_TempControlPeriodic_Temperature_string_(CALLER result, (tc_TempControlPeriodic_Temperature) this); return;
    case Ttc_TempControlPeriodic_Temperature_Payload: tc_TempControlPeriodic_Temperature_Payload_string_(CALLER result, (tc_TempControlPeriodic_Temperature_Payload) this); return;
    default: fprintf(stderr, "%s: %d\n", "Unexpected TYPE: ", type); exit(1);
  }
}

