// #Sireum

package slang.TempControlMixedSeL4CAmKES

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

import org.sireum._
import slang.GumboXUtil.GumboXResult
import slang.util.{Container, Profile, UnitTestConfigurationBatch}
import slang.RandomLib
import org.sireum.Random.Impl.Xoshiro256

object Fan_fp_f_UnitTestConfiguration_Util {

  def freshRandomLib: RandomLib = {
    return RandomLib(Random.Gen64Impl(Xoshiro256.create))
  }

  val tq: String = "\"\"\""

  type DefaultComputeProfile = Fan_fp_f_Profile_P

  def defaultComputeConfig: Fan_fp_f_Compute_UnitTestConfiguration = {
    return (Fan_fp_f_Compute_UnitTestConfiguration (
      verbose = F,
      name = "Default_Compute_Config",
      description = "Default Compute Configuration",
      numTests = 100,
      numTestVectorGenRetries = 100,
      failOnUnsatPreconditions = F,
      profile = Fan_fp_f_Profile_P (
        name = "Compute_Default_Profile",
        api_fanCmd = freshRandomLib
      ),
      genReplay = (c: Container, testName: String, r: GumboXResult.Type) => Some(
       st"""Replay Unit Test:
            |  test("Replay: $testName") {
            |    val results = slang.GumboXUtil.GumboXResult.$r
            |    val json = st${tq}${slang.JSON.fromutilContainer(c, T)}${tq}.render
            |    val testVector = slang.JSON.toTempControlMixedSeL4CAmKESFan_fp_f_PreState_Container_P(json).left
            |    assert (testComputeCBV(testVector) == results)
            |  }""".render))
    )
  }
}

@record class Fan_fp_f_Compute_UnitTestConfiguration (
  var verbose: B,
  var name: String,
  var description: String,
  var numTests: Z,
  var numTestVectorGenRetries: Z,
  var failOnUnsatPreconditions: B,
  var profile: Fan_fp_f_Profile_P_Trait,
  var genReplay: (Container, String, GumboXResult.Type) => Option[String])
  extends UnitTestConfigurationBatch with Fan_fp_f_GumboX_TestHarness {

  override def test(c: Container): GumboXResult.Type = {
    return testComputeCBV(c.asInstanceOf[Fan_fp_f_PreState_Container])
  }
}
