// #Sireum

package slang.TempControlMixedSeL4CAmKES

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

import org.sireum._
import slang.GumboXUtil.GumboXResult
import slang.util.{Container, Profile, UnitTestConfigurationBatch}
import slang.RandomLib
import org.sireum.Random.Impl.Xoshiro256

object TempSensor_tsp_ts_UnitTestConfiguration_Util {

  def freshRandomLib: RandomLib = {
    return RandomLib(Random.Gen64Impl(Xoshiro256.create))
  }

  val tq: String = "\"\"\""

  type DefaultInitializeProfile = TempSensor_tsp_ts_Profile

  def defaultInitializeConfig: TempSensor_tsp_ts_Initialize_UnitTestConfiguration = {
    return (TempSensor_tsp_ts_Initialize_UnitTestConfiguration (
      verbose = F,
      name = "Default_Initialize_Config",
      description = "Default Initialize Configuration",
      numTests = 100,
      numTestVectorGenRetries = 100,
      failOnUnsatPreconditions = F,
      profile = TempSensor_tsp_ts_Profile (
        name = "Initialize_Default_Profile",
      ),
      genReplay = (c: Container, testName: String, r: GumboXResult.Type) => None())
    )
  }

  type DefaultComputeProfile = TempSensor_tsp_ts_Profile_P

  def defaultComputeConfig: TempSensor_tsp_ts_Compute_UnitTestConfiguration = {
    return (TempSensor_tsp_ts_Compute_UnitTestConfiguration (
      verbose = F,
      name = "Default_Compute_Config",
      description = "Default Compute Configuration",
      numTests = 100,
      numTestVectorGenRetries = 100,
      failOnUnsatPreconditions = F,
      profile = TempSensor_tsp_ts_Profile_P (
        name = "Compute_Default_Profile",
      ),
      genReplay = (c: Container, testName: String, r: GumboXResult.Type) => Some(
       st"""Replay Unit Test:
            |  test("Replay: $testName") {
            |    val results = slang.GumboXUtil.GumboXResult.$r
            |    val json = st${tq}${slang.JSON.fromutilContainer(c, T)}${tq}.render
            |    val testVector = slang.JSON.toTempControlMixedSeL4CAmKESTempSensor_tsp_ts_PreState_Container_P(json).left
            |    assert (testComputeCBV(testVector) == results)
            |  }""".render))
    )
  }
}

@record class TempSensor_tsp_ts_Initialize_UnitTestConfiguration (
  var verbose: B,
  var name: String,
  var description: String,
  var numTests: Z,
  var numTestVectorGenRetries: Z,
  var failOnUnsatPreconditions: B,
  var profile: TempSensor_tsp_ts_Profile_Trait,
  var genReplay: (Container, String, GumboXResult.Type) => Option[String])
  extends UnitTestConfigurationBatch with TempSensor_tsp_ts_GumboX_TestHarness {

  override def test(c: Container): GumboXResult.Type = {
    return testInitialiseCB()
  }
}

@record class TempSensor_tsp_ts_Compute_UnitTestConfiguration (
  var verbose: B,
  var name: String,
  var description: String,
  var numTests: Z,
  var numTestVectorGenRetries: Z,
  var failOnUnsatPreconditions: B,
  var profile: TempSensor_tsp_ts_Profile_P_Trait,
  var genReplay: (Container, String, GumboXResult.Type) => Option[String])
  extends UnitTestConfigurationBatch with TempSensor_tsp_ts_GumboX_TestHarness {

  override def test(c: Container): GumboXResult.Type = {
    return testComputeCBV(c.asInstanceOf[TempSensor_tsp_ts_PreState_Container])
  }
}
