// #Sireum

package slang.Isolette_Data_Model

import org.sireum._
import slang._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

object Failure_Flag {
  def example(): Isolette_Data_Model.Failure_Flag = {
    return Isolette_Data_Model.Failure_Flag(
      flag = Base_Types.Boolean_example())
  }
}

@datatype class Failure_Flag(
  val flag: B) {
}

object Failure_Flag_Payload {
  def example(): Failure_Flag_Payload = {
    return Failure_Flag_Payload(Isolette_Data_Model.Failure_Flag.example())
  }
}

@datatype class Failure_Flag_Payload(value: Isolette_Data_Model.Failure_Flag) extends art.DataContent
