// #Sireum

package slang.Isolette_Data_Model

import org.sireum._
import slang._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

object TempWstatus {
  def example(): Isolette_Data_Model.TempWstatus = {
    return Isolette_Data_Model.TempWstatus(
      degrees = Base_Types.Float_32_example(),
      status = Isolette_Data_Model.ValueStatus.byOrdinal(0).get)
  }
}

@datatype class TempWstatus(
  val degrees: F32,
  val status: Isolette_Data_Model.ValueStatus.Type) {
}

object TempWstatus_Payload {
  def example(): TempWstatus_Payload = {
    return TempWstatus_Payload(Isolette_Data_Model.TempWstatus.example())
  }
}

@datatype class TempWstatus_Payload(value: Isolette_Data_Model.TempWstatus) extends art.DataContent
