// #Sireum

package tc.TempControlPeriodic

import org.sireum._
import tc._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

object GUMBO__Library {
  @strictpure def inRange(temp: TempControlPeriodic.Temperature): Base_Types.Boolean = temp.degrees >= -40.0f &&
    temp.degrees <= 122.0f
}
