#include <all.h>

B Type__eq(void *t1, void *t2) {
  TYPE type = ((Type) t1)->type;
  if (type != ((Type) t2)->type) return F;
  switch (type) {
    case TIS_948B60: return IS_948B60__eq((IS_948B60) t1, (IS_948B60) t2);
    case TIS_D10119: return IS_D10119__eq((IS_D10119) t1, (IS_D10119) t2);
    case TIS_820232: return IS_820232__eq((IS_820232) t1, (IS_820232) t2);
    case TMBox2_37E193: return MBox2_37E193__eq((MBox2_37E193) t1, (MBox2_37E193) t2);
    case TMBox2_43CC67: return MBox2_43CC67__eq((MBox2_43CC67) t1, (MBox2_43CC67) t2);
    case TMS_83D5EB: return MS_83D5EB__eq((MS_83D5EB) t1, (MS_83D5EB) t2);
    case TNone_CFD2B0: return None_CFD2B0__eq((None_CFD2B0) t1, (None_CFD2B0) t2);
    case TNone_734370: return None_734370__eq((None_734370) t1, (None_734370) t2);
    case TNone_964667: return None_964667__eq((None_964667) t1, (None_964667) t2);
    case TNone_ED72E1: return None_ED72E1__eq((None_ED72E1) t1, (None_ED72E1) t2);
    case TNone_A70CEE: return None_A70CEE__eq((None_A70CEE) t1, (None_A70CEE) t2);
    case TNone_ACDB63: return None_ACDB63__eq((None_ACDB63) t1, (None_ACDB63) t2);
    case TNone_30CA2A: return None_30CA2A__eq((None_30CA2A) t1, (None_30CA2A) t2);
    case TNone_BB3A66: return None_BB3A66__eq((None_BB3A66) t1, (None_BB3A66) t2);
    case TNone_E88024: return None_E88024__eq((None_E88024) t1, (None_E88024) t2);
    case TNone_86BF24: return None_86BF24__eq((None_86BF24) t1, (None_86BF24) t2);
    case TNone_40E880: return None_40E880__eq((None_40E880) t1, (None_40E880) t2);
    case TSome_D29615: return Some_D29615__eq((Some_D29615) t1, (Some_D29615) t2);
    case TSome_4782C6: return Some_4782C6__eq((Some_4782C6) t1, (Some_4782C6) t2);
    case TSome_D85467: return Some_D85467__eq((Some_D85467) t1, (Some_D85467) t2);
    case TSome_2EFA7D: return Some_2EFA7D__eq((Some_2EFA7D) t1, (Some_2EFA7D) t2);
    case TSome_B391E9: return Some_B391E9__eq((Some_B391E9) t1, (Some_B391E9) t2);
    case TSome_6EABEC: return Some_6EABEC__eq((Some_6EABEC) t1, (Some_6EABEC) t2);
    case TSome_BE25AD: return Some_BE25AD__eq((Some_BE25AD) t1, (Some_BE25AD) t2);
    case TSome_0C4CF8: return Some_0C4CF8__eq((Some_0C4CF8) t1, (Some_0C4CF8) t2);
    case TSome_76E303: return Some_76E303__eq((Some_76E303) t1, (Some_76E303) t2);
    case TString: return String__eq((String) t1, (String) t2);
    case Tart_Bridge_Ports: return art_Bridge_Ports__eq((art_Bridge_Ports) t1, (art_Bridge_Ports) t2);
    case Tart_DispatchPropertyProtocol_Sporadic: return art_DispatchPropertyProtocol_Sporadic__eq((art_DispatchPropertyProtocol_Sporadic) t1, (art_DispatchPropertyProtocol_Sporadic) t2);
    case Tart_Empty: return art_Empty__eq((art_Empty) t1, (art_Empty) t2);
    case Tart_EventTriggered: return art_EventTriggered__eq((art_EventTriggered) t1, (art_EventTriggered) t2);
    case Tart_Port_9CBF18: return art_Port_9CBF18__eq((art_Port_9CBF18) t1, (art_Port_9CBF18) t2);
    case Tart_Port_AE5929: return art_Port_AE5929__eq((art_Port_AE5929) t1, (art_Port_AE5929) t2);
    case Tart_Port_70EB35: return art_Port_70EB35__eq((art_Port_70EB35) t1, (art_Port_70EB35) t2);
    case Tart_Port_846E11: return art_Port_846E11__eq((art_Port_846E11) t1, (art_Port_846E11) t2);
    case Tart_Port_890848: return art_Port_890848__eq((art_Port_890848) t1, (art_Port_890848) t2);
    case Tops_ISZOps_3974F3: return ops_ISZOps_3974F3__eq((ops_ISZOps_3974F3) t1, (ops_ISZOps_3974F3) t2);
    case Ttc_Base_Types_Boolean_Payload: return tc_Base_Types_Boolean_Payload__eq((tc_Base_Types_Boolean_Payload) t1, (tc_Base_Types_Boolean_Payload) t2);
    case Ttc_Base_Types_Character_Payload: return tc_Base_Types_Character_Payload__eq((tc_Base_Types_Character_Payload) t1, (tc_Base_Types_Character_Payload) t2);
    case Ttc_Base_Types_Float_32_Payload: return tc_Base_Types_Float_32_Payload__eq((tc_Base_Types_Float_32_Payload) t1, (tc_Base_Types_Float_32_Payload) t2);
    case Ttc_Base_Types_Float_64_Payload: return tc_Base_Types_Float_64_Payload__eq((tc_Base_Types_Float_64_Payload) t1, (tc_Base_Types_Float_64_Payload) t2);
    case Ttc_Base_Types_Float_Payload: return tc_Base_Types_Float_Payload__eq((tc_Base_Types_Float_Payload) t1, (tc_Base_Types_Float_Payload) t2);
    case Ttc_Base_Types_Integer_16_Payload: return tc_Base_Types_Integer_16_Payload__eq((tc_Base_Types_Integer_16_Payload) t1, (tc_Base_Types_Integer_16_Payload) t2);
    case Ttc_Base_Types_Integer_32_Payload: return tc_Base_Types_Integer_32_Payload__eq((tc_Base_Types_Integer_32_Payload) t1, (tc_Base_Types_Integer_32_Payload) t2);
    case Ttc_Base_Types_Integer_64_Payload: return tc_Base_Types_Integer_64_Payload__eq((tc_Base_Types_Integer_64_Payload) t1, (tc_Base_Types_Integer_64_Payload) t2);
    case Ttc_Base_Types_Integer_8_Payload: return tc_Base_Types_Integer_8_Payload__eq((tc_Base_Types_Integer_8_Payload) t1, (tc_Base_Types_Integer_8_Payload) t2);
    case Ttc_Base_Types_Integer_Payload: return tc_Base_Types_Integer_Payload__eq((tc_Base_Types_Integer_Payload) t1, (tc_Base_Types_Integer_Payload) t2);
    case Ttc_Base_Types_String_Payload: return tc_Base_Types_String_Payload__eq((tc_Base_Types_String_Payload) t1, (tc_Base_Types_String_Payload) t2);
    case Ttc_Base_Types_Unsigned_16_Payload: return tc_Base_Types_Unsigned_16_Payload__eq((tc_Base_Types_Unsigned_16_Payload) t1, (tc_Base_Types_Unsigned_16_Payload) t2);
    case Ttc_Base_Types_Unsigned_32_Payload: return tc_Base_Types_Unsigned_32_Payload__eq((tc_Base_Types_Unsigned_32_Payload) t1, (tc_Base_Types_Unsigned_32_Payload) t2);
    case Ttc_Base_Types_Unsigned_64_Payload: return tc_Base_Types_Unsigned_64_Payload__eq((tc_Base_Types_Unsigned_64_Payload) t1, (tc_Base_Types_Unsigned_64_Payload) t2);
    case Ttc_Base_Types_Unsigned_8_Payload: return tc_Base_Types_Unsigned_8_Payload__eq((tc_Base_Types_Unsigned_8_Payload) t1, (tc_Base_Types_Unsigned_8_Payload) t2);
    case Ttc_TempControlMixedSeL4CAmKES_FanAck_Payload: return tc_TempControlMixedSeL4CAmKES_FanAck_Payload__eq((tc_TempControlMixedSeL4CAmKES_FanAck_Payload) t1, (tc_TempControlMixedSeL4CAmKES_FanAck_Payload) t2);
    case Ttc_TempControlMixedSeL4CAmKES_FanCmd_Payload: return tc_TempControlMixedSeL4CAmKES_FanCmd_Payload__eq((tc_TempControlMixedSeL4CAmKES_FanCmd_Payload) t1, (tc_TempControlMixedSeL4CAmKES_FanCmd_Payload) t2);
    case Ttc_TempControlMixedSeL4CAmKES_SetPoint: return tc_TempControlMixedSeL4CAmKES_SetPoint__eq((tc_TempControlMixedSeL4CAmKES_SetPoint) t1, (tc_TempControlMixedSeL4CAmKES_SetPoint) t2);
    case Ttc_TempControlMixedSeL4CAmKES_SetPoint_Payload: return tc_TempControlMixedSeL4CAmKES_SetPoint_Payload__eq((tc_TempControlMixedSeL4CAmKES_SetPoint_Payload) t1, (tc_TempControlMixedSeL4CAmKES_SetPoint_Payload) t2);
    case Ttc_TempControlMixedSeL4CAmKES_TempControl_Initialization_Api: return tc_TempControlMixedSeL4CAmKES_TempControl_Initialization_Api__eq((tc_TempControlMixedSeL4CAmKES_TempControl_Initialization_Api) t1, (tc_TempControlMixedSeL4CAmKES_TempControl_Initialization_Api) t2);
    case Ttc_TempControlMixedSeL4CAmKES_TempControl_Operational_Api: return tc_TempControlMixedSeL4CAmKES_TempControl_Operational_Api__eq((tc_TempControlMixedSeL4CAmKES_TempControl_Operational_Api) t1, (tc_TempControlMixedSeL4CAmKES_TempControl_Operational_Api) t2);
    case Ttc_TempControlMixedSeL4CAmKES_TempControl_tcp_tct_Bridge: return tc_TempControlMixedSeL4CAmKES_TempControl_tcp_tct_Bridge__eq((tc_TempControlMixedSeL4CAmKES_TempControl_tcp_tct_Bridge) t1, (tc_TempControlMixedSeL4CAmKES_TempControl_tcp_tct_Bridge) t2);
    case Ttc_TempControlMixedSeL4CAmKES_TempControl_tcp_tct_Bridge_EntryPoints: return tc_TempControlMixedSeL4CAmKES_TempControl_tcp_tct_Bridge_EntryPoints__eq((tc_TempControlMixedSeL4CAmKES_TempControl_tcp_tct_Bridge_EntryPoints) t1, (tc_TempControlMixedSeL4CAmKES_TempControl_tcp_tct_Bridge_EntryPoints) t2);
    case Ttc_TempControlMixedSeL4CAmKES_TempUnit_Payload: return tc_TempControlMixedSeL4CAmKES_TempUnit_Payload__eq((tc_TempControlMixedSeL4CAmKES_TempUnit_Payload) t1, (tc_TempControlMixedSeL4CAmKES_TempUnit_Payload) t2);
    case Ttc_TempControlMixedSeL4CAmKES_Temperature: return tc_TempControlMixedSeL4CAmKES_Temperature__eq((tc_TempControlMixedSeL4CAmKES_Temperature) t1, (tc_TempControlMixedSeL4CAmKES_Temperature) t2);
    case Ttc_TempControlMixedSeL4CAmKES_Temperature_Payload: return tc_TempControlMixedSeL4CAmKES_Temperature_Payload__eq((tc_TempControlMixedSeL4CAmKES_Temperature_Payload) t1, (tc_TempControlMixedSeL4CAmKES_Temperature_Payload) t2);
    default: fprintf(stderr, "%s: %d\n", "Unexpected TYPE: ", type); exit(1);
  }
}

B Type__equiv(void *t1, void *t2) {
  TYPE type = ((Type) t1)->type;
  if (type != ((Type) t2)->type) return F;
  switch (type) {
    case TIS_948B60: return IS_948B60__equiv((IS_948B60) t1, (IS_948B60) t2);
    case TIS_D10119: return IS_D10119__equiv((IS_D10119) t1, (IS_D10119) t2);
    case TIS_820232: return IS_820232__equiv((IS_820232) t1, (IS_820232) t2);
    case TMBox2_37E193: return MBox2_37E193__equiv((MBox2_37E193) t1, (MBox2_37E193) t2);
    case TMBox2_43CC67: return MBox2_43CC67__equiv((MBox2_43CC67) t1, (MBox2_43CC67) t2);
    case TMS_83D5EB: return MS_83D5EB__equiv((MS_83D5EB) t1, (MS_83D5EB) t2);
    case TNone_CFD2B0: return None_CFD2B0__equiv((None_CFD2B0) t1, (None_CFD2B0) t2);
    case TNone_734370: return None_734370__equiv((None_734370) t1, (None_734370) t2);
    case TNone_964667: return None_964667__equiv((None_964667) t1, (None_964667) t2);
    case TNone_ED72E1: return None_ED72E1__equiv((None_ED72E1) t1, (None_ED72E1) t2);
    case TNone_A70CEE: return None_A70CEE__equiv((None_A70CEE) t1, (None_A70CEE) t2);
    case TNone_ACDB63: return None_ACDB63__equiv((None_ACDB63) t1, (None_ACDB63) t2);
    case TNone_30CA2A: return None_30CA2A__equiv((None_30CA2A) t1, (None_30CA2A) t2);
    case TNone_BB3A66: return None_BB3A66__equiv((None_BB3A66) t1, (None_BB3A66) t2);
    case TNone_E88024: return None_E88024__equiv((None_E88024) t1, (None_E88024) t2);
    case TNone_86BF24: return None_86BF24__equiv((None_86BF24) t1, (None_86BF24) t2);
    case TNone_40E880: return None_40E880__equiv((None_40E880) t1, (None_40E880) t2);
    case TSome_D29615: return Some_D29615__equiv((Some_D29615) t1, (Some_D29615) t2);
    case TSome_4782C6: return Some_4782C6__equiv((Some_4782C6) t1, (Some_4782C6) t2);
    case TSome_D85467: return Some_D85467__equiv((Some_D85467) t1, (Some_D85467) t2);
    case TSome_2EFA7D: return Some_2EFA7D__equiv((Some_2EFA7D) t1, (Some_2EFA7D) t2);
    case TSome_B391E9: return Some_B391E9__equiv((Some_B391E9) t1, (Some_B391E9) t2);
    case TSome_6EABEC: return Some_6EABEC__equiv((Some_6EABEC) t1, (Some_6EABEC) t2);
    case TSome_BE25AD: return Some_BE25AD__equiv((Some_BE25AD) t1, (Some_BE25AD) t2);
    case TSome_0C4CF8: return Some_0C4CF8__equiv((Some_0C4CF8) t1, (Some_0C4CF8) t2);
    case TSome_76E303: return Some_76E303__equiv((Some_76E303) t1, (Some_76E303) t2);
    case TString: return String__equiv((String) t1, (String) t2);
    case Tart_Bridge_Ports: return art_Bridge_Ports__equiv((art_Bridge_Ports) t1, (art_Bridge_Ports) t2);
    case Tart_DispatchPropertyProtocol_Sporadic: return art_DispatchPropertyProtocol_Sporadic__equiv((art_DispatchPropertyProtocol_Sporadic) t1, (art_DispatchPropertyProtocol_Sporadic) t2);
    case Tart_Empty: return art_Empty__equiv((art_Empty) t1, (art_Empty) t2);
    case Tart_EventTriggered: return art_EventTriggered__equiv((art_EventTriggered) t1, (art_EventTriggered) t2);
    case Tart_Port_9CBF18: return art_Port_9CBF18__equiv((art_Port_9CBF18) t1, (art_Port_9CBF18) t2);
    case Tart_Port_AE5929: return art_Port_AE5929__equiv((art_Port_AE5929) t1, (art_Port_AE5929) t2);
    case Tart_Port_70EB35: return art_Port_70EB35__equiv((art_Port_70EB35) t1, (art_Port_70EB35) t2);
    case Tart_Port_846E11: return art_Port_846E11__equiv((art_Port_846E11) t1, (art_Port_846E11) t2);
    case Tart_Port_890848: return art_Port_890848__equiv((art_Port_890848) t1, (art_Port_890848) t2);
    case Tops_ISZOps_3974F3: return ops_ISZOps_3974F3__equiv((ops_ISZOps_3974F3) t1, (ops_ISZOps_3974F3) t2);
    case Ttc_Base_Types_Boolean_Payload: return tc_Base_Types_Boolean_Payload__equiv((tc_Base_Types_Boolean_Payload) t1, (tc_Base_Types_Boolean_Payload) t2);
    case Ttc_Base_Types_Character_Payload: return tc_Base_Types_Character_Payload__equiv((tc_Base_Types_Character_Payload) t1, (tc_Base_Types_Character_Payload) t2);
    case Ttc_Base_Types_Float_32_Payload: return tc_Base_Types_Float_32_Payload__equiv((tc_Base_Types_Float_32_Payload) t1, (tc_Base_Types_Float_32_Payload) t2);
    case Ttc_Base_Types_Float_64_Payload: return tc_Base_Types_Float_64_Payload__equiv((tc_Base_Types_Float_64_Payload) t1, (tc_Base_Types_Float_64_Payload) t2);
    case Ttc_Base_Types_Float_Payload: return tc_Base_Types_Float_Payload__equiv((tc_Base_Types_Float_Payload) t1, (tc_Base_Types_Float_Payload) t2);
    case Ttc_Base_Types_Integer_16_Payload: return tc_Base_Types_Integer_16_Payload__equiv((tc_Base_Types_Integer_16_Payload) t1, (tc_Base_Types_Integer_16_Payload) t2);
    case Ttc_Base_Types_Integer_32_Payload: return tc_Base_Types_Integer_32_Payload__equiv((tc_Base_Types_Integer_32_Payload) t1, (tc_Base_Types_Integer_32_Payload) t2);
    case Ttc_Base_Types_Integer_64_Payload: return tc_Base_Types_Integer_64_Payload__equiv((tc_Base_Types_Integer_64_Payload) t1, (tc_Base_Types_Integer_64_Payload) t2);
    case Ttc_Base_Types_Integer_8_Payload: return tc_Base_Types_Integer_8_Payload__equiv((tc_Base_Types_Integer_8_Payload) t1, (tc_Base_Types_Integer_8_Payload) t2);
    case Ttc_Base_Types_Integer_Payload: return tc_Base_Types_Integer_Payload__equiv((tc_Base_Types_Integer_Payload) t1, (tc_Base_Types_Integer_Payload) t2);
    case Ttc_Base_Types_String_Payload: return tc_Base_Types_String_Payload__equiv((tc_Base_Types_String_Payload) t1, (tc_Base_Types_String_Payload) t2);
    case Ttc_Base_Types_Unsigned_16_Payload: return tc_Base_Types_Unsigned_16_Payload__equiv((tc_Base_Types_Unsigned_16_Payload) t1, (tc_Base_Types_Unsigned_16_Payload) t2);
    case Ttc_Base_Types_Unsigned_32_Payload: return tc_Base_Types_Unsigned_32_Payload__equiv((tc_Base_Types_Unsigned_32_Payload) t1, (tc_Base_Types_Unsigned_32_Payload) t2);
    case Ttc_Base_Types_Unsigned_64_Payload: return tc_Base_Types_Unsigned_64_Payload__equiv((tc_Base_Types_Unsigned_64_Payload) t1, (tc_Base_Types_Unsigned_64_Payload) t2);
    case Ttc_Base_Types_Unsigned_8_Payload: return tc_Base_Types_Unsigned_8_Payload__equiv((tc_Base_Types_Unsigned_8_Payload) t1, (tc_Base_Types_Unsigned_8_Payload) t2);
    case Ttc_TempControlMixedSeL4CAmKES_FanAck_Payload: return tc_TempControlMixedSeL4CAmKES_FanAck_Payload__equiv((tc_TempControlMixedSeL4CAmKES_FanAck_Payload) t1, (tc_TempControlMixedSeL4CAmKES_FanAck_Payload) t2);
    case Ttc_TempControlMixedSeL4CAmKES_FanCmd_Payload: return tc_TempControlMixedSeL4CAmKES_FanCmd_Payload__equiv((tc_TempControlMixedSeL4CAmKES_FanCmd_Payload) t1, (tc_TempControlMixedSeL4CAmKES_FanCmd_Payload) t2);
    case Ttc_TempControlMixedSeL4CAmKES_SetPoint: return tc_TempControlMixedSeL4CAmKES_SetPoint__equiv((tc_TempControlMixedSeL4CAmKES_SetPoint) t1, (tc_TempControlMixedSeL4CAmKES_SetPoint) t2);
    case Ttc_TempControlMixedSeL4CAmKES_SetPoint_Payload: return tc_TempControlMixedSeL4CAmKES_SetPoint_Payload__equiv((tc_TempControlMixedSeL4CAmKES_SetPoint_Payload) t1, (tc_TempControlMixedSeL4CAmKES_SetPoint_Payload) t2);
    case Ttc_TempControlMixedSeL4CAmKES_TempControl_Initialization_Api: return tc_TempControlMixedSeL4CAmKES_TempControl_Initialization_Api__equiv((tc_TempControlMixedSeL4CAmKES_TempControl_Initialization_Api) t1, (tc_TempControlMixedSeL4CAmKES_TempControl_Initialization_Api) t2);
    case Ttc_TempControlMixedSeL4CAmKES_TempControl_Operational_Api: return tc_TempControlMixedSeL4CAmKES_TempControl_Operational_Api__equiv((tc_TempControlMixedSeL4CAmKES_TempControl_Operational_Api) t1, (tc_TempControlMixedSeL4CAmKES_TempControl_Operational_Api) t2);
    case Ttc_TempControlMixedSeL4CAmKES_TempControl_tcp_tct_Bridge: return tc_TempControlMixedSeL4CAmKES_TempControl_tcp_tct_Bridge__equiv((tc_TempControlMixedSeL4CAmKES_TempControl_tcp_tct_Bridge) t1, (tc_TempControlMixedSeL4CAmKES_TempControl_tcp_tct_Bridge) t2);
    case Ttc_TempControlMixedSeL4CAmKES_TempControl_tcp_tct_Bridge_EntryPoints: return tc_TempControlMixedSeL4CAmKES_TempControl_tcp_tct_Bridge_EntryPoints__equiv((tc_TempControlMixedSeL4CAmKES_TempControl_tcp_tct_Bridge_EntryPoints) t1, (tc_TempControlMixedSeL4CAmKES_TempControl_tcp_tct_Bridge_EntryPoints) t2);
    case Ttc_TempControlMixedSeL4CAmKES_TempUnit_Payload: return tc_TempControlMixedSeL4CAmKES_TempUnit_Payload__equiv((tc_TempControlMixedSeL4CAmKES_TempUnit_Payload) t1, (tc_TempControlMixedSeL4CAmKES_TempUnit_Payload) t2);
    case Ttc_TempControlMixedSeL4CAmKES_Temperature: return tc_TempControlMixedSeL4CAmKES_Temperature__equiv((tc_TempControlMixedSeL4CAmKES_Temperature) t1, (tc_TempControlMixedSeL4CAmKES_Temperature) t2);
    case Ttc_TempControlMixedSeL4CAmKES_Temperature_Payload: return tc_TempControlMixedSeL4CAmKES_Temperature_Payload__equiv((tc_TempControlMixedSeL4CAmKES_Temperature_Payload) t1, (tc_TempControlMixedSeL4CAmKES_Temperature_Payload) t2);
    default: fprintf(stderr, "%s: %d\n", "Unexpected TYPE: ", type); exit(1);
  }
}

void Type_cprint(void *this, B isOut) {
  #ifndef SIREUM_NO_PRINT
  TYPE type = ((Type) this)->type;
  switch (type) {
    case TIS_948B60: IS_948B60_cprint((IS_948B60) this, isOut); return;
    case TIS_D10119: IS_D10119_cprint((IS_D10119) this, isOut); return;
    case TIS_820232: IS_820232_cprint((IS_820232) this, isOut); return;
    case TMBox2_37E193: MBox2_37E193_cprint((MBox2_37E193) this, isOut); return;
    case TMBox2_43CC67: MBox2_43CC67_cprint((MBox2_43CC67) this, isOut); return;
    case TMS_83D5EB: MS_83D5EB_cprint((MS_83D5EB) this, isOut); return;
    case TNone_CFD2B0: None_CFD2B0_cprint((None_CFD2B0) this, isOut); return;
    case TNone_734370: None_734370_cprint((None_734370) this, isOut); return;
    case TNone_964667: None_964667_cprint((None_964667) this, isOut); return;
    case TNone_ED72E1: None_ED72E1_cprint((None_ED72E1) this, isOut); return;
    case TNone_A70CEE: None_A70CEE_cprint((None_A70CEE) this, isOut); return;
    case TNone_ACDB63: None_ACDB63_cprint((None_ACDB63) this, isOut); return;
    case TNone_30CA2A: None_30CA2A_cprint((None_30CA2A) this, isOut); return;
    case TNone_BB3A66: None_BB3A66_cprint((None_BB3A66) this, isOut); return;
    case TNone_E88024: None_E88024_cprint((None_E88024) this, isOut); return;
    case TNone_86BF24: None_86BF24_cprint((None_86BF24) this, isOut); return;
    case TNone_40E880: None_40E880_cprint((None_40E880) this, isOut); return;
    case TSome_D29615: Some_D29615_cprint((Some_D29615) this, isOut); return;
    case TSome_4782C6: Some_4782C6_cprint((Some_4782C6) this, isOut); return;
    case TSome_D85467: Some_D85467_cprint((Some_D85467) this, isOut); return;
    case TSome_2EFA7D: Some_2EFA7D_cprint((Some_2EFA7D) this, isOut); return;
    case TSome_B391E9: Some_B391E9_cprint((Some_B391E9) this, isOut); return;
    case TSome_6EABEC: Some_6EABEC_cprint((Some_6EABEC) this, isOut); return;
    case TSome_BE25AD: Some_BE25AD_cprint((Some_BE25AD) this, isOut); return;
    case TSome_0C4CF8: Some_0C4CF8_cprint((Some_0C4CF8) this, isOut); return;
    case TSome_76E303: Some_76E303_cprint((Some_76E303) this, isOut); return;
    case TString: String_cprint((String) this, isOut); return;
    case Tart_Bridge_Ports: art_Bridge_Ports_cprint((art_Bridge_Ports) this, isOut); return;
    case Tart_DispatchPropertyProtocol_Sporadic: art_DispatchPropertyProtocol_Sporadic_cprint((art_DispatchPropertyProtocol_Sporadic) this, isOut); return;
    case Tart_Empty: art_Empty_cprint((art_Empty) this, isOut); return;
    case Tart_EventTriggered: art_EventTriggered_cprint((art_EventTriggered) this, isOut); return;
    case Tart_Port_9CBF18: art_Port_9CBF18_cprint((art_Port_9CBF18) this, isOut); return;
    case Tart_Port_AE5929: art_Port_AE5929_cprint((art_Port_AE5929) this, isOut); return;
    case Tart_Port_70EB35: art_Port_70EB35_cprint((art_Port_70EB35) this, isOut); return;
    case Tart_Port_846E11: art_Port_846E11_cprint((art_Port_846E11) this, isOut); return;
    case Tart_Port_890848: art_Port_890848_cprint((art_Port_890848) this, isOut); return;
    case Tops_ISZOps_3974F3: ops_ISZOps_3974F3_cprint((ops_ISZOps_3974F3) this, isOut); return;
    case Ttc_Base_Types_Boolean_Payload: tc_Base_Types_Boolean_Payload_cprint((tc_Base_Types_Boolean_Payload) this, isOut); return;
    case Ttc_Base_Types_Character_Payload: tc_Base_Types_Character_Payload_cprint((tc_Base_Types_Character_Payload) this, isOut); return;
    case Ttc_Base_Types_Float_32_Payload: tc_Base_Types_Float_32_Payload_cprint((tc_Base_Types_Float_32_Payload) this, isOut); return;
    case Ttc_Base_Types_Float_64_Payload: tc_Base_Types_Float_64_Payload_cprint((tc_Base_Types_Float_64_Payload) this, isOut); return;
    case Ttc_Base_Types_Float_Payload: tc_Base_Types_Float_Payload_cprint((tc_Base_Types_Float_Payload) this, isOut); return;
    case Ttc_Base_Types_Integer_16_Payload: tc_Base_Types_Integer_16_Payload_cprint((tc_Base_Types_Integer_16_Payload) this, isOut); return;
    case Ttc_Base_Types_Integer_32_Payload: tc_Base_Types_Integer_32_Payload_cprint((tc_Base_Types_Integer_32_Payload) this, isOut); return;
    case Ttc_Base_Types_Integer_64_Payload: tc_Base_Types_Integer_64_Payload_cprint((tc_Base_Types_Integer_64_Payload) this, isOut); return;
    case Ttc_Base_Types_Integer_8_Payload: tc_Base_Types_Integer_8_Payload_cprint((tc_Base_Types_Integer_8_Payload) this, isOut); return;
    case Ttc_Base_Types_Integer_Payload: tc_Base_Types_Integer_Payload_cprint((tc_Base_Types_Integer_Payload) this, isOut); return;
    case Ttc_Base_Types_String_Payload: tc_Base_Types_String_Payload_cprint((tc_Base_Types_String_Payload) this, isOut); return;
    case Ttc_Base_Types_Unsigned_16_Payload: tc_Base_Types_Unsigned_16_Payload_cprint((tc_Base_Types_Unsigned_16_Payload) this, isOut); return;
    case Ttc_Base_Types_Unsigned_32_Payload: tc_Base_Types_Unsigned_32_Payload_cprint((tc_Base_Types_Unsigned_32_Payload) this, isOut); return;
    case Ttc_Base_Types_Unsigned_64_Payload: tc_Base_Types_Unsigned_64_Payload_cprint((tc_Base_Types_Unsigned_64_Payload) this, isOut); return;
    case Ttc_Base_Types_Unsigned_8_Payload: tc_Base_Types_Unsigned_8_Payload_cprint((tc_Base_Types_Unsigned_8_Payload) this, isOut); return;
    case Ttc_TempControlMixedSeL4CAmKES_FanAck_Payload: tc_TempControlMixedSeL4CAmKES_FanAck_Payload_cprint((tc_TempControlMixedSeL4CAmKES_FanAck_Payload) this, isOut); return;
    case Ttc_TempControlMixedSeL4CAmKES_FanCmd_Payload: tc_TempControlMixedSeL4CAmKES_FanCmd_Payload_cprint((tc_TempControlMixedSeL4CAmKES_FanCmd_Payload) this, isOut); return;
    case Ttc_TempControlMixedSeL4CAmKES_SetPoint: tc_TempControlMixedSeL4CAmKES_SetPoint_cprint((tc_TempControlMixedSeL4CAmKES_SetPoint) this, isOut); return;
    case Ttc_TempControlMixedSeL4CAmKES_SetPoint_Payload: tc_TempControlMixedSeL4CAmKES_SetPoint_Payload_cprint((tc_TempControlMixedSeL4CAmKES_SetPoint_Payload) this, isOut); return;
    case Ttc_TempControlMixedSeL4CAmKES_TempControl_Initialization_Api: tc_TempControlMixedSeL4CAmKES_TempControl_Initialization_Api_cprint((tc_TempControlMixedSeL4CAmKES_TempControl_Initialization_Api) this, isOut); return;
    case Ttc_TempControlMixedSeL4CAmKES_TempControl_Operational_Api: tc_TempControlMixedSeL4CAmKES_TempControl_Operational_Api_cprint((tc_TempControlMixedSeL4CAmKES_TempControl_Operational_Api) this, isOut); return;
    case Ttc_TempControlMixedSeL4CAmKES_TempControl_tcp_tct_Bridge: tc_TempControlMixedSeL4CAmKES_TempControl_tcp_tct_Bridge_cprint((tc_TempControlMixedSeL4CAmKES_TempControl_tcp_tct_Bridge) this, isOut); return;
    case Ttc_TempControlMixedSeL4CAmKES_TempControl_tcp_tct_Bridge_EntryPoints: tc_TempControlMixedSeL4CAmKES_TempControl_tcp_tct_Bridge_EntryPoints_cprint((tc_TempControlMixedSeL4CAmKES_TempControl_tcp_tct_Bridge_EntryPoints) this, isOut); return;
    case Ttc_TempControlMixedSeL4CAmKES_TempUnit_Payload: tc_TempControlMixedSeL4CAmKES_TempUnit_Payload_cprint((tc_TempControlMixedSeL4CAmKES_TempUnit_Payload) this, isOut); return;
    case Ttc_TempControlMixedSeL4CAmKES_Temperature: tc_TempControlMixedSeL4CAmKES_Temperature_cprint((tc_TempControlMixedSeL4CAmKES_Temperature) this, isOut); return;
    case Ttc_TempControlMixedSeL4CAmKES_Temperature_Payload: tc_TempControlMixedSeL4CAmKES_Temperature_Payload_cprint((tc_TempControlMixedSeL4CAmKES_Temperature_Payload) this, isOut); return;
    default: fprintf(stderr, "%s: %d\n", "Unexpected TYPE: ", type); exit(1);
  }
  #endif
}

void Type_string_(STACK_FRAME String result, void *this) {
  TYPE type = ((Type) this)->type;
  switch (type) {
    case TIS_948B60: IS_948B60_string_(CALLER result, (IS_948B60) this); return;
    case TIS_D10119: IS_D10119_string_(CALLER result, (IS_D10119) this); return;
    case TIS_820232: IS_820232_string_(CALLER result, (IS_820232) this); return;
    case TMBox2_37E193: MBox2_37E193_string_(CALLER result, (MBox2_37E193) this); return;
    case TMBox2_43CC67: MBox2_43CC67_string_(CALLER result, (MBox2_43CC67) this); return;
    case TMS_83D5EB: MS_83D5EB_string_(CALLER result, (MS_83D5EB) this); return;
    case TNone_CFD2B0: None_CFD2B0_string_(CALLER result, (None_CFD2B0) this); return;
    case TNone_734370: None_734370_string_(CALLER result, (None_734370) this); return;
    case TNone_964667: None_964667_string_(CALLER result, (None_964667) this); return;
    case TNone_ED72E1: None_ED72E1_string_(CALLER result, (None_ED72E1) this); return;
    case TNone_A70CEE: None_A70CEE_string_(CALLER result, (None_A70CEE) this); return;
    case TNone_ACDB63: None_ACDB63_string_(CALLER result, (None_ACDB63) this); return;
    case TNone_30CA2A: None_30CA2A_string_(CALLER result, (None_30CA2A) this); return;
    case TNone_BB3A66: None_BB3A66_string_(CALLER result, (None_BB3A66) this); return;
    case TNone_E88024: None_E88024_string_(CALLER result, (None_E88024) this); return;
    case TNone_86BF24: None_86BF24_string_(CALLER result, (None_86BF24) this); return;
    case TNone_40E880: None_40E880_string_(CALLER result, (None_40E880) this); return;
    case TSome_D29615: Some_D29615_string_(CALLER result, (Some_D29615) this); return;
    case TSome_4782C6: Some_4782C6_string_(CALLER result, (Some_4782C6) this); return;
    case TSome_D85467: Some_D85467_string_(CALLER result, (Some_D85467) this); return;
    case TSome_2EFA7D: Some_2EFA7D_string_(CALLER result, (Some_2EFA7D) this); return;
    case TSome_B391E9: Some_B391E9_string_(CALLER result, (Some_B391E9) this); return;
    case TSome_6EABEC: Some_6EABEC_string_(CALLER result, (Some_6EABEC) this); return;
    case TSome_BE25AD: Some_BE25AD_string_(CALLER result, (Some_BE25AD) this); return;
    case TSome_0C4CF8: Some_0C4CF8_string_(CALLER result, (Some_0C4CF8) this); return;
    case TSome_76E303: Some_76E303_string_(CALLER result, (Some_76E303) this); return;
    case TString: String_string_(CALLER result, (String) this); return;
    case Tart_Bridge_Ports: art_Bridge_Ports_string_(CALLER result, (art_Bridge_Ports) this); return;
    case Tart_DispatchPropertyProtocol_Sporadic: art_DispatchPropertyProtocol_Sporadic_string_(CALLER result, (art_DispatchPropertyProtocol_Sporadic) this); return;
    case Tart_Empty: art_Empty_string_(CALLER result, (art_Empty) this); return;
    case Tart_EventTriggered: art_EventTriggered_string_(CALLER result, (art_EventTriggered) this); return;
    case Tart_Port_9CBF18: art_Port_9CBF18_string_(CALLER result, (art_Port_9CBF18) this); return;
    case Tart_Port_AE5929: art_Port_AE5929_string_(CALLER result, (art_Port_AE5929) this); return;
    case Tart_Port_70EB35: art_Port_70EB35_string_(CALLER result, (art_Port_70EB35) this); return;
    case Tart_Port_846E11: art_Port_846E11_string_(CALLER result, (art_Port_846E11) this); return;
    case Tart_Port_890848: art_Port_890848_string_(CALLER result, (art_Port_890848) this); return;
    case Tops_ISZOps_3974F3: ops_ISZOps_3974F3_string_(CALLER result, (ops_ISZOps_3974F3) this); return;
    case Ttc_Base_Types_Boolean_Payload: tc_Base_Types_Boolean_Payload_string_(CALLER result, (tc_Base_Types_Boolean_Payload) this); return;
    case Ttc_Base_Types_Character_Payload: tc_Base_Types_Character_Payload_string_(CALLER result, (tc_Base_Types_Character_Payload) this); return;
    case Ttc_Base_Types_Float_32_Payload: tc_Base_Types_Float_32_Payload_string_(CALLER result, (tc_Base_Types_Float_32_Payload) this); return;
    case Ttc_Base_Types_Float_64_Payload: tc_Base_Types_Float_64_Payload_string_(CALLER result, (tc_Base_Types_Float_64_Payload) this); return;
    case Ttc_Base_Types_Float_Payload: tc_Base_Types_Float_Payload_string_(CALLER result, (tc_Base_Types_Float_Payload) this); return;
    case Ttc_Base_Types_Integer_16_Payload: tc_Base_Types_Integer_16_Payload_string_(CALLER result, (tc_Base_Types_Integer_16_Payload) this); return;
    case Ttc_Base_Types_Integer_32_Payload: tc_Base_Types_Integer_32_Payload_string_(CALLER result, (tc_Base_Types_Integer_32_Payload) this); return;
    case Ttc_Base_Types_Integer_64_Payload: tc_Base_Types_Integer_64_Payload_string_(CALLER result, (tc_Base_Types_Integer_64_Payload) this); return;
    case Ttc_Base_Types_Integer_8_Payload: tc_Base_Types_Integer_8_Payload_string_(CALLER result, (tc_Base_Types_Integer_8_Payload) this); return;
    case Ttc_Base_Types_Integer_Payload: tc_Base_Types_Integer_Payload_string_(CALLER result, (tc_Base_Types_Integer_Payload) this); return;
    case Ttc_Base_Types_String_Payload: tc_Base_Types_String_Payload_string_(CALLER result, (tc_Base_Types_String_Payload) this); return;
    case Ttc_Base_Types_Unsigned_16_Payload: tc_Base_Types_Unsigned_16_Payload_string_(CALLER result, (tc_Base_Types_Unsigned_16_Payload) this); return;
    case Ttc_Base_Types_Unsigned_32_Payload: tc_Base_Types_Unsigned_32_Payload_string_(CALLER result, (tc_Base_Types_Unsigned_32_Payload) this); return;
    case Ttc_Base_Types_Unsigned_64_Payload: tc_Base_Types_Unsigned_64_Payload_string_(CALLER result, (tc_Base_Types_Unsigned_64_Payload) this); return;
    case Ttc_Base_Types_Unsigned_8_Payload: tc_Base_Types_Unsigned_8_Payload_string_(CALLER result, (tc_Base_Types_Unsigned_8_Payload) this); return;
    case Ttc_TempControlMixedSeL4CAmKES_FanAck_Payload: tc_TempControlMixedSeL4CAmKES_FanAck_Payload_string_(CALLER result, (tc_TempControlMixedSeL4CAmKES_FanAck_Payload) this); return;
    case Ttc_TempControlMixedSeL4CAmKES_FanCmd_Payload: tc_TempControlMixedSeL4CAmKES_FanCmd_Payload_string_(CALLER result, (tc_TempControlMixedSeL4CAmKES_FanCmd_Payload) this); return;
    case Ttc_TempControlMixedSeL4CAmKES_SetPoint: tc_TempControlMixedSeL4CAmKES_SetPoint_string_(CALLER result, (tc_TempControlMixedSeL4CAmKES_SetPoint) this); return;
    case Ttc_TempControlMixedSeL4CAmKES_SetPoint_Payload: tc_TempControlMixedSeL4CAmKES_SetPoint_Payload_string_(CALLER result, (tc_TempControlMixedSeL4CAmKES_SetPoint_Payload) this); return;
    case Ttc_TempControlMixedSeL4CAmKES_TempControl_Initialization_Api: tc_TempControlMixedSeL4CAmKES_TempControl_Initialization_Api_string_(CALLER result, (tc_TempControlMixedSeL4CAmKES_TempControl_Initialization_Api) this); return;
    case Ttc_TempControlMixedSeL4CAmKES_TempControl_Operational_Api: tc_TempControlMixedSeL4CAmKES_TempControl_Operational_Api_string_(CALLER result, (tc_TempControlMixedSeL4CAmKES_TempControl_Operational_Api) this); return;
    case Ttc_TempControlMixedSeL4CAmKES_TempControl_tcp_tct_Bridge: tc_TempControlMixedSeL4CAmKES_TempControl_tcp_tct_Bridge_string_(CALLER result, (tc_TempControlMixedSeL4CAmKES_TempControl_tcp_tct_Bridge) this); return;
    case Ttc_TempControlMixedSeL4CAmKES_TempControl_tcp_tct_Bridge_EntryPoints: tc_TempControlMixedSeL4CAmKES_TempControl_tcp_tct_Bridge_EntryPoints_string_(CALLER result, (tc_TempControlMixedSeL4CAmKES_TempControl_tcp_tct_Bridge_EntryPoints) this); return;
    case Ttc_TempControlMixedSeL4CAmKES_TempUnit_Payload: tc_TempControlMixedSeL4CAmKES_TempUnit_Payload_string_(CALLER result, (tc_TempControlMixedSeL4CAmKES_TempUnit_Payload) this); return;
    case Ttc_TempControlMixedSeL4CAmKES_Temperature: tc_TempControlMixedSeL4CAmKES_Temperature_string_(CALLER result, (tc_TempControlMixedSeL4CAmKES_Temperature) this); return;
    case Ttc_TempControlMixedSeL4CAmKES_Temperature_Payload: tc_TempControlMixedSeL4CAmKES_Temperature_Payload_string_(CALLER result, (tc_TempControlMixedSeL4CAmKES_Temperature_Payload) this); return;
    default: fprintf(stderr, "%s: %d\n", "Unexpected TYPE: ", type); exit(1);
  }
}

