// #Sireum

package tc.Isolette_Data_Model

import org.sireum._
import tc._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

object Temp {
  def example(): Isolette_Data_Model.Temp = {
    return Isolette_Data_Model.Temp(
      degrees = Base_Types.Float_32_example())
  }
}

@datatype class Temp(
  val degrees: F32) {
}

object Temp_Payload {
  def example(): Temp_Payload = {
    return Temp_Payload(Isolette_Data_Model.Temp.example())
  }
}

@datatype class Temp_Payload(value: Isolette_Data_Model.Temp) extends art.DataContent
