// #Sireum

package tc.TempControlMixedSeL4CAmKES

import org.sireum._
import tc._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

@enum object TempUnit {
  "Fahrenheit"
}

object TempUnit_Payload {
  def example(): TempUnit_Payload = {
    return TempUnit_Payload(TempControlMixedSeL4CAmKES.TempUnit.byOrdinal(0).get)
  }
}

@datatype class TempUnit_Payload(value: TempControlMixedSeL4CAmKES.TempUnit.Type) extends art.DataContent
