// #Sireum

package slang_rm.Isolette_Data_Model

import org.sireum._
import slang_rm._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

object PhysicalTemp {
  def example(): Isolette_Data_Model.PhysicalTemp = {
    return Isolette_Data_Model.PhysicalTemp(
      degrees = Base_Types.Float_32_example())
  }
}

@datatype class PhysicalTemp(
  val degrees: F32) {
}

object PhysicalTemp_Payload {
  def example(): PhysicalTemp_Payload = {
    return PhysicalTemp_Payload(Isolette_Data_Model.PhysicalTemp.example())
  }
}

@datatype class PhysicalTemp_Payload(value: Isolette_Data_Model.PhysicalTemp) extends art.DataContent
