#ifndef TEMPCONTROL_TCP_TCT_ADAPTER_H
#define TEMPCONTROL_TCP_TCT_ADAPTER_H

#include <all.h>

Unit tc_TempControlMixedSeL4CAmKES_TempControl_tcp_tct_adapter_initialiseArchitecture(STACK_FRAME_ONLY);

Unit tc_TempControlMixedSeL4CAmKES_TempControl_tcp_tct_adapter_initialiseEntryPoint(STACK_FRAME_ONLY);

Unit tc_TempControlMixedSeL4CAmKES_TempControl_tcp_tct_adapter_computeEntryPoint(STACK_FRAME_ONLY);

art_Bridge_EntryPoints tc_TempControlMixedSeL4CAmKES_TempControl_tcp_tct_adapter_entryPoints(STACK_FRAME_ONLY);

#endif
