// #Sireum

package slang.TempControlMixedSeL4CAmKES

import org.sireum._
import art._
import slang._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

object TempControl_tcp_tc_EntryPoint_Companion {

  var preStateContainer_wL: Option[TempControl_tcp_tc_PreState_Container_PS] = None()

  def pre_initialise(): Unit = {
    // assume/require contracts cannot refer to incoming ports or
    // state variables so nothing to do here
  }

  def post_initialise(): Unit = {
    // block the component while its post-state values are retrieved
    val postStateContainer_wL =
      TempControl_tcp_tc_PostState_Container_PS(
        currentFanState = slang.TempControlMixedSeL4CAmKES.TempControl_tcp_tc.currentFanState,
        currentSetPoint = slang.TempControlMixedSeL4CAmKES.TempControl_tcp_tc.currentSetPoint,
        latestTemp = slang.TempControlMixedSeL4CAmKES.TempControl_tcp_tc.latestTemp,
        api_fanCmd = 
          if (Art.observeOutPortVariable(Arch.TempControlSystem_Instance_tcp_tc.operational_api.fanCmd_Id).nonEmpty)
            Some(Art.observeOutPortVariable(Arch.TempControlSystem_Instance_tcp_tc.operational_api.fanCmd_Id).get.asInstanceOf[TempControlMixedSeL4CAmKES.FanCmd_Payload].value)
          else None())

    // the rest can now be performed via a different thread
    slang.runtimemonitor.RuntimeMonitor.observeInitialisePostState(Arch.TempControlSystem_Instance_tcp_tc.id, slang.runtimemonitor.ObservationKind.TempControlSystem_Instance_tcp_tc_postInit, postStateContainer_wL)
  }

  def pre_compute(): Unit = {
    // block the component while its pre-state values are retrieved
    preStateContainer_wL = Some(
      TempControl_tcp_tc_PreState_Container_PS(
        In_currentFanState = slang.TempControlMixedSeL4CAmKES.TempControl_tcp_tc.currentFanState, 
        In_currentSetPoint = slang.TempControlMixedSeL4CAmKES.TempControl_tcp_tc.currentSetPoint, 
        In_latestTemp = slang.TempControlMixedSeL4CAmKES.TempControl_tcp_tc.latestTemp, 
        api_tempChanged = Art.observeInPortVariable(Arch.TempControlSystem_Instance_tcp_tc.operational_api.tempChanged_Id).asInstanceOf[Option[art.Empty]], 
        api_fanAck = 
          if (Art.observeInPortVariable(Arch.TempControlSystem_Instance_tcp_tc.operational_api.fanAck_Id).nonEmpty)
            Some(Art.observeInPortVariable(Arch.TempControlSystem_Instance_tcp_tc.operational_api.fanAck_Id).get.asInstanceOf[TempControlMixedSeL4CAmKES.FanAck_Payload].value)
          else None(), 
        api_setPoint = 
          if (Art.observeInPortVariable(Arch.TempControlSystem_Instance_tcp_tc.operational_api.setPoint_Id).nonEmpty)
            Some(Art.observeInPortVariable(Arch.TempControlSystem_Instance_tcp_tc.operational_api.setPoint_Id).get.asInstanceOf[TempControlMixedSeL4CAmKES.SetPoint_Payload].value)
          else None(), 
        api_currentTemp = Art.observeInPortVariable(Arch.TempControlSystem_Instance_tcp_tc.operational_api.currentTemp_Id).get.asInstanceOf[TempControlMixedSeL4CAmKES.Temperature_Payload].value))

    // the rest can now be performed via a different thread
    slang.runtimemonitor.RuntimeMonitor.observeComputePreState(Arch.TempControlSystem_Instance_tcp_tc.id, slang.runtimemonitor.ObservationKind.TempControlSystem_Instance_tcp_tc_preCompute, preStateContainer_wL.asInstanceOf[Option[art.DataContent]])
  }

  def post_compute(): Unit = {
    // block the component while its post-state values are retrieved
    val postStateContainer_wL =
      TempControl_tcp_tc_PostState_Container_PS(
        currentFanState = slang.TempControlMixedSeL4CAmKES.TempControl_tcp_tc.currentFanState,
        currentSetPoint = slang.TempControlMixedSeL4CAmKES.TempControl_tcp_tc.currentSetPoint,
        latestTemp = slang.TempControlMixedSeL4CAmKES.TempControl_tcp_tc.latestTemp,
        api_fanCmd = 
          if (Art.observeOutPortVariable(Arch.TempControlSystem_Instance_tcp_tc.operational_api.fanCmd_Id).nonEmpty)
            Some(Art.observeOutPortVariable(Arch.TempControlSystem_Instance_tcp_tc.operational_api.fanCmd_Id).get.asInstanceOf[TempControlMixedSeL4CAmKES.FanCmd_Payload].value)
          else None())

    // the rest can now be performed via a different thread
    slang.runtimemonitor.RuntimeMonitor.observeComputePrePostState(Arch.TempControlSystem_Instance_tcp_tc.id, slang.runtimemonitor.ObservationKind.TempControlSystem_Instance_tcp_tc_postCompute, preStateContainer_wL.asInstanceOf[Option[art.DataContent]], postStateContainer_wL)
  }
}