// #Sireum

package slang.TempControlMixedSeL4CAmKES

import org.sireum._
import slang._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

@enum object FanAck {
  "Ok"
  "Error"
}

object FanAck_Payload {
  def example(): FanAck_Payload = {
    return FanAck_Payload(TempControlMixedSeL4CAmKES.FanAck.byOrdinal(0).get)
  }
}

@datatype class FanAck_Payload(value: TempControlMixedSeL4CAmKES.FanAck.Type) extends art.DataContent
