// #Sireum

package tc

import org.sireum._
import art._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

object ArtNix {

  val maxPortIds: Z = IPCPorts.Main.toZ + 1
  val timeTriggered: TimeTriggered = TimeTriggered()
  val noData: Option[DataContent] = None()
  val data: MS[Art.PortId, Option[DataContent]] = MS.create(maxPortIds, noData)
  val connection: MS[Art.PortId, IS[Art.ConnectionId, (Art.PortId, Art.PortId)]] = {
    // mapping from src ports to pairs holding the destination app port ids and component port ids
    val r = MS.create[Art.PortId, IS[Art.ConnectionId, (Art.PortId, Art.PortId)]](maxPortIds, IS())

    r(Arch.TempControlSystem_Instance_tsp_tst.currentTemp.id) = IS(
      (IPCPorts.TempControl_tcp_tct_App, Arch.TempControlSystem_Instance_tcp_tct.currentTemp.id)
    )
    r(Arch.TempControlSystem_Instance_tsp_tst.tempChanged.id) = IS(
      (IPCPorts.TempControl_tcp_tct_App, Arch.TempControlSystem_Instance_tcp_tct.tempChanged.id)
    )
    r(Arch.TempControlSystem_Instance_tcp_tct.fanCmd.id) = IS(
      (IPCPorts.Fan_fp_ft_App, Arch.TempControlSystem_Instance_fp_ft.fanCmd.id)
    )
    r(Arch.TempControlSystem_Instance_fp_ft.fanAck.id) = IS(
      (IPCPorts.TempControl_tcp_tct_App, Arch.TempControlSystem_Instance_tcp_tct.fanAck.id)
    )

    r
  }
  val eventInPorts: MS[Art.PortId, Art.PortId] = MS[Art.PortId, Art.PortId] (
    Arch.TempControlSystem_Instance_tcp_tct.tempChanged.id,
    Arch.TempControlSystem_Instance_tcp_tct.fanAck.id,
    Arch.TempControlSystem_Instance_tcp_tct.setPoint.id,
    Arch.TempControlSystem_Instance_fp_ft.fanCmd.id
  )
  var frozen: MS[Art.PortId, Option[DataContent]] = MS.create(maxPortIds, noData)
  var outgoing: MS[Art.PortId, Option[DataContent]] = MS.create(maxPortIds, noData)
  var isTimeDispatch: B = F

  def updateData(port: Art.PortId, d: DataContent): Unit = {
    data(port) = Some(d)
  }

  def timeDispatch(): Unit = {
    isTimeDispatch = T
  }

  def eventDispatch(): Unit = {
    isTimeDispatch = F
  }

  def dispatchStatus(bridgeId: Art.BridgeId): DispatchStatus = {
    if (isTimeDispatch) {
      return timeTriggered
    } else {
      var r = ISZ[Art.PortId]()
      for (i <- eventInPorts if data(i).nonEmpty) {
        r = r :+ i
      }
      return EventTriggered(r)
    }
  }

  def receiveInput(eventPortIds: ISZ[Art.PortId], dataPortIds: ISZ[Art.PortId]): Unit = {
    frozen = data
    for (i <- eventPortIds) {
      data(i) = noData
    }
  }

  def putValue(portId: Art.PortId, data: DataContent): Unit = {
    outgoing(portId) = Some(data)
  }

  def getValue(portId: Art.PortId): Option[DataContent] = {
    return frozen(portId)
  }

  def sendOutput(eventPortIds: ISZ[Art.PortId], dataPortIds: ISZ[Art.PortId]): Unit = {
    for (p <- dataPortIds) {
      outgoing(p) match {
        case Some(d) =>
          outgoing(p) = noData
          for(e <- connection(p)){
            PlatformComm.sendAsync(e._1, e._2, d)
          }
        case _ =>
      }
    }

    for (p <- eventPortIds) {
      outgoing(p) match {
        case Some(d) =>
          outgoing(p) = noData
          for(e <- connection(p)){
            PlatformComm.sendAsync(e._1, e._2, d)
          }
        case _ =>
      }
    }
  }

  def logInfo(title: String, msg: String): Unit = {
    print(title)
    print(": ")
    println(msg)
  }

  def logError(title: String, msg: String): Unit = {
    eprint(title)
    eprint(": ")
    eprintln(msg)
  }

  def logDebug(title: String, msg: String): Unit = {
    print(title)
    print(": ")
    println(msg)
  }

  def time(): Art.Time = {
    return Process.time()
  }

  def run(): Unit = {}

  def tearDownSystemState(): Unit = {}

  def setUpSystemState(): Unit = {}

  def initializePhase(): Unit = {}

  def computePhase(): Unit = {}

  def finalizePhase(): Unit = {}
}
