// #Sireum

package tc

import org.sireum._
import art._
import art.Art.PortId._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

object IPCPorts {
  val TempSensor_tsp_tst_App: Art.PortId = Art.PortId.fromZ(9)
  val TempControl_tcp_tct_App: Art.PortId = Art.PortId.fromZ(10)
  val Fan_fp_ft_App: Art.PortId = Art.PortId.fromZ(11)
  val Main: Art.PortId = Art.PortId.fromZ(12)

  def emptyReceiveOut: MBox2[Art.PortId, DataContent] = {
    return MBox2(portId"0", art.Empty())
  }

  def emptyReceiveAsyncOut: MBox2[Art.PortId, Option[DataContent]] = {
    return MBox2(portId"0", None())
  }
}
