// #Sireum

package tc

import org.sireum._
import art._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

object LegacyDemo extends App {
  def main(args: ISZ[String]): Z = {

    val seed: Z = if (args.size == z"1") {
      val n = Z(args(0)).get
      if (n <= z"0") 1 else n
    } else {
      1
    }

    PlatformComm.initialise(seed, None())

    val empty = art.Empty()

    PlatformComm.sendAsync(IPCPorts.TempSensor_tsp_tst_App, IPCPorts.TempSensor_tsp_tst_App, empty)
    PlatformComm.sendAsync(IPCPorts.TempControl_tcp_tct_App, IPCPorts.TempControl_tcp_tct_App, empty)
    PlatformComm.sendAsync(IPCPorts.Fan_fp_ft_App, IPCPorts.Fan_fp_ft_App, empty)

    PlatformComm.finalise()
    return 0
  }
}
