// #Sireum

package tc

import org.sireum._
import art._
import art.Art.PortId._
import art.scheduling.nop.NopScheduler

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

object TempControl_tcp_tct_App extends App {

  val entryPoints: Bridge.EntryPoints = Arch.TempControlSystem_Instance_tcp_tct.entryPoints
  val appPortId: Art.PortId = IPCPorts.TempControl_tcp_tct_App
  val appPortIdOpt: Option[Art.PortId] = Some(appPortId)

  // incoming ports
  val currentTempPortId: Art.PortId = Arch.TempControlSystem_Instance_tcp_tct.currentTemp.id
  val currentTempPortIdOpt: Option[Art.PortId] = Some(currentTempPortId)
  val tempChangedPortId: Art.PortId = Arch.TempControlSystem_Instance_tcp_tct.tempChanged.id
  val tempChangedPortIdOpt: Option[Art.PortId] = Some(tempChangedPortId)
  val fanAckPortId: Art.PortId = Arch.TempControlSystem_Instance_tcp_tct.fanAck.id
  val fanAckPortIdOpt: Option[Art.PortId] = Some(fanAckPortId)
  val setPointPortId: Art.PortId = Arch.TempControlSystem_Instance_tcp_tct.setPoint.id
  val setPointPortIdOpt: Option[Art.PortId] = Some(setPointPortId)

  def initialiseArchitecture(seed: Z): Unit = {
    PlatformComm.initialise(seed, appPortIdOpt)
    PlatformComm.initialise(seed, currentTempPortIdOpt)
    PlatformComm.initialise(seed, tempChangedPortIdOpt)
    PlatformComm.initialise(seed, fanAckPortIdOpt)
    PlatformComm.initialise(seed, setPointPortIdOpt)

    Art.run(Arch.ad, NopScheduler())
  }

  def initialise(): Unit = {
    entryPoints.initialise()
  }

  def compute(): Unit = {
    var dispatch = F

    {
      val out = IPCPorts.emptyReceiveAsyncOut
      PlatformComm.receiveAsync(currentTempPortIdOpt, out)
      out.value2 match {
        case Some(v: TempControlMixedSeL4CAmKES.Temperature_Payload) => ArtNix.updateData(currentTempPortId, v); dispatch = F
        case Some(v) => halt(s"Unexpected payload on port currentTemp.  Expecting something of type TempControlMixedSeL4CAmKES.Temperature_Payload but received ${v}")
        case None() => // do nothing
      }
    }
    {
      val out = IPCPorts.emptyReceiveAsyncOut
      PlatformComm.receiveAsync(tempChangedPortIdOpt, out)
      out.value2 match {
        case Some(v: art.Empty) => ArtNix.updateData(tempChangedPortId, v); dispatch = T
        case Some(v) => halt(s"Unexpected payload on port tempChanged.  Expecting something of type art.Empty but received ${v}")
        case None() => // do nothing
      }
    }
    {
      val out = IPCPorts.emptyReceiveAsyncOut
      PlatformComm.receiveAsync(fanAckPortIdOpt, out)
      out.value2 match {
        case Some(v: TempControlMixedSeL4CAmKES.FanAck_Payload) => ArtNix.updateData(fanAckPortId, v); dispatch = T
        case Some(v) => halt(s"Unexpected payload on port fanAck.  Expecting something of type TempControlMixedSeL4CAmKES.FanAck_Payload but received ${v}")
        case None() => // do nothing
      }
    }
    {
      val out = IPCPorts.emptyReceiveAsyncOut
      PlatformComm.receiveAsync(setPointPortIdOpt, out)
      out.value2 match {
        case Some(v: TempControlMixedSeL4CAmKES.SetPoint_Payload) => ArtNix.updateData(setPointPortId, v); dispatch = T
        case Some(v) => halt(s"Unexpected payload on port setPoint.  Expecting something of type TempControlMixedSeL4CAmKES.SetPoint_Payload but received ${v}")
        case None() => // do nothing
      }
    }
    if (dispatch) {
      entryPoints.compute()
      tc.Process.sleep(1000)
    } else {
      tc.Process.sleep(10)
    }
  }

  def finalise(): Unit = {
    entryPoints.finalise()
  }

  def main(args: ISZ[String]): Z = {

    val seed: Z = if (args.size == z"1") {
      val n = Z(args(0)).get
      if (n == z"0") 1 else n
    } else {
      1
    }

    initialiseArchitecture(seed)

    PlatformComm.receive(appPortIdOpt, IPCPorts.emptyReceiveOut) // pause after setting up component

    initialise()

    PlatformComm.receive(appPortIdOpt, IPCPorts.emptyReceiveOut) // pause after component init

    println("TempControl_tcp_tct_App starting ...")

    ArtNix.eventDispatch()

    var terminated = F
    while (!terminated) {
      val out = IPCPorts.emptyReceiveAsyncOut
      PlatformComm.receiveAsync(appPortIdOpt, out)
      if (out.value2.isEmpty) {
        compute()
      } else {
        terminated = T
      }
    }
    exit()

    touch()

    return 0
  }

  def touch(): Unit = {
    if(F) {
      TranspilerToucher.touch()

      // add types used in Platform.receive and Platform.receiveAsync
      val mbox2Boolean_Payload: MBox2[Art.PortId, DataContent] = MBox2(portId"0", Base_Types.Boolean_Payload(T))
      val mbox2OptionDataContent: MBox2[Art.PortId, Option[DataContent]] = MBox2(portId"0", None())

      // touch each payload/type in case some are only used as a field in a record
      def printDataContent(a: art.DataContent): Unit = { println(s"${a}") }

      printDataContent(Base_Types.Boolean_Payload(Base_Types.Boolean_example()))
      printDataContent(Base_Types.Integer_Payload(Base_Types.Integer_example()))
      printDataContent(Base_Types.Integer_8_Payload(Base_Types.Integer_8_example()))
      printDataContent(Base_Types.Integer_16_Payload(Base_Types.Integer_16_example()))
      printDataContent(Base_Types.Integer_32_Payload(Base_Types.Integer_32_example()))
      printDataContent(Base_Types.Integer_64_Payload(Base_Types.Integer_64_example()))
      printDataContent(Base_Types.Unsigned_8_Payload(Base_Types.Unsigned_8_example()))
      printDataContent(Base_Types.Unsigned_16_Payload(Base_Types.Unsigned_16_example()))
      printDataContent(Base_Types.Unsigned_32_Payload(Base_Types.Unsigned_32_example()))
      printDataContent(Base_Types.Unsigned_64_Payload(Base_Types.Unsigned_64_example()))
      printDataContent(Base_Types.Float_Payload(Base_Types.Float_example()))
      printDataContent(Base_Types.Float_32_Payload(Base_Types.Float_32_example()))
      printDataContent(Base_Types.Float_64_Payload(Base_Types.Float_64_example()))
      printDataContent(Base_Types.Character_Payload(Base_Types.Character_example()))
      printDataContent(Base_Types.String_Payload(Base_Types.String_example()))
      printDataContent(TempControlMixedSeL4CAmKES.Temperature_Payload(TempControlMixedSeL4CAmKES.Temperature.example()))
      printDataContent(TempControlMixedSeL4CAmKES.TempUnit_Payload(TempControlMixedSeL4CAmKES.TempUnit.byOrdinal(0).get))
      printDataContent(TempControlMixedSeL4CAmKES.SetPoint_Payload(TempControlMixedSeL4CAmKES.SetPoint.example()))
      printDataContent(TempControlMixedSeL4CAmKES.FanCmd_Payload(TempControlMixedSeL4CAmKES.FanCmd.byOrdinal(0).get))
      printDataContent(TempControlMixedSeL4CAmKES.FanAck_Payload(TempControlMixedSeL4CAmKES.FanAck.byOrdinal(0).get))
      printDataContent(Isolette_Environment.Heat_Payload(Isolette_Environment.Heat.example()))
      printDataContent(Isolette_Environment.Interface_Interaction_Payload(Isolette_Environment.Interface_Interaction.example()))
      printDataContent(Isolette_Environment.Air_Interaction_Payload(Isolette_Environment.Air_Interaction.example()))
      printDataContent(TempControlMixed.Temperature_Payload(TempControlMixed.Temperature.example()))
      printDataContent(TempControlMixed.SetPoint_Payload(TempControlMixed.SetPoint.example()))
      printDataContent(TempControlMixed.TempUnit_Payload(TempControlMixed.TempUnit.byOrdinal(0).get))
      printDataContent(TempControlMixed.FanCmd_Payload(TempControlMixed.FanCmd.byOrdinal(0).get))
      printDataContent(TempControlMixed.FanAck_Payload(TempControlMixed.FanAck.byOrdinal(0).get))
      printDataContent(TempControlPeriodic.Temperature_Payload(TempControlPeriodic.Temperature.example()))
      printDataContent(TempControlPeriodic.SetPoint_Payload(TempControlPeriodic.SetPoint.example()))
      printDataContent(TempControlPeriodic.TempUnit_Payload(TempControlPeriodic.TempUnit.byOrdinal(0).get))
      printDataContent(TempControlPeriodic.FanCmd_Payload(TempControlPeriodic.FanCmd.byOrdinal(0).get))
      printDataContent(TempControlPeriodic.FanAck_Payload(TempControlPeriodic.FanAck.byOrdinal(0).get))
      printDataContent(Isolette_Data_Model.PhysicalTemp_Payload(Isolette_Data_Model.PhysicalTemp.example()))
      printDataContent(Isolette_Data_Model.TempWstatus_Payload(Isolette_Data_Model.TempWstatus.example()))
      printDataContent(Isolette_Data_Model.Temp_Payload(Isolette_Data_Model.Temp.example()))
      printDataContent(Isolette_Data_Model.On_Off_Payload(Isolette_Data_Model.On_Off.byOrdinal(0).get))
      printDataContent(Isolette_Data_Model.Failure_Flag_Payload(Isolette_Data_Model.Failure_Flag.example()))
      printDataContent(Isolette_Data_Model.ValueStatus_Payload(Isolette_Data_Model.ValueStatus.byOrdinal(0).get))
      printDataContent(Isolette_Data_Model.Status_Payload(Isolette_Data_Model.Status.byOrdinal(0).get))
      printDataContent(Isolette_Data_Model.Regulator_Mode_Payload(Isolette_Data_Model.Regulator_Mode.byOrdinal(0).get))
      printDataContent(Isolette_Data_Model.Monitor_Mode_Payload(Isolette_Data_Model.Monitor_Mode.byOrdinal(0).get))
      printDataContent(art.Empty())

      tc.TempControlMixedSeL4CAmKES.TempControl_tcp_tct_Bridge.c_initialization_api.get.logInfo("")
      tc.TempControlMixedSeL4CAmKES.TempControl_tcp_tct_Bridge.c_initialization_api.get.logDebug("")
      tc.TempControlMixedSeL4CAmKES.TempControl_tcp_tct_Bridge.c_initialization_api.get.logError("")
      tc.TempControlMixedSeL4CAmKES.TempControl_tcp_tct_Bridge.c_operational_api.get.logInfo("")
      tc.TempControlMixedSeL4CAmKES.TempControl_tcp_tct_Bridge.c_operational_api.get.logDebug("")
      tc.TempControlMixedSeL4CAmKES.TempControl_tcp_tct_Bridge.c_operational_api.get.logError("")
      val apiUsage_currentTemp: Option[TempControlMixedSeL4CAmKES.Temperature] = tc.TempControlMixedSeL4CAmKES.TempControl_tcp_tct_Bridge.c_operational_api.get.get_currentTemp()
      val apiUsage_tempChanged: Option[art.Empty] = tc.TempControlMixedSeL4CAmKES.TempControl_tcp_tct_Bridge.c_operational_api.get.get_tempChanged()
      val apiUsage_fanAck: Option[TempControlMixedSeL4CAmKES.FanAck.Type] = tc.TempControlMixedSeL4CAmKES.TempControl_tcp_tct_Bridge.c_operational_api.get.get_fanAck()
      val apiUsage_setPoint: Option[TempControlMixedSeL4CAmKES.SetPoint] = tc.TempControlMixedSeL4CAmKES.TempControl_tcp_tct_Bridge.c_operational_api.get.get_setPoint()
      tc.TempControlMixedSeL4CAmKES.TempControl_tcp_tct_Bridge.c_initialization_api.get.put_fanCmd(TempControlMixedSeL4CAmKES.FanCmd.byOrdinal(0).get)
      tc.TempControlMixedSeL4CAmKES.TempControl_tcp_tct_Bridge.c_operational_api.get.put_fanCmd(TempControlMixedSeL4CAmKES.FanCmd.byOrdinal(0).get)
    }
  }

  def exit(): Unit = {
    finalise()
    PlatformComm.finalise()
  }

  override def atExit(): Unit = {
    exit()
  }
}