// #Sireum

package tc.runtimemonitor

import org.sireum._
import tc._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

@enum object ObservationKind {
  "TempControlSystem_Instance_tsp_tst_postInit"
  "TempControlSystem_Instance_tsp_tst_preCompute"
  "TempControlSystem_Instance_tsp_tst_postCompute"
  "TempControlSystem_Instance_tcp_tct_postInit"
  "TempControlSystem_Instance_tcp_tct_preCompute"
  "TempControlSystem_Instance_tcp_tct_postCompute"
  "TempControlSystem_Instance_fp_ft_postInit"
  "TempControlSystem_Instance_fp_ft_preCompute"
  "TempControlSystem_Instance_fp_ft_postCompute"
}
