// #Sireum

package slang_rm.runtimemonitor

import org.sireum._
import slang_rm._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

object GumboXDispatcher {
  def checkContract(observationKind: ObservationKind.Type, preContainer: Option[art.DataContent], postContainer: Option[art.DataContent]): B = {
    observationKind match {
      case slang_rm.runtimemonitor.ObservationKind.TempControlSystem_Instance_tsp_ts_postInit =>
        val result: B = slang_rm.TempControlMixedSeL4CAmKES.TempSensor_tsp_ts_GumboX.inititialize_IEP_Post_Container(postContainer.get.asInstanceOf[slang_rm.TempControlMixedSeL4CAmKES.TempSensor_tsp_ts_PostState_Container_PS])
        //println(s"ts.initialise: Post-condition: ${if (result) "" else "un"}satisfied")
        return result
      case slang_rm.runtimemonitor.ObservationKind.TempControlSystem_Instance_tsp_ts_preCompute =>
        // checking the pre-state values of ts's compute entrypoint is not required
        return T
      case slang_rm.runtimemonitor.ObservationKind.TempControlSystem_Instance_tsp_ts_postCompute =>
        val result: B = slang_rm.TempControlMixedSeL4CAmKES.TempSensor_tsp_ts_GumboX.compute_CEP_Post_Container(preContainer.get.asInstanceOf[slang_rm.TempControlMixedSeL4CAmKES.TempSensor_tsp_ts_PreState_Container_PS], postContainer.get.asInstanceOf[slang_rm.TempControlMixedSeL4CAmKES.TempSensor_tsp_ts_PostState_Container_PS])
        //println(s"ts.timeTriggered: Post-condition: ${if (result) "" else "un"}satisfied")
        return result

      case slang_rm.runtimemonitor.ObservationKind.TempControlSystem_Instance_tcp_tc_postInit =>
        val result: B = slang_rm.TempControlMixedSeL4CAmKES.TempControl_tcp_tc_GumboX.inititialize_IEP_Post_Container(postContainer.get.asInstanceOf[slang_rm.TempControlMixedSeL4CAmKES.TempControl_tcp_tc_PostState_Container_PS])
        //println(s"tc.initialise: Post-condition: ${if (result) "" else "un"}satisfied")
        return result
      case slang_rm.runtimemonitor.ObservationKind.TempControlSystem_Instance_tcp_tc_preCompute =>
        val result: B = slang_rm.TempControlMixedSeL4CAmKES.TempControl_tcp_tc_GumboX.compute_CEP_Pre_Container(preContainer.get.asInstanceOf[slang_rm.TempControlMixedSeL4CAmKES.TempControl_tcp_tc_PreState_Container_PS])
        //println(s"tc.timeTriggered: Pre-condition: ${if (result) "" else "un"}satisfied")
        return result
      case slang_rm.runtimemonitor.ObservationKind.TempControlSystem_Instance_tcp_tc_postCompute =>
        val result: B = slang_rm.TempControlMixedSeL4CAmKES.TempControl_tcp_tc_GumboX.compute_CEP_Post_Container(preContainer.get.asInstanceOf[slang_rm.TempControlMixedSeL4CAmKES.TempControl_tcp_tc_PreState_Container_PS], postContainer.get.asInstanceOf[slang_rm.TempControlMixedSeL4CAmKES.TempControl_tcp_tc_PostState_Container_PS])
        //println(s"tc.timeTriggered: Post-condition: ${if (result) "" else "un"}satisfied")
        return result

      case slang_rm.runtimemonitor.ObservationKind.TempControlSystem_Instance_fp_f_postInit =>
        // checking the post-state values of f's initialise entrypoint is not required
        return T
      case slang_rm.runtimemonitor.ObservationKind.TempControlSystem_Instance_fp_f_preCompute =>
        // checking the pre-state values of f's compute entrypoint is not required
        return T
      case slang_rm.runtimemonitor.ObservationKind.TempControlSystem_Instance_fp_f_postCompute =>
        // checking the post-state values of f's compute entrypoint is not required
        return T

      case _ => halt("Infeasible")
    }
  }

  def genTestSuite(testCases: ISZ[(Z, ISZ[ST])]): Unit = {
    val tq = "\"\"\""

    val testRoot = Os.path(".") / "src" / "test" / "bridge"

    val TempSensor_tsp_ts_id = Arch.TempControlSystem_Instance_tsp_ts.id
    val TempControl_tcp_tc_id = Arch.TempControlSystem_Instance_tcp_tc.id
    val Fan_fp_f_id = Arch.TempControlSystem_Instance_fp_f.id

    def genUniqueSuiteName(path: Os.Path, prefix: String): String = {
      var i = 0
      while(true) {
        val cand = path / s"${prefix}_${i}.scala"
        if (!cand.exists) {
          return s"${prefix}_${i}"
        }
        i = i + 1
      }
      halt("Infeasible")
    }

    for (p <- testCases) {
      art.Art.BridgeId.fromZ(p._1) match {
        case TempSensor_tsp_ts_id =>
          val prefix = "TempSensor_tsp_ts_RM_TestSuite"
          val path = testRoot /+ ISZ("slang_rm","TempControlMixedSeL4CAmKES")
          val suiteName = genUniqueSuiteName(path, prefix)

          val testSuite =
            st"""package slang_rm.TempControlMixedSeL4CAmKES
                |
                |import org.sireum._
                |import slang_rm.TempControlMixedSeL4CAmKES._
                |
                |class ${suiteName} extends TempSensor_tsp_ts_GumboX_TestHarness_ScalaTest {
                |  val verbose: B = T
                |
                |  ${p._2}
                |}"""
          val filename = path / s"${suiteName}.scala"
          filename.writeOver(testSuite.render)
          println(s"Wrote: ${filename.toUri}")
        case TempControl_tcp_tc_id =>
          val prefix = "TempControl_tcp_tc_RM_TestSuite"
          val path = testRoot /+ ISZ("slang_rm","TempControlMixedSeL4CAmKES")
          val suiteName = genUniqueSuiteName(path, prefix)

          val testSuite =
            st"""package slang_rm.TempControlMixedSeL4CAmKES
                |
                |import org.sireum._
                |import slang_rm.TempControlMixedSeL4CAmKES._
                |
                |class ${suiteName} extends TempControl_tcp_tc_ScalaTest {
                |  val verbose: B = T
                |
                |  ${p._2}
                |}"""
          val filename = path / s"${suiteName}.scala"
          filename.writeOver(testSuite.render)
          println(s"Wrote: ${filename.toUri}")
        case Fan_fp_f_id =>
          val prefix = "Fan_fp_f_RM_TestSuite"
          val path = testRoot /+ ISZ("slang_rm","TempControlMixedSeL4CAmKES")
          val suiteName = genUniqueSuiteName(path, prefix)

          val testSuite =
            st"""package slang_rm.TempControlMixedSeL4CAmKES
                |
                |import org.sireum._
                |import slang_rm.TempControlMixedSeL4CAmKES._
                |
                |class ${suiteName} extends Fan_fp_f_GumboX_TestHarness_ScalaTest {
                |  val verbose: B = T
                |
                |  ${p._2}
                |}"""
          val filename = path / s"${suiteName}.scala"
          filename.writeOver(testSuite.render)
          println(s"Wrote: ${filename.toUri}")
        case x => halt(s"Infeasible bridge id: $x")
      }
    }
  }

  def genTestCase(observationKind: ObservationKind.Type, preContainer: Option[String], postContainer: Option[String], testNameSuffix: Option[String]): ST = {
    val tq = "\"\"\""
    val suffix: String =
      if (testNameSuffix.nonEmpty) testNameSuffix.get
      else ""

    observationKind match {
      case slang_rm.runtimemonitor.ObservationKind.TempControlSystem_Instance_tsp_ts_postInit =>
        return (st"""// Begin test cases for TempControlSystem_Instance_tsp_ts_postInit
                    |
                    |test(s"TempControlSystem_Instance_tsp_ts_postInit: Check Post-condition$suffix") {
                    |  val postJson: String = st${tq}${postContainer.get}${tq}.render
                    |  val postContainer = slang_rm.JSON.toTempControlMixedSeL4CAmKESTempSensor_tsp_ts_PostState_Container_PS(postJson).left
                    |  assert(slang_rm.TempControlMixedSeL4CAmKES.TempSensor_tsp_ts_GumboX.inititialize_IEP_Post_Container(postContainer))
                    |}
                    |// End test cases for TempControlSystem_Instance_tsp_ts_postInit""")
      case slang_rm.runtimemonitor.ObservationKind.TempControlSystem_Instance_tsp_ts_postCompute =>
        return (st"""// Begin test cases for TempControlSystem_Instance_tsp_ts_postCompute
                    |
                    |test(s"TempControlSystem_Instance_tsp_ts_postCompute: Check Post-condition$suffix") {
                    |  val preJson: String = st${tq}${preContainer.get}${tq}.render
                    |  val postJson: String = st${tq}${postContainer.get}${tq}.render
                    |  val preContainer = slang_rm.JSON.toTempControlMixedSeL4CAmKESTempSensor_tsp_ts_PreState_Container_PS(preJson).left
                    |  val postContainer = slang_rm.JSON.toTempControlMixedSeL4CAmKESTempSensor_tsp_ts_PostState_Container_PS(postJson).left
                    |  if (verbose) {
                    |    println("Pre-State Values:")
                    |    println(s"  $$preContainer")
                    |    println("Post-State Values:")
                    |    println(s"  $$postContainer");
                    |  }
                    |  assert(slang_rm.TempControlMixedSeL4CAmKES.TempSensor_tsp_ts_GumboX.compute_CEP_Post_Container(preContainer, postContainer))
                    |}
                    |// End test cases for TempControlSystem_Instance_tsp_ts_postCompute""")
      case slang_rm.runtimemonitor.ObservationKind.TempControlSystem_Instance_tcp_tc_postInit =>
        return (st"""// Begin test cases for TempControlSystem_Instance_tcp_tc_postInit
                    |
                    |test(s"TempControlSystem_Instance_tcp_tc_postInit: Check Post-condition$suffix") {
                    |  val postJson: String = st${tq}${postContainer.get}${tq}.render
                    |  val postContainer = slang_rm.JSON.toTempControlMixedSeL4CAmKESTempControl_tcp_tc_PostState_Container_PS(postJson).left
                    |  assert(slang_rm.TempControlMixedSeL4CAmKES.TempControl_tcp_tc_GumboX.inititialize_IEP_Post_Container(postContainer))
                    |}
                    |// End test cases for TempControlSystem_Instance_tcp_tc_postInit""")
      case slang_rm.runtimemonitor.ObservationKind.TempControlSystem_Instance_tcp_tc_preCompute =>
        return (st"""// Begin test cases for TempControlSystem_Instance_tcp_tc_preCompute
                    |
                    |test(s"TempControlSystem_Instance_tcp_tc_preCompute: Check Pre-condition$suffix") {
                    |  val preJson: String = st${tq}${preContainer.get}${tq}.render
                    |  val preContainer = slang_rm.JSON.toTempControlMixedSeL4CAmKESTempControl_tcp_tc_PreState_Container_PS(preJson).left
                    |  if (verbose) {
                    |    println("Pre-State Values:")
                    |    println(s"  $$preContainer")
                    |  }
                    |  assert(slang_rm.TempControlMixedSeL4CAmKES.TempControl_tcp_tc_GumboX.compute_CEP_Pre_Container(preContainer))
                    |}
                    |// End test cases for TempControlSystem_Instance_tcp_tc_preCompute""")
      case slang_rm.runtimemonitor.ObservationKind.TempControlSystem_Instance_tcp_tc_postCompute =>
        return (st"""// Begin test cases for TempControlSystem_Instance_tcp_tc_postCompute
                    |
                    |test(s"TempControlSystem_Instance_tcp_tc_postCompute: Check Pre-condition$suffix") {
                    |  val preJson: String = st${tq}${preContainer.get}${tq}.render
                    |  val preContainer = slang_rm.JSON.toTempControlMixedSeL4CAmKESTempControl_tcp_tc_PreState_Container_PS(preJson).left
                    |  if (verbose) {
                    |    println("Pre-State Values:")
                    |    println(s"  $$preContainer")
                    |  }
                    |  assert(slang_rm.TempControlMixedSeL4CAmKES.TempControl_tcp_tc_GumboX.compute_CEP_Pre_Container(preContainer))
                    |}
                    |
                    |test(s"TempControlSystem_Instance_tcp_tc_postCompute: Check Post-condition$suffix") {
                    |  val preJson: String = st${tq}${preContainer.get}${tq}.render
                    |  val postJson: String = st${tq}${postContainer.get}${tq}.render
                    |  val preContainer = slang_rm.JSON.toTempControlMixedSeL4CAmKESTempControl_tcp_tc_PreState_Container_PS(preJson).left
                    |  val postContainer = slang_rm.JSON.toTempControlMixedSeL4CAmKESTempControl_tcp_tc_PostState_Container_PS(postJson).left
                    |  if (verbose) {
                    |    println("Pre-State Values:")
                    |    println(s"  $$preContainer")
                    |    println("Post-State Values:")
                    |    println(s"  $$postContainer");
                    |  }
                    |  assert(slang_rm.TempControlMixedSeL4CAmKES.TempControl_tcp_tc_GumboX.compute_CEP_Post_Container(preContainer, postContainer))
                    |}
                    |// End test cases for TempControlSystem_Instance_tcp_tc_postCompute""")

      case _ => return st"// TODO ${observationKind}"
    }
  }

  def getUpdates(bridge_id: art.Art.BridgeId, observationKind: ObservationKind.Type, container: art.DataContent): Map[String, String] = {
    observationKind match {
      case slang_rm.runtimemonitor.ObservationKind.TempControlSystem_Instance_tsp_ts_postInit =>
        var updates: Map[String, String] = Map.empty
        val postContainer = container.asInstanceOf[slang_rm.TempControlMixedSeL4CAmKES.TempSensor_tsp_ts_PostState_Container_PS]
        updates = updates + s"${bridge_id}_Out_currentTemp" ~> postContainer.api_currentTemp.string
        if (postContainer.api_tempChanged.nonEmpty) {
          updates = updates + s"${bridge_id}_Out_tempChanged" ~> postContainer.api_tempChanged.get.string
        }
        return updates
      case slang_rm.runtimemonitor.ObservationKind.TempControlSystem_Instance_tcp_tc_postInit =>
        var updates: Map[String, String] = Map.empty
        val postContainer = container.asInstanceOf[slang_rm.TempControlMixedSeL4CAmKES.TempControl_tcp_tc_PostState_Container_PS]
        updates = updates + s"${bridge_id}_Out_currentSetPoint" ~> postContainer.currentSetPoint.string
        updates = updates + s"${bridge_id}_Out_currentFanState" ~> postContainer.currentFanState.string
        updates = updates + s"${bridge_id}_Out_latestTemp" ~> postContainer.latestTemp.string
        if (postContainer.api_fanCmd.nonEmpty) {
          updates = updates + s"${bridge_id}_Out_fanCmd" ~> postContainer.api_fanCmd.get.string
        }
        return updates
      case slang_rm.runtimemonitor.ObservationKind.TempControlSystem_Instance_fp_f_postInit =>
        var updates: Map[String, String] = Map.empty
        val postContainer = container.asInstanceOf[slang_rm.TempControlMixedSeL4CAmKES.Fan_fp_f_PostState_Container_PS]
        if (postContainer.api_fanAck.nonEmpty) {
          updates = updates + s"${bridge_id}_Out_fanAck" ~> postContainer.api_fanAck.get.string
        }
        return updates
      case slang_rm.runtimemonitor.ObservationKind.TempControlSystem_Instance_tsp_ts_preCompute =>
        var updates: Map[String, String] = Map.empty
        val preContainer = container.asInstanceOf[slang_rm.TempControlMixedSeL4CAmKES.TempSensor_tsp_ts_PreState_Container_PS]
        return updates
      case slang_rm.runtimemonitor.ObservationKind.TempControlSystem_Instance_tcp_tc_preCompute =>
        var updates: Map[String, String] = Map.empty
        val preContainer = container.asInstanceOf[slang_rm.TempControlMixedSeL4CAmKES.TempControl_tcp_tc_PreState_Container_PS]
        updates = updates + s"${bridge_id}_In_In_currentSetPoint" ~> preContainer.In_currentSetPoint.string
        updates = updates + s"${bridge_id}_In_In_currentFanState" ~> preContainer.In_currentFanState.string
        updates = updates + s"${bridge_id}_In_In_latestTemp" ~> preContainer.In_latestTemp.string
        updates = updates + s"${bridge_id}_In_currentTemp" ~> preContainer.api_currentTemp.string
        if (preContainer.api_tempChanged.nonEmpty) {
          updates = updates + s"${bridge_id}_In_tempChanged" ~> preContainer.api_tempChanged.get.string
        }
        if (preContainer.api_fanAck.nonEmpty) {
          updates = updates + s"${bridge_id}_In_fanAck" ~> preContainer.api_fanAck.get.string
        }
        if (preContainer.api_setPoint.nonEmpty) {
          updates = updates + s"${bridge_id}_In_setPoint" ~> preContainer.api_setPoint.get.string
        }
        return updates
      case slang_rm.runtimemonitor.ObservationKind.TempControlSystem_Instance_fp_f_preCompute =>
        var updates: Map[String, String] = Map.empty
        val preContainer = container.asInstanceOf[slang_rm.TempControlMixedSeL4CAmKES.Fan_fp_f_PreState_Container_PS]
        if (preContainer.api_fanCmd.nonEmpty) {
          updates = updates + s"${bridge_id}_In_fanCmd" ~> preContainer.api_fanCmd.get.string
        }
        return updates
      case slang_rm.runtimemonitor.ObservationKind.TempControlSystem_Instance_tsp_ts_postCompute =>
        var updates: Map[String, String] = Map.empty
        val postContainer = container.asInstanceOf[slang_rm.TempControlMixedSeL4CAmKES.TempSensor_tsp_ts_PostState_Container_PS]
        updates = updates + s"${bridge_id}_Out_currentTemp" ~> postContainer.api_currentTemp.string
        if (postContainer.api_tempChanged.nonEmpty) {
          updates = updates + s"${bridge_id}_Out_tempChanged" ~> postContainer.api_tempChanged.get.string
        }
        return updates
      case slang_rm.runtimemonitor.ObservationKind.TempControlSystem_Instance_tcp_tc_postCompute =>
        var updates: Map[String, String] = Map.empty
        val postContainer = container.asInstanceOf[slang_rm.TempControlMixedSeL4CAmKES.TempControl_tcp_tc_PostState_Container_PS]
        updates = updates + s"${bridge_id}_Out_currentSetPoint" ~> postContainer.currentSetPoint.string
        updates = updates + s"${bridge_id}_Out_currentFanState" ~> postContainer.currentFanState.string
        updates = updates + s"${bridge_id}_Out_latestTemp" ~> postContainer.latestTemp.string
        if (postContainer.api_fanCmd.nonEmpty) {
          updates = updates + s"${bridge_id}_Out_fanCmd" ~> postContainer.api_fanCmd.get.string
        }
        return updates
      case slang_rm.runtimemonitor.ObservationKind.TempControlSystem_Instance_fp_f_postCompute =>
        var updates: Map[String, String] = Map.empty
        val postContainer = container.asInstanceOf[slang_rm.TempControlMixedSeL4CAmKES.Fan_fp_f_PostState_Container_PS]
        if (postContainer.api_fanAck.nonEmpty) {
          updates = updates + s"${bridge_id}_Out_fanAck" ~> postContainer.api_fanAck.get.string
        }
        return updates
      case _ => return Map.empty
    }
  }
}