// #Sireum

package slang_rm.runtimemonitor

import org.sireum._
import slang_rm._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

@enum object ObservationKind {
  "TempControlSystem_Instance_tsp_ts_postInit"
  "TempControlSystem_Instance_tsp_ts_preCompute"
  "TempControlSystem_Instance_tsp_ts_postCompute"
  "TempControlSystem_Instance_tcp_tc_postInit"
  "TempControlSystem_Instance_tcp_tc_preCompute"
  "TempControlSystem_Instance_tcp_tc_postCompute"
  "TempControlSystem_Instance_fp_f_postInit"
  "TempControlSystem_Instance_fp_f_preCompute"
  "TempControlSystem_Instance_fp_f_postCompute"
}
