// #Sireum

package slang.TempControlMixed

import org.sireum._
import slang._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

object GUMBO__Library {
  @strictpure def inRange(temp: TempControlMixed.Temperature): Base_Types.Boolean = temp.degrees >= -40.0f &&
    temp.degrees <= 122.0f
}
